import type {
  ActivityEvent,
  ApiToken,
  AuditEvent,
  AuroraService,
  CapabilityFeature,
  ChatMessage,
  ConfigEntry,
  Conversation,
  Device,
  MeshPeer,
  ModelProvider,
  Permission,
  Principal,
  Role,
  RouteCandidate,
  SpecCoverageRow,
} from './types'

export const deploymentSummary = {
  mode: 'Server' as const,
  route: 'Local' as const,
  privacy: 'personal' as const,
  identity: 'Admin' as const,
  health: 'Healthy' as const,
  nodeName: 'aurora-prod-01',
  region: 'self-hosted · fra1',
  version: 'v0.9.4',
  uptime: '18d 4h',
}

export const services: AuroraService[] = [
  {
    module: 'Gateway',
    status: 'Healthy',
    instanceId: 'gw-7f3a',
    capabilities: ['registry', 'http', 'openapi', 'webrtc', 'gateway-builtins'],
    methods: [
      { name: 'Registry', busTopic: 'Gateway.Registry', methodType: 'gateway', exposure: 'gateway_builtin', permissions: [], routePath: '/api/registry', backendCoverage: 'implemented', note: 'Gateway-native endpoint, not a dynamic bus route.' },
      { name: 'Services', busTopic: 'Gateway.Services', methodType: 'gateway', exposure: 'gateway_builtin', permissions: [], routePath: '/api/services', backendCoverage: 'implemented', note: 'Gateway-native endpoint used by admin overview/services.' },
      { name: 'Routes', busTopic: 'Gateway.Routes', methodType: 'gateway', exposure: 'gateway_builtin', permissions: [], routePath: '/api/routes', backendCoverage: 'implemented', note: 'Route inventory generated from registry.' },
      { name: 'ConnectedPeers', busTopic: 'Gateway.AdminPeers', methodType: 'manage', exposure: 'gateway_builtin', permissions: ['Auth.manage'], routePath: '/api/admin/peers', backendCoverage: 'implemented', note: 'Live WebRTC peer state, distinct from persisted Auth mesh peers.' },
    ],
    lastHeartbeat: '2s ago',
    routeAvailability: 'Local',
    description: 'Service discovery, registry, HTTP/OpenAPI routes and mesh signaling. Includes built-in endpoints outside the dynamic contract registry.',
  },
  {
    module: 'Auth',
    status: 'Healthy',
    instanceId: 'auth-91b2',
    capabilities: ['login', 'pairing', 'rbac', 'tokens', 'audit', 'mesh'],
    methods: [
      { name: 'Login', busTopic: 'Auth.Login', methodType: 'use', exposure: 'both', permissions: [], routePath: '/api/Auth/Login', backendCoverage: 'partial', note: 'Public bypass casing must be runtime-smoke-tested before hardcoding paths.' },
      { name: 'WhoAmI', busTopic: 'Auth.WhoAmI', methodType: 'use', exposure: 'both', permissions: [], routePath: '/api/Auth/WhoAmI', backendCoverage: 'implemented' },
      { name: 'ListPrincipals', busTopic: 'Auth.ListPrincipals', methodType: 'manage', exposure: 'both', permissions: ['Auth.manage'], routePath: '/api/Auth/ListPrincipals', backendCoverage: 'implemented' },
      { name: 'SetPermissions', busTopic: 'Auth.SetPermissions', methodType: 'manage', exposure: 'both', permissions: ['Auth.manage'], routePath: '/api/Auth/SetPermissions', backendCoverage: 'implemented' },
      { name: 'RevokeToken', busTopic: 'Auth.RevokeToken', methodType: 'manage', exposure: 'both', permissions: ['Auth.manage'], routePath: '/api/Auth/RevokeToken', backendCoverage: 'implemented' },
      { name: 'AuditLog', busTopic: 'Auth.AuditLog', methodType: 'manage', exposure: 'both', permissions: ['Auth.manage'], routePath: '/api/Auth/AuditLog', backendCoverage: 'implemented' },
    ],
    lastHeartbeat: '1s ago',
    routeAvailability: 'Local',
    description: 'Login/session, pairing, principals, tokens, devices, audit and mesh credentials. UI must use backend-canonical Auth.* permissions.',
  },
  {
    module: 'Orchestrator',
    status: 'Healthy',
    instanceId: 'orch-22c8',
    capabilities: ['chat', 'tools', 'routing'],
    methods: [
      { name: 'ExternalUserInput', busTopic: 'Orchestrator.ExternalUserInput', methodType: 'use', exposure: 'external', permissions: ['Orchestrator.use'], routePath: '/api/Orchestrator/ExternalUserInput', backendCoverage: 'implemented' },
      { name: 'UserInput', busTopic: 'Orchestrator.UserInput', methodType: 'use', exposure: 'internal', permissions: ['Orchestrator.use'], backendCoverage: 'internal_only', note: 'Local/Tauri bus path only, not HTTP generated.' },
      { name: 'Response', busTopic: 'Orchestrator.Response', methodType: 'event', exposure: 'internal', permissions: [], backendCoverage: 'partial', note: 'Streaming/event transport remains a product gap.' },
      { name: 'Cancel', busTopic: 'Orchestrator.Cancel', methodType: 'planned', exposure: 'planned', permissions: ['Orchestrator.use'], backendCoverage: 'missing_contract', note: 'Needed for interrupt/stop generation UX.' },
    ],
    lastHeartbeat: '3s ago',
    routeAvailability: 'Local',
    description: 'User input handling, tool result routing and assistant response generation.',
  },
  {
    module: 'TTS',
    status: 'Degraded',
    instanceId: 'tts-04ad',
    capabilities: ['synthesize', 'playback'],
    methods: [
      { name: 'Synthesize', busTopic: 'TTS.Synthesize', methodType: 'use', exposure: 'both', permissions: ['TTS.use'], routePath: '/api/TTS/Synthesize', backendCoverage: 'implemented' },
      { name: 'Request', busTopic: 'TTS.Request', methodType: 'use', exposure: 'internal', permissions: ['TTS.use'], backendCoverage: 'internal_only', note: 'Playback request is local/internal; server/web should use synthesize or native playback.' },
      { name: 'Stop', busTopic: 'TTS.Stop', methodType: 'use', exposure: 'internal', permissions: ['TTS.use'], backendCoverage: 'internal_only' },
    ],
    lastHeartbeat: '14s ago',
    routeAvailability: 'Remote',
    description: 'Speech synthesis and playback controls. Voice model warming up; remote HTTP does not imply local speaker control.',
  },
  {
    module: 'STT',
    status: 'Healthy',
    instanceId: 'stt-66f1',
    capabilities: ['wakeword', 'transcribe', 'listen'],
    methods: [
      { name: 'Transcribe', busTopic: 'Transcription.Transcribe', methodType: 'use', exposure: 'both', permissions: ['Transcription.use'], routePath: '/api/Transcription/Transcribe', backendCoverage: 'implemented' },
      { name: 'WakeWordDetect', busTopic: 'WakeWord.Detect', methodType: 'use', exposure: 'both', permissions: ['WakeWord.use'], routePath: '/api/WakeWord/Detect', backendCoverage: 'implemented' },
      { name: 'CoordinatorListen', busTopic: 'STTCoordinator.Listen', methodType: 'use', exposure: 'internal', permissions: ['STTCoordinator.use'], backendCoverage: 'internal_only', note: 'Server web cannot start server microphone listening as if it were local client capture.' },
    ],
    lastHeartbeat: '4s ago',
    routeAvailability: 'Local',
    description: 'Listening, wakeword and transcription pipeline. UI must split local capture from remote transcription.',
  },
  {
    module: 'Tooling',
    status: 'Healthy',
    instanceId: 'tool-1a9e',
    capabilities: ['tools', 'mcp', 'execute'],
    methods: [
      { name: 'GetTools', busTopic: 'Tooling.GetTools', methodType: 'use', exposure: 'both', permissions: ['Tooling.use'], routePath: '/api/Tooling/GetTools', backendCoverage: 'implemented' },
      { name: 'ExecuteTool', busTopic: 'Tooling.ExecuteTool', methodType: 'use', exposure: 'both', permissions: ['Tooling.use'], routePath: '/api/Tooling/ExecuteTool', backendCoverage: 'implemented' },
      { name: 'GetMCPStatus', busTopic: 'Tooling.GetMCPStatus', methodType: 'use', exposure: 'both', permissions: ['Tooling.use'], routePath: '/api/Tooling/GetMCPStatus', backendCoverage: 'implemented' },
      { name: 'ReloadMCPTools', busTopic: 'Tooling.ReloadMCPTools', methodType: 'manage', exposure: 'internal', permissions: ['Tooling.manage'], backendCoverage: 'internal_only', note: 'Admin UI can show planned/local-only reload, but HTTP route is not exposed today.' },
    ],
    lastHeartbeat: '2s ago',
    routeAvailability: 'Local',
    description: 'Tool registry, MCP status and tool execution with schema/risk approval UX.',
  },
  {
    module: 'Scheduler',
    status: 'Healthy',
    instanceId: 'sch-3b7d',
    capabilities: ['cron', 'jobs'],
    methods: [
      { name: 'ListJobs', busTopic: 'Scheduler.ListJobs', methodType: 'use', exposure: 'both', permissions: ['Scheduler.use'], routePath: '/api/Scheduler/ListJobs', backendCoverage: 'implemented' },
      { name: 'Schedule', busTopic: 'Scheduler.Schedule', methodType: 'manage', exposure: 'both', permissions: ['Scheduler.manage'], routePath: '/api/Scheduler/Schedule', backendCoverage: 'implemented' },
      { name: 'Cancel', busTopic: 'Scheduler.Cancel', methodType: 'manage', exposure: 'both', permissions: ['Scheduler.manage'], routePath: '/api/Scheduler/Cancel', backendCoverage: 'implemented' },
      { name: 'Pause', busTopic: 'Scheduler.Pause', methodType: 'manage', exposure: 'internal', permissions: ['Scheduler.manage'], backendCoverage: 'internal_only' },
      { name: 'Resume', busTopic: 'Scheduler.Resume', methodType: 'manage', exposure: 'internal', permissions: ['Scheduler.manage'], backendCoverage: 'internal_only' },
    ],
    lastHeartbeat: '6s ago',
    routeAvailability: 'Local',
    description: 'Schedule, cancel, pause, resume and list jobs. UI needs explicit lifecycle controls and event timeline.',
  },
  {
    module: 'Config',
    status: 'Healthy',
    instanceId: 'cfg-58c0',
    capabilities: ['get', 'set', 'validate', 'plugin'],
    methods: [
      { name: 'Get', busTopic: 'Config.Get', methodType: 'use', exposure: 'both', permissions: ['Config.use'], routePath: '/api/Config/Get', backendCoverage: 'implemented' },
      { name: 'Set', busTopic: 'Config.Set', methodType: 'manage', exposure: 'both', permissions: ['Config.manage'], routePath: '/api/Config/Set', backendCoverage: 'implemented' },
      { name: 'Validate', busTopic: 'Config.Validate', methodType: 'use', exposure: 'both', permissions: ['Config.use'], routePath: '/api/Config/Validate', backendCoverage: 'implemented' },
      { name: 'ReloadService', busTopic: 'Config.ReloadService', methodType: 'manage', exposure: 'internal', permissions: ['Config.manage'], backendCoverage: 'internal_only', note: 'Reload is not an external generated route.' },
      { name: 'Rollback', busTopic: 'Config.Rollback', methodType: 'planned', exposure: 'planned', permissions: ['Config.manage'], backendCoverage: 'missing_contract' },
    ],
    lastHeartbeat: '5s ago',
    routeAvailability: 'Local',
    description: 'Configuration get/set/validate/plugin state. Diff is currently client-side; rollback/versioning is planned.',
  },
  {
    module: 'DB',
    status: 'Healthy',
    instanceId: 'db-9c11',
    capabilities: ['messages', 'rag', 'audit'],
    methods: [
      { name: 'GetMessages', busTopic: 'DB.GetMessages', methodType: 'use', exposure: 'both', permissions: ['DB.use'], routePath: '/api/DB/GetMessages', backendCoverage: 'implemented' },
      { name: 'GetMessagesForDate', busTopic: 'DB.GetMessagesForDate', methodType: 'use', exposure: 'both', permissions: ['DB.use'], routePath: '/api/DB/GetMessagesForDate', backendCoverage: 'implemented' },
      { name: 'RAGSearch', busTopic: 'DB.RAGSearch', methodType: 'use', exposure: 'both', permissions: ['DB.use'], routePath: '/api/DB/RAGSearch', backendCoverage: 'implemented' },
      { name: 'RAGDelete', busTopic: 'DB.RAGDelete', methodType: 'manage', exposure: 'internal', permissions: ['DB.manage'], backendCoverage: 'internal_only' },
    ],
    lastHeartbeat: '2s ago',
    routeAvailability: 'Local',
    description: 'Messages and RAG search are externally readable; many mutation/storage internals stay local/internal.',
  },
  {
    module: 'Supervisor',
    status: 'Needs attention',
    instanceId: 'sup-7e2f',
    capabilities: ['status', 'restart'],
    methods: [
      { name: 'GetStatus', busTopic: 'Supervisor.GetStatus', methodType: 'use', exposure: 'both', permissions: ['Supervisor.use'], routePath: '/api/Supervisor/GetStatus', backendCoverage: 'implemented' },
      { name: 'RestartService', busTopic: 'Supervisor.RestartService', methodType: 'manage', exposure: 'internal', permissions: ['Supervisor.manage'], backendCoverage: 'partial', note: 'Implementation is narrower than the contract model; start/stop should be displayed as planned/blocked.' },
      { name: 'StopService', busTopic: 'Supervisor.StopService', methodType: 'planned', exposure: 'planned', permissions: ['Supervisor.manage'], backendCoverage: 'missing_contract' },
    ],
    lastHeartbeat: '41s ago',
    routeAvailability: 'Local',
    description: 'Runtime status/control. The production UI must not overstate start/stop availability.',
  },
]

export const principals: Principal[] = [
  {
    id: 'p-001',
    name: 'admin',
    kind: 'user',
    isAdmin: true,
    role: 'Owner',
    permissions: ['*'],
    created: '2026-01-12',
    lastActive: '2m ago',
  },
  {
    id: 'p-002',
    name: 'maya.chen',
    kind: 'user',
    isAdmin: false,
    role: 'Member',
    permissions: ['Orchestrator.use', 'DB.use', 'Tooling.use'],
    created: '2026-03-04',
    lastActive: '1h ago',
  },
  {
    id: 'p-003',
    name: 'ops-bot',
    kind: 'service',
    isAdmin: false,
    role: 'Automation',
    permissions: ['Scheduler.manage', 'Tooling.use'],
    created: '2026-02-20',
    lastActive: '5m ago',
  },
  {
    id: 'p-004',
    name: 'studio-mac',
    kind: 'device',
    isAdmin: false,
    role: 'Member',
    permissions: ['Orchestrator.use', 'DB.use'],
    created: '2026-04-18',
    lastActive: '3d ago',
  },
  {
    id: 'p-005',
    name: 'family-tablet',
    kind: 'device',
    isAdmin: false,
    role: 'Guest',
    permissions: ['Orchestrator.use'],
    created: '2026-05-30',
    lastActive: '12m ago',
  },
]

export const tokens: ApiToken[] = [
  {
    id: 't-01',
    prefix: 'aur_live_7Kp…',
    principal: 'admin',
    scopes: ['*'],
    created: '2026-01-12',
    expires: 'never',
    status: 'active',
  },
  {
    id: 't-02',
    prefix: 'aur_live_9Qz…',
    principal: 'ops-bot',
    scopes: ['Scheduler.manage', 'Tooling.use'],
    created: '2026-02-20',
    expires: '2026-08-20',
    status: 'active',
  },
  {
    id: 't-03',
    prefix: 'aur_live_3Lm…',
    principal: 'maya.chen',
    scopes: ['Orchestrator.use', 'DB.use'],
    created: '2026-05-01',
    expires: '2026-07-01',
    status: 'expiring',
  },
  {
    id: 't-04',
    prefix: 'aur_live_0Xw…',
    principal: 'studio-mac',
    scopes: ['Orchestrator.use'],
    created: '2026-03-15',
    expires: '2026-06-15',
    status: 'revoked',
  },
]

export const devices: Device[] = [
  {
    id: 'd-01',
    name: 'studio-mac',
    trust: 'trusted',
    user: 'admin',
    lastSeen: '3d ago',
    source: 'Local',
    platform: 'macOS · Desktop Local',
  },
  {
    id: 'd-02',
    name: 'pixel-9',
    trust: 'trusted',
    user: 'maya.chen',
    lastSeen: '1h ago',
    source: 'Remote',
    platform: 'Android · Thin',
  },
  {
    id: 'd-03',
    name: 'family-tablet',
    trust: 'pending',
    user: '—',
    lastSeen: '12m ago',
    source: 'Mesh Peer',
    platform: 'Android · Local-light',
  },
  {
    id: 'd-04',
    name: 'iphone-15',
    trust: 'trusted',
    user: 'maya.chen',
    lastSeen: '4h ago',
    source: 'Remote',
    platform: 'iOS · Thin',
  },
]

export const meshPeers: MeshPeer[] = [
  {
    id: 'm-01',
    name: 'home-server',
    fingerprint: 'SHA256:9f2a…c41e',
    status: 'approved',
    permissions: ['Orchestrator.use', 'models.remote'],
    latencyMs: 12,
    lastSeen: '4s ago',
    routeQuality: 'excellent',
  },
  {
    id: 'm-02',
    name: 'studio-gpu',
    fingerprint: 'SHA256:1b7d…88af',
    status: 'approved',
    permissions: ['models.remote'],
    latencyMs: 34,
    lastSeen: '20s ago',
    routeQuality: 'good',
  },
  {
    id: 'm-03',
    name: 'cabin-node',
    fingerprint: 'SHA256:5e0c…2d19',
    status: 'pending',
    permissions: [],
    latencyMs: 180,
    lastSeen: '2m ago',
    routeQuality: 'poor',
  },
]

export const auditEvents: AuditEvent[] = [
  {
    id: 'a-01',
    timestamp: '2026-06-14 09:42:11',
    actor: 'admin',
    action: 'token.revoke',
    resource: 'aur_live_0Xw…',
    severity: 'warning',
    result: 'success',
  },
  {
    id: 'a-02',
    timestamp: '2026-06-14 09:31:02',
    actor: 'admin',
    action: 'config.set',
    resource: 'gateway.cors.origins',
    severity: 'critical',
    result: 'success',
  },
  {
    id: 'a-03',
    timestamp: '2026-06-14 08:58:44',
    actor: 'maya.chen',
    action: 'principal.update',
    resource: 'p-005',
    severity: 'info',
    result: 'denied',
  },
  {
    id: 'a-04',
    timestamp: '2026-06-14 08:12:09',
    actor: 'ops-bot',
    action: 'tool.execute',
    resource: 'web.search',
    severity: 'info',
    result: 'success',
  },
  {
    id: 'a-05',
    timestamp: '2026-06-13 22:05:51',
    actor: 'admin',
    action: 'mesh.approve',
    resource: 'studio-gpu',
    severity: 'warning',
    result: 'success',
  },
]

export const configEntries: ConfigEntry[] = [
  {
    key: 'gateway.http.port',
    section: 'gateway',
    value: '8770',
    source: 'config.json',
    description: 'HTTP listen port for the Gateway service.',
    restartRequired: true,
  },
  {
    key: 'gateway.cors.origins',
    section: 'gateway',
    value: 'https://app.aurora.local',
    source: 'config.json',
    description: 'Allowed CORS origins for browser clients.',
  },
  {
    key: 'auth.session.ttl',
    section: 'auth',
    value: '24h',
    source: 'default',
    description: 'Default session token lifetime.',
  },
  {
    key: 'auth.secret',
    section: 'auth',
    value: '••••••••••••',
    source: 'env',
    description: 'Signing secret for session tokens. Managed by environment.',
    secret: true,
  },
  {
    key: 'models.default.provider',
    section: 'models',
    value: 'llama.cpp',
    source: 'config.json',
    description: 'Default model provider for assistant chat.',
    restartRequired: true,
  },
  {
    key: 'privacy.allow_remote_fallback',
    section: 'privacy',
    value: 'false',
    source: 'config.json',
    description: 'Allow personal data to fall back to remote routes.',
  },
]

export const activityEvents: ActivityEvent[] = [
  {
    id: 'e-01',
    type: 'assistant',
    title: 'Response delivered',
    detail: 'llama.cpp · local route · 1.2s',
    time: 'now',
  },
  {
    id: 'e-02',
    type: 'warning',
    title: 'TTS degraded',
    detail: 'Voice model warming up, text replies unaffected',
    time: '1m',
  },
  {
    id: 'e-03',
    type: 'mesh',
    title: 'Peer pairing request',
    detail: 'cabin-node is awaiting approval',
    time: '2m',
  },
  {
    id: 'e-04',
    type: 'config',
    title: 'Config updated',
    detail: 'gateway.cors.origins changed by admin',
    time: '11m',
  },
  {
    id: 'e-05',
    type: 'audit',
    title: 'Token revoked',
    detail: 'aur_live_0Xw… revoked by admin',
    time: '18m',
  },
  {
    id: 'e-06',
    type: 'service',
    title: 'Scheduler ran job',
    detail: 'daily-digest completed',
    time: '34m',
  },
]

export const conversations: Conversation[] = [
  {
    id: 'c-01',
    title: 'Draft launch announcement',
    route: 'Local',
    model: 'llama.cpp',
    privacyClass: 'personal',
    updated: '2m ago',
    pinned: true,
  },
  {
    id: 'c-02',
    title: 'Summarize quarterly metrics',
    route: 'Remote',
    model: 'gpt-class',
    privacyClass: 'sensitive',
    updated: '1h ago',
  },
  {
    id: 'c-03',
    title: 'Refactor mesh routing notes',
    route: 'Mesh Peer',
    model: 'studio-gpu',
    privacyClass: 'personal',
    updated: '5h ago',
  },
  {
    id: 'c-04',
    title: 'Personal journal reflection',
    route: 'Local',
    model: 'llama.cpp',
    privacyClass: 'secret',
    updated: 'yesterday',
  },
]

export const sampleMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    role: 'user',
    content: 'Draft a short launch announcement for the Aurora 0.9 release.',
    privacyClass: 'personal',
  },
  {
    id: 'msg-2',
    role: 'assistant',
    content:
      "Here's a concise draft:\n\nAurora 0.9 is here. Your private assistant now runs across desktop, server, mesh and mobile — with a unified operator cockpit for services, RBAC, and diagnostics. Every route is observable, every admin action is auditable, and local-first is the default.",
    route: 'Local',
    model: 'llama.cpp · 8B',
    privacyClass: 'personal',
    citations: ['release-notes.md', 'changelog/0.9.0'],
  },
  {
    id: 'msg-3',
    role: 'user',
    content: 'Now check our latest deployment health and summarize any warnings.',
    privacyClass: 'personal',
  },
  {
    id: 'msg-4',
    role: 'assistant',
    content: 'I can call the diagnostics tool to read current service health. This is a read-only action on the local node.',
    route: 'Local',
    model: 'llama.cpp · 8B',
    privacyClass: 'personal',
    toolCall: {
      name: 'diagnostics.serviceHealth',
      target: 'Gateway',
      inputs: { scope: 'all-services', includeLogs: 'false' },
      risk: 'read-only',
      dataLeavesDevice: false,
      status: 'pending',
    },
  },
]

export const routeCandidates: RouteCandidate[] = [
  {
    kind: 'Local',
    label: 'Local node · llama.cpp',
    model: 'llama-3-8b-instruct',
    privacyClass: 'personal',
    latencyMs: 1200,
    cost: 'free',
    available: true,
    target: 'local-node:aurora-prod-01',
    auditRequired: false,
    note: 'Runs entirely on this device. Recommended for personal data.',
  },
  {
    kind: 'Remote',
    label: 'Server gateway',
    model: 'gpt-class-large',
    privacyClass: 'sensitive',
    latencyMs: 600,
    cost: 'metered',
    available: true,
    target: 'https://gateway.example.internal',
    auditRequired: true,
    payloadPreview: 'redacted text + metadata only',
    blockers: ['privacy.allow_remote_fallback=false for sensitive/secret classes'],
    note: 'Higher quality. Data leaves the device — requires policy for sensitive content.',
  },
  {
    kind: 'Mesh Peer',
    label: 'studio-gpu (peer)',
    model: 'qwen-32b',
    privacyClass: 'personal',
    latencyMs: 340,
    cost: 'low',
    available: true,
    target: 'peer:studio-gpu',
    auditRequired: true,
    payloadPreview: 'redacted text + route metadata',
    blockers: ['peer must advertise capability manifest', 'peer permission scope checked'],
    note: 'Trusted peer on your mesh. Good for heavier local-network tasks.',
  },
  {
    kind: 'Native Mobile',
    label: 'On-device mobile runtime',
    model: 'phi-mini',
    privacyClass: 'secret',
    latencyMs: 2200,
    cost: 'free',
    available: false,
    target: 'native-mobile-runtime',
    auditRequired: false,
    blockers: ['native mobile runtime provider unavailable on this platform'],
    note: 'Requires native mobile inference runtime — not available on this platform.',
  },
]

export const modelProviders: ModelProvider[] = [
  {
    id: 'mp-01',
    name: 'llama.cpp (local)',
    kind: 'local',
    status: 'available',
    size: '8B · Q4_K_M',
    contextWindow: '8k',
    health: 'Healthy',
  },
  {
    id: 'mp-02',
    name: 'Server gateway provider',
    kind: 'remote',
    status: 'remote_only',
    contextWindow: '128k',
    health: 'Healthy',
  },
  {
    id: 'mp-03',
    name: 'studio-gpu (peer)',
    kind: 'mesh',
    status: 'available',
    size: '32B',
    contextWindow: '32k',
    health: 'Healthy',
  },
  {
    id: 'mp-04',
    name: 'Mobile local-light',
    kind: 'mobile',
    status: 'unsupported_platform',
    contextWindow: '4k',
    health: 'Offline',
  },
]

export const capabilityFeatures: CapabilityFeature[] = [
  {
    id: 'assistant.chat.text',
    label: 'Text chat',
    category: 'assistant',
    state: 'available',
    privacyClass: 'personal',
    requiredServices: ['Orchestrator'],
    requiredMethods: ['Orchestrator.ExternalUserInput'],
    requiredPermissions: ['Orchestrator.use'],
    backendCoverage: 'implemented',
    transportNotes: ['HTTP uses generated POST route; local desktop can use internal bus path.'],
  },
  {
    id: 'assistant.chat.streaming',
    label: 'Streaming responses',
    category: 'assistant',
    state: 'degraded',
    privacyClass: 'personal',
    requiredServices: ['Orchestrator'],
    requiredMethods: ['Orchestrator.Response', 'Aurora.EventStream'],
    requiredPermissions: ['Orchestrator.use'],
    backendCoverage: 'missing_contract',
    transportNotes: ['Needs SSE/WebSocket/Tauri event adapter before production streaming.'],
    missing: ['Event stream contract'],
    note: 'Falls back to full-message delivery until the stream contract is defined.',
  },
  {
    id: 'assistant.voice.ptt',
    label: 'Push-to-talk voice',
    category: 'assistant',
    state: 'degraded',
    privacyClass: 'raw-audio',
    requiredServices: ['STT', 'TTS'],
    requiredMethods: ['Transcription.Transcribe', 'TTS.Synthesize', 'STTCoordinator.Listen (internal-only)'],
    requiredPermissions: ['Transcription.use', 'TTS.use', 'Orchestrator.use'],
    backendCoverage: 'partial',
    transportNotes: ['Server web captures client audio; local desktop may use STTCoordinator internal bus controls.'],
    missing: ['TTS healthy'],
    userActions: ['request_microphone'],
    note: 'TTS is warming up; replies will be text-only until it recovers.',
  },
  {
    id: 'assistant.voice.wake',
    label: 'Wake word',
    category: 'assistant',
    state: 'needs_native_permission',
    privacyClass: 'raw-audio',
    requiredServices: ['WakeWord', 'STT'],
    requiredMethods: ['WakeWord.Detect', 'WakeWord.ProcessAudio'],
    requiredPermissions: ['WakeWord.use', 'Transcription.use', 'Orchestrator.use'],
    backendCoverage: 'partial',
    transportNotes: ['Always-on wake is native/platform-gated; iOS does not allow Siri replacement.'],
    missing: ['Microphone permission', 'Autostart permission'],
    userActions: ['request_microphone', 'open_settings'],
  },
  {
    id: 'assistant.attachments',
    label: 'File & context attach',
    category: 'assistant',
    state: 'missing_service',
    privacyClass: 'sensitive',
    requiredServices: ['Attachments'],
    requiredMethods: ['Attachment.Ingest (planned)', 'Native.ShareIntake (planned)'],
    requiredPermissions: ['DB.manage'],
    backendCoverage: 'missing_contract',
    missing: ['Attachment ingestion contract'],
    note: 'Attachment ingestion contract is a planned backend gap.',
  },
  {
    id: 'admin.services.control',
    label: 'Start / stop services',
    category: 'admin',
    state: 'available',
    privacyClass: 'admin-critical',
    requiredServices: ['Supervisor'],
    requiredMethods: ['Supervisor.RestartService (partial/internal)', 'Supervisor.StopService (planned)'],
    requiredPermissions: ['Supervisor.manage'],
    backendCoverage: 'partial',
    missing: ['Start/stop production implementation', 'AdminAction backend envelope'],
    note: 'UI must not present service stop/start as fully available over HTTP today.',
  },
  {
    id: 'admin.diagnostics.export',
    label: 'Diagnostics export',
    category: 'diagnostics',
    state: 'degraded',
    privacyClass: 'admin-critical',
    requiredServices: ['Gateway'],
    requiredMethods: ['Diagnostics.ExportBundle (planned)', 'Gateway.Services'],
    requiredPermissions: ['Auth.manage'],
    backendCoverage: 'missing_contract',
    missing: ['Diagnostics bundle contract'],
    note: 'Partial — log/registry bundle contract still pending.',
  },
  {
    id: 'mesh.diagnostics',
    label: 'Mesh diagnostics',
    category: 'mesh',
    state: 'missing_service',
    privacyClass: 'sensitive',
    requiredServices: ['Gateway', 'Auth'],
    requiredMethods: ['Gateway.AdminPeers', 'Auth.MeshListPeers', 'Mesh.Diagnostics (planned)'],
    requiredPermissions: ['Auth.use'],
    backendCoverage: 'partial',
    missing: ['WebRTC metrics endpoint'],
  },
  {
    id: 'admin.backups',
    label: 'Backup & restore',
    category: 'admin',
    state: 'missing_service',
    privacyClass: 'admin-critical',
    requiredServices: ['Backup'],
    requiredMethods: ['Backup.Create (planned)', 'Backup.Restore (planned)'],
    requiredPermissions: ['Config.manage'],
    backendCoverage: 'missing_contract',
    missing: ['Backup/restore contract'],
  },
]

export const permissionCatalog: Permission[] = [
  { id: '*', label: 'Owner wildcard', scope: 'admin', backendNamespace: '*', description: 'Full backend wildcard. Use only for owner/system principals.' },
  { id: 'Orchestrator.use', label: 'Use assistant', scope: 'assistant', backendNamespace: 'Orchestrator', description: 'Send user input and receive assistant responses where exposed.' },
  { id: 'DB.use', label: 'Read memory and RAG', scope: 'memory', backendNamespace: 'DB', description: 'Read message history and run RAG searches.' },
  { id: 'DB.manage', label: 'Manage memory records', scope: 'memory', backendNamespace: 'DB', description: 'Delete or mutate stored memory/RAG records; many routes are internal-only today.' },
  { id: 'Tooling.use', label: 'List and execute tools', scope: 'tools', backendNamespace: 'Tooling', description: 'Read tool registry, MCP status and execute allowed tools.' },
  { id: 'Tooling.manage', label: 'Reload/manage tools', scope: 'tools', backendNamespace: 'Tooling', description: 'Manage MCP/tooling internals; reload is internal-only today.' },
  { id: 'Scheduler.use', label: 'Read schedules', scope: 'scheduler', backendNamespace: 'Scheduler', description: 'List scheduled jobs.' },
  { id: 'Scheduler.manage', label: 'Manage schedules', scope: 'scheduler', backendNamespace: 'Scheduler', description: 'Schedule, cancel, pause or resume jobs where exposed.' },
  { id: 'Supervisor.use', label: 'Read service status', scope: 'admin', backendNamespace: 'Supervisor', description: 'Read supervisor status.' },
  { id: 'Supervisor.manage', label: 'Restart/manage services', scope: 'admin', backendNamespace: 'Supervisor', description: 'High-risk service control; start/stop support is not fully implemented.' },
  { id: 'Auth.use', label: 'Use auth/session APIs', scope: 'admin', backendNamespace: 'Auth', description: 'Read limited auth/identity surfaces.' },
  { id: 'Auth.manage', label: 'Manage RBAC, devices, peers and audit', scope: 'admin', backendNamespace: 'Auth', description: 'Manage principals, tokens, devices, audit and persisted mesh peers.' },
  { id: 'Config.use', label: 'Read/validate configuration', scope: 'config', backendNamespace: 'Config', description: 'Read and validate configuration.' },
  { id: 'Config.manage', label: 'Apply configuration changes', scope: 'config', backendNamespace: 'Config', description: 'Set config/plugin values; rollback/versioning remains planned.' },
  { id: 'TTS.use', label: 'Use speech synthesis', scope: 'audio', backendNamespace: 'TTS', description: 'Synthesize speech; local playback controls may be internal-only.' },
  { id: 'Transcription.use', label: 'Use transcription', scope: 'audio', backendNamespace: 'Transcription', description: 'Transcribe supplied audio through exposed transcription route.' },
  { id: 'WakeWord.use', label: 'Use wakeword detection', scope: 'audio', backendNamespace: 'WakeWord', description: 'Run wakeword detection when platform/audio capability allows it.' },
]

export const roles: Role[] = [
  {
    id: 'role-owner',
    name: 'Owner',
    description: 'Full control over the assistant, services, and configuration. Cannot be edited.',
    system: true,
    principalCount: 1,
    permissions: ['*'],
  },
  {
    id: 'role-admin',
    name: 'Admin',
    description: 'Operate services, read audit logs, and manage most configuration.',
    principalCount: 2,
    permissions: [
      'Orchestrator.use',
      'DB.use',
      'DB.manage',
      'Tooling.use',
      'Tooling.manage',
      'Scheduler.manage',
      'Supervisor.manage',
      'Auth.manage',
      'Config.manage',
    ],
  },
  {
    id: 'role-member',
    name: 'Member',
    description: 'Use the assistant with tools and read access to memory.',
    principalCount: 5,
    permissions: ['Orchestrator.use', 'DB.use', 'Tooling.use'],
  },
  {
    id: 'role-automation',
    name: 'Automation',
    description: 'Service identity for scheduled jobs and background tools.',
    principalCount: 1,
    permissions: ['Scheduler.manage', 'Tooling.use'],
  },
  {
    id: 'role-guest',
    name: 'Guest',
    description: 'Conversation-only access on shared devices. No memory or tools.',
    principalCount: 3,
    permissions: ['Orchestrator.use'],
  },
]

export const specCoverageRows: SpecCoverageRow[] = [
  {
    id: 'sdk.transport.client',
    area: 'sdk',
    label: 'Transport-independent AuroraClient facade',
    specStatus: 'covered',
    backendStatus: 'missing_contract',
    mockStatus: 'partial',
    requiredBackendWork: ['Keep Gateway registry/OpenAPI stable', 'Add event stream contract', 'Add capability manifest endpoint or SDK-computed equivalent'],
    requiredMockWork: ['Keep screens fixture-driven but label backend/transport support states'],
    taskNotes: 'First production task cluster: SDK core, method registry ingestion, transport adapters, normalized result/error envelope.',
  },
  {
    id: 'auth.session.state_machine',
    area: 'admin',
    label: 'Auth/session lifecycle and recovery',
    specStatus: 'needs_refinement',
    backendStatus: 'partial',
    mockStatus: 'partial',
    requiredBackendWork: ['Smoke-test public auth route casing', 'Normalize contract error payloads vs HTTP errors'],
    requiredMockWork: ['Add 401/403/expired/auth-disabled/API-key/SYSTEM visual states'],
    taskNotes: 'Must precede all protected assistant/admin surfaces.',
  },
  {
    id: 'admin.action.envelope',
    area: 'admin',
    label: 'Server-enforced admin confirmation envelope',
    specStatus: 'covered',
    backendStatus: 'missing_contract',
    mockStatus: 'partial',
    requiredBackendWork: ['AdminAction draft/preview endpoint', 'Nonce + payload digest verification', 'Audit receipt and high-risk bypass prevention'],
    requiredMockWork: ['Show envelope fields and planned backend-enforced badge in every critical dialog'],
    taskNotes: 'Blocks production-safe config/RBAC/token/peer/service mutations.',
  },
  {
    id: 'gateway.method_exposure_matrix',
    area: 'sdk',
    label: 'Method exposure and route availability matrix',
    specStatus: 'needs_refinement',
    backendStatus: 'implemented',
    mockStatus: 'partial',
    requiredBackendWork: ['Expose generated registry consistently', 'Document gateway built-ins separately'],
    requiredMockWork: ['Use MethodInfo fields: bus_topic, exposure, method_type, required_perms'],
    taskNotes: 'Needed for feature gating across HTTP, Tauri local bus and mesh.',
  },
  {
    id: 'assistant.chat.streaming',
    area: 'assistant',
    label: 'Assistant streaming and cancellation',
    specStatus: 'partial',
    backendStatus: 'missing_contract',
    mockStatus: 'partial',
    requiredBackendWork: ['Unified event stream', 'Orchestrator cancellation contract'],
    requiredMockWork: ['Show queued/routing/streaming/cancel/retry states'],
    taskNotes: 'Implement after basic text invocation and event transport are proven.',
  },
  {
    id: 'voice.audio.mode_matrix',
    area: 'native',
    label: 'Voice/audio platform and transport matrix',
    specStatus: 'needs_refinement',
    backendStatus: 'partial',
    mockStatus: 'partial',
    requiredBackendWork: ['Clarify exposed transcription/synthesis vs internal listen/playback controls', 'Native audio bridge contracts'],
    requiredMockWork: ['Split local capture, remote transcription, local playback and native permission states'],
    taskNotes: 'Prevents server-web UI from pretending it controls local Python microphone/speaker state.',
  },
  {
    id: 'mesh.peer_state_split',
    area: 'mesh',
    label: 'Persisted peers vs live WebRTC sessions',
    specStatus: 'partial',
    backendStatus: 'partial',
    mockStatus: 'partial',
    requiredBackendWork: ['Peer capability manifest', 'Route diagnostics and WebRTC metrics'],
    requiredMockWork: ['Separate paired/trusted peer records from live connected peer sessions'],
    taskNotes: 'Required before mesh route policy can be production-worthy.',
  },
  {
    id: 'config.diff.rollback',
    area: 'admin',
    label: 'Config diff, validation, apply and rollback',
    specStatus: 'partial',
    backendStatus: 'partial',
    mockStatus: 'covered',
    requiredBackendWork: ['Backend diff/rollback/version contract', 'Reload impact preview'],
    requiredMockWork: ['Mark rollback as missing backend contract while keeping staged diff UI'],
    taskNotes: 'Config.Set/Validate exist; rollback and durable version history do not.',
  },
  {
    id: 'diagnostics.bundle',
    area: 'admin',
    label: 'Diagnostics bundle and redacted support export',
    specStatus: 'covered',
    backendStatus: 'missing_contract',
    mockStatus: 'covered',
    requiredBackendWork: ['Diagnostics bundle contract', 'Log/trace collection', 'Redaction policy and audit event'],
    requiredMockWork: ['Keep export as planned/missing-contract state'],
    taskNotes: 'Useful admin UX exists, backend route still required.',
  },
  {
    id: 'models.catalog.runtime',
    area: 'models',
    label: 'Model catalog, import, benchmark and mobile local-light runtime',
    specStatus: 'covered',
    backendStatus: 'missing_contract',
    mockStatus: 'partial',
    requiredBackendWork: ['Model provider/catalog contract', 'Download/import/benchmark contracts', 'Mobile runtime provider abstraction'],
    requiredMockWork: ['Keep desktop/server/mesh/mobile provider states explicit'],
    taskNotes: 'Do not wire model UI directly to one provider implementation.',
  },
]
