// Generated by scripts/generate_rust_contracts.py. Do not edit by hand.

use crate::{
    normalize_contract_value, validate_normalized_contract_schema, ContractParseError,
    EventDescriptor, MethodDescriptor, SchemaDescriptor, StreamingDescriptor,
};

pub mod models {
    pub mod empty_output {
        typify::import_types!(schema = "schema/empty_output.json");
    }
    pub use empty_output::EmptyOutput;
    pub mod route_explain_request {
        typify::import_types!(schema = "schema/route_explain_request.json");
    }
    pub use route_explain_request::RouteExplainRequest;
    pub mod route_explain_response {
        typify::import_types!(schema = "schema/route_explain_response.json");
    }
    pub use route_explain_response::RouteExplainResponse;
    pub mod stt_audio_chunk {
        typify::import_types!(schema = "schema/stt_audio_chunk.json");
    }
    pub use stt_audio_chunk::SttAudioChunk;
    pub mod stt_listen_request {
        typify::import_types!(schema = "schema/stt_listen_request.json");
    }
    pub use stt_listen_request::SttListenRequest;
    pub mod stt_listen_response {
        typify::import_types!(schema = "schema/stt_listen_response.json");
    }
    pub use stt_listen_response::SttListenResponse;
    pub mod stt_stop_listening_request {
        typify::import_types!(schema = "schema/stt_stop_listening_request.json");
    }
    pub use stt_stop_listening_request::SttStopListeningRequest;
    pub mod tts_audio_chunk_event {
        typify::import_types!(schema = "schema/tts_audio_chunk_event.json");
    }
    pub use tts_audio_chunk_event::TtsAudioChunkEvent;
    pub mod tts_create_voice_profile_request {
        typify::import_types!(schema = "schema/tts_create_voice_profile_request.json");
    }
    pub use tts_create_voice_profile_request::TtsCreateVoiceProfileRequest;
    pub mod tts_create_voice_profile_response {
        typify::import_types!(schema = "schema/tts_create_voice_profile_response.json");
    }
    pub use tts_create_voice_profile_response::TtsCreateVoiceProfileResponse;
    pub mod tts_delete_voice_profile_request {
        typify::import_types!(schema = "schema/tts_delete_voice_profile_request.json");
    }
    pub use tts_delete_voice_profile_request::TtsDeleteVoiceProfileRequest;
    pub mod tts_delete_voice_profile_response {
        typify::import_types!(schema = "schema/tts_delete_voice_profile_response.json");
    }
    pub use tts_delete_voice_profile_response::TtsDeleteVoiceProfileResponse;
    pub mod tts_get_capabilities_request {
        typify::import_types!(schema = "schema/tts_get_capabilities_request.json");
    }
    pub use tts_get_capabilities_request::TtsGetCapabilitiesRequest;
    pub mod tts_get_capabilities_response {
        typify::import_types!(schema = "schema/tts_get_capabilities_response.json");
    }
    pub use tts_get_capabilities_response::TtsGetCapabilitiesResponse;
    pub mod tts_get_voice_profile_request {
        typify::import_types!(schema = "schema/tts_get_voice_profile_request.json");
    }
    pub use tts_get_voice_profile_request::TtsGetVoiceProfileRequest;
    pub mod tts_get_voice_profile_response {
        typify::import_types!(schema = "schema/tts_get_voice_profile_response.json");
    }
    pub use tts_get_voice_profile_response::TtsGetVoiceProfileResponse;
    pub mod tts_install_voice_profile_request {
        typify::import_types!(schema = "schema/tts_install_voice_profile_request.json");
    }
    pub use tts_install_voice_profile_request::TtsInstallVoiceProfileRequest;
    pub mod tts_install_voice_profile_response {
        typify::import_types!(schema = "schema/tts_install_voice_profile_response.json");
    }
    pub use tts_install_voice_profile_response::TtsInstallVoiceProfileResponse;
    pub mod tts_list_voice_profiles_request {
        typify::import_types!(schema = "schema/tts_list_voice_profiles_request.json");
    }
    pub use tts_list_voice_profiles_request::TtsListVoiceProfilesRequest;
    pub mod tts_list_voice_profiles_response {
        typify::import_types!(schema = "schema/tts_list_voice_profiles_response.json");
    }
    pub use tts_list_voice_profiles_response::TtsListVoiceProfilesResponse;
    pub mod tts_list_voices_request {
        typify::import_types!(schema = "schema/tts_list_voices_request.json");
    }
    pub use tts_list_voices_request::TtsListVoicesRequest;
    pub mod tts_list_voices_response {
        typify::import_types!(schema = "schema/tts_list_voices_response.json");
    }
    pub use tts_list_voices_response::TtsListVoicesResponse;
    pub mod tts_remove_voice_profile_request {
        typify::import_types!(schema = "schema/tts_remove_voice_profile_request.json");
    }
    pub use tts_remove_voice_profile_request::TtsRemoveVoiceProfileRequest;
    pub mod tts_remove_voice_profile_response {
        typify::import_types!(schema = "schema/tts_remove_voice_profile_response.json");
    }
    pub use tts_remove_voice_profile_response::TtsRemoveVoiceProfileResponse;
    pub mod tts_request {
        typify::import_types!(schema = "schema/tts_request.json");
    }
    pub use tts_request::TtsRequest;
    pub mod tts_set_default_voice_request {
        typify::import_types!(schema = "schema/tts_set_default_voice_request.json");
    }
    pub use tts_set_default_voice_request::TtsSetDefaultVoiceRequest;
    pub mod tts_set_default_voice_response {
        typify::import_types!(schema = "schema/tts_set_default_voice_response.json");
    }
    pub use tts_set_default_voice_response::TtsSetDefaultVoiceResponse;
    pub mod tts_stream_chunk_request {
        typify::import_types!(schema = "schema/tts_stream_chunk_request.json");
    }
    pub use tts_stream_chunk_request::TtsStreamChunkRequest;
    pub mod tts_stream_end_request {
        typify::import_types!(schema = "schema/tts_stream_end_request.json");
    }
    pub use tts_stream_end_request::TtsStreamEndRequest;
    pub mod tts_stream_start_request {
        typify::import_types!(schema = "schema/tts_stream_start_request.json");
    }
    pub use tts_stream_start_request::TtsStreamStartRequest;
    pub mod tts_synthesize_request {
        typify::import_types!(schema = "schema/tts_synthesize_request.json");
    }
    pub use tts_synthesize_request::TtsSynthesizeRequest;
    pub mod tts_synthesize_response {
        typify::import_types!(schema = "schema/tts_synthesize_response.json");
    }
    pub use tts_synthesize_response::TtsSynthesizeResponse;
    pub mod tts_update_voice_profile_request {
        typify::import_types!(schema = "schema/tts_update_voice_profile_request.json");
    }
    pub use tts_update_voice_profile_request::TtsUpdateVoiceProfileRequest;
    pub mod tts_update_voice_profile_response {
        typify::import_types!(schema = "schema/tts_update_voice_profile_response.json");
    }
    pub use tts_update_voice_profile_response::TtsUpdateVoiceProfileResponse;
    pub mod tts_voice_import_abort_request {
        typify::import_types!(schema = "schema/tts_voice_import_abort_request.json");
    }
    pub use tts_voice_import_abort_request::TtsVoiceImportAbortRequest;
    pub mod tts_voice_import_abort_response {
        typify::import_types!(schema = "schema/tts_voice_import_abort_response.json");
    }
    pub use tts_voice_import_abort_response::TtsVoiceImportAbortResponse;
    pub mod tts_voice_import_chunk_request {
        typify::import_types!(schema = "schema/tts_voice_import_chunk_request.json");
    }
    pub use tts_voice_import_chunk_request::TtsVoiceImportChunkRequest;
    pub mod tts_voice_import_chunk_response {
        typify::import_types!(schema = "schema/tts_voice_import_chunk_response.json");
    }
    pub use tts_voice_import_chunk_response::TtsVoiceImportChunkResponse;
    pub mod tts_voice_import_end_request {
        typify::import_types!(schema = "schema/tts_voice_import_end_request.json");
    }
    pub use tts_voice_import_end_request::TtsVoiceImportEndRequest;
    pub mod tts_voice_import_end_response {
        typify::import_types!(schema = "schema/tts_voice_import_end_response.json");
    }
    pub use tts_voice_import_end_response::TtsVoiceImportEndResponse;
    pub mod tts_voice_import_start_request {
        typify::import_types!(schema = "schema/tts_voice_import_start_request.json");
    }
    pub use tts_voice_import_start_request::TtsVoiceImportStartRequest;
    pub mod tts_voice_import_start_response {
        typify::import_types!(schema = "schema/tts_voice_import_start_response.json");
    }
    pub use tts_voice_import_start_response::TtsVoiceImportStartResponse;
    pub mod tooling_execute_tool_request {
        typify::import_types!(schema = "schema/tooling_execute_tool_request.json");
    }
    pub use tooling_execute_tool_request::ToolingExecuteToolRequest;
    pub mod tooling_execute_tool_response {
        typify::import_types!(schema = "schema/tooling_execute_tool_response.json");
    }
    pub use tooling_execute_tool_response::ToolingExecuteToolResponse;
    pub mod tooling_get_export_catalog_request {
        typify::import_types!(schema = "schema/tooling_get_export_catalog_request.json");
    }
    pub use tooling_get_export_catalog_request::ToolingGetExportCatalogRequest;
    pub mod tooling_get_export_catalog_response {
        typify::import_types!(schema = "schema/tooling_get_export_catalog_response.json");
    }
    pub use tooling_get_export_catalog_response::ToolingGetExportCatalogResponse;
    pub mod tooling_get_tools_request {
        typify::import_types!(schema = "schema/tooling_get_tools_request.json");
    }
    pub use tooling_get_tools_request::ToolingGetToolsRequest;
    pub mod tooling_get_tools_response {
        typify::import_types!(schema = "schema/tooling_get_tools_response.json");
    }
    pub use tooling_get_tools_response::ToolingGetToolsResponse;
    pub mod tooling_prepare_execution_request {
        typify::import_types!(schema = "schema/tooling_prepare_execution_request.json");
    }
    pub use tooling_prepare_execution_request::ToolingPrepareExecutionRequest;
    pub mod tooling_prepare_execution_response {
        typify::import_types!(schema = "schema/tooling_prepare_execution_response.json");
    }
    pub use tooling_prepare_execution_response::ToolingPrepareExecutionResponse;
    pub mod transcribe_audio_request {
        typify::import_types!(schema = "schema/transcribe_audio_request.json");
    }
    pub use transcribe_audio_request::TranscribeAudioRequest;
    pub mod transcribe_audio_response {
        typify::import_types!(schema = "schema/transcribe_audio_response.json");
    }
    pub use transcribe_audio_response::TranscribeAudioResponse;
    pub mod wake_word_detect_request {
        typify::import_types!(schema = "schema/wake_word_detect_request.json");
    }
    pub use wake_word_detect_request::WakeWordDetectRequest;
    pub mod wake_word_detect_response {
        typify::import_types!(schema = "schema/wake_word_detect_response.json");
    }
    pub use wake_word_detect_response::WakeWordDetectResponse;
}

pub static SCHEMA_DESCRIPTORS: &[SchemaDescriptor] = &[
    SchemaDescriptor {
        schema_id: "Gateway.ExplainRoute.input.RouteExplainRequest",
        method_id: "Gateway.ExplainRoute",
        direction: "input",
        model_name: "RouteExplainRequest",
        schema_hash: "d05010e28be60b0dd3ae969cef25872b43158512976806b473fe430dbe756561",
        schema_json: include_str!("../schema/route_explain_request.json"),
    },
    SchemaDescriptor {
        schema_id: "Gateway.ExplainRoute.output.RouteExplainResponse",
        method_id: "Gateway.ExplainRoute",
        direction: "output",
        model_name: "RouteExplainResponse",
        schema_hash: "b874d83f14fde33979ffa4db819341c4d4a91f81a4ea8e6fcd465cf2555f4a8e",
        schema_json: include_str!("../schema/route_explain_response.json"),
    },
    SchemaDescriptor {
        schema_id: "STTCoordinator.Listen.input.STTListenRequest",
        method_id: "STTCoordinator.Listen",
        direction: "input",
        model_name: "STTListenRequest",
        schema_hash: "8130cc5cdde9469f9cb249bb59a515c018fe8c33037309f02b74a83f1194a46f",
        schema_json: include_str!("../schema/stt_listen_request.json"),
    },
    SchemaDescriptor {
        schema_id: "STTCoordinator.Listen.output.STTListenResponse",
        method_id: "STTCoordinator.Listen",
        direction: "output",
        model_name: "STTListenResponse",
        schema_hash: "3b629fc8dc429740afab14c2f35a2b31317e94a8f38631ab115f14944f2aaf30",
        schema_json: include_str!("../schema/stt_listen_response.json"),
    },
    SchemaDescriptor {
        schema_id: "STTCoordinator.StopListening.input.STTStopListeningRequest",
        method_id: "STTCoordinator.StopListening",
        direction: "input",
        model_name: "STTStopListeningRequest",
        schema_hash: "297d48be1b7ec76f082f8d3999cb5dfa0f53b28107333fc5b887a470ce30cafd",
        schema_json: include_str!("../schema/stt_stop_listening_request.json"),
    },
    SchemaDescriptor {
        schema_id: "STTCoordinator.StopListening.output.EmptyOutput",
        method_id: "STTCoordinator.StopListening",
        direction: "output",
        model_name: "EmptyOutput",
        schema_hash: "d752bd45e4fd44c7a57678a37407a5fc08f6330355fef98e81c5fa20f89bf06b",
        schema_json: include_str!("../schema/empty_output.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.AudioChunk.event.TTSAudioChunkEvent",
        method_id: "TTS.AudioChunk",
        direction: "event",
        model_name: "TTSAudioChunkEvent",
        schema_hash: "8f2a4c111920f068e5dae7ac8c6ea4dd031f7f50989af157d3c68fa5989760a6",
        schema_json: include_str!("../schema/tts_audio_chunk_event.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.CreateVoiceProfile.input.TTSCreateVoiceProfileRequest",
        method_id: "TTS.CreateVoiceProfile",
        direction: "input",
        model_name: "TTSCreateVoiceProfileRequest",
        schema_hash: "11fc8f0c64f33e9d874885cf8a0b21917fb0f22f37709191b411158d92ee5203",
        schema_json: include_str!("../schema/tts_create_voice_profile_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.CreateVoiceProfile.output.TTSCreateVoiceProfileResponse",
        method_id: "TTS.CreateVoiceProfile",
        direction: "output",
        model_name: "TTSCreateVoiceProfileResponse",
        schema_hash: "2706c7668161681b2dae334e87dbc1ff041e20e9a2af1eeed0e7deb3ceb78584",
        schema_json: include_str!("../schema/tts_create_voice_profile_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.DeleteVoiceProfile.input.TTSDeleteVoiceProfileRequest",
        method_id: "TTS.DeleteVoiceProfile",
        direction: "input",
        model_name: "TTSDeleteVoiceProfileRequest",
        schema_hash: "d4e21efd4b4a31a2fbc8aab099203e766c808dec5c6c5f090a32ec931338688d",
        schema_json: include_str!("../schema/tts_delete_voice_profile_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.DeleteVoiceProfile.output.TTSDeleteVoiceProfileResponse",
        method_id: "TTS.DeleteVoiceProfile",
        direction: "output",
        model_name: "TTSDeleteVoiceProfileResponse",
        schema_hash: "5761b20bf24e294410ea27adc1bbc3254d039ffbc4b4ad8806d0183d83b4f44b",
        schema_json: include_str!("../schema/tts_delete_voice_profile_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.GetCapabilities.input.TTSGetCapabilitiesRequest",
        method_id: "TTS.GetCapabilities",
        direction: "input",
        model_name: "TTSGetCapabilitiesRequest",
        schema_hash: "0adcf095a1796861de001117544967a9201061ce3ec92c2e9a7a2a5e7b29fa95",
        schema_json: include_str!("../schema/tts_get_capabilities_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.GetCapabilities.output.TTSGetCapabilitiesResponse",
        method_id: "TTS.GetCapabilities",
        direction: "output",
        model_name: "TTSGetCapabilitiesResponse",
        schema_hash: "038cb33a1ca8eafea60a326169eb770b91032226281ade8613427e706ed8fb29",
        schema_json: include_str!("../schema/tts_get_capabilities_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.GetVoiceProfile.input.TTSGetVoiceProfileRequest",
        method_id: "TTS.GetVoiceProfile",
        direction: "input",
        model_name: "TTSGetVoiceProfileRequest",
        schema_hash: "a26ddd489476ef2df0813321e35e3c27052a95d9470fd6947f3bc605106aebc7",
        schema_json: include_str!("../schema/tts_get_voice_profile_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.GetVoiceProfile.output.TTSGetVoiceProfileResponse",
        method_id: "TTS.GetVoiceProfile",
        direction: "output",
        model_name: "TTSGetVoiceProfileResponse",
        schema_hash: "fe69d7c7c5ad334b37c2b3e770e60850eaa6b7dde884da63be46a0963e9fdcff",
        schema_json: include_str!("../schema/tts_get_voice_profile_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.InstallVoiceProfile.input.TTSInstallVoiceProfileRequest",
        method_id: "TTS.InstallVoiceProfile",
        direction: "input",
        model_name: "TTSInstallVoiceProfileRequest",
        schema_hash: "42978ca21ac8c27eb54a29d45617e8fe6bddcfa837c3391af6aa4823a0e797a9",
        schema_json: include_str!("../schema/tts_install_voice_profile_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.InstallVoiceProfile.output.TTSInstallVoiceProfileResponse",
        method_id: "TTS.InstallVoiceProfile",
        direction: "output",
        model_name: "TTSInstallVoiceProfileResponse",
        schema_hash: "8fd498e8964ed05bb825d436cec455d78b1e012679e068eef51c6064f53d8448",
        schema_json: include_str!("../schema/tts_install_voice_profile_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.ListVoiceProfiles.input.TTSListVoiceProfilesRequest",
        method_id: "TTS.ListVoiceProfiles",
        direction: "input",
        model_name: "TTSListVoiceProfilesRequest",
        schema_hash: "31045e05ae45e59efe8ee19bdd3f8980e40fb864d89e7627971c00c1058e2c91",
        schema_json: include_str!("../schema/tts_list_voice_profiles_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.ListVoiceProfiles.output.TTSListVoiceProfilesResponse",
        method_id: "TTS.ListVoiceProfiles",
        direction: "output",
        model_name: "TTSListVoiceProfilesResponse",
        schema_hash: "04b672e2dfabb6fb3cfcf578556d62017374ddce0649d11edd6809592b2a0c2f",
        schema_json: include_str!("../schema/tts_list_voice_profiles_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.ListVoices.input.TTSListVoicesRequest",
        method_id: "TTS.ListVoices",
        direction: "input",
        model_name: "TTSListVoicesRequest",
        schema_hash: "52a2cd8c57d91f1c49accf6ee916d477970ccef16c06fc381b7926f01300f9aa",
        schema_json: include_str!("../schema/tts_list_voices_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.ListVoices.output.TTSListVoicesResponse",
        method_id: "TTS.ListVoices",
        direction: "output",
        model_name: "TTSListVoicesResponse",
        schema_hash: "597ea4f7521b0a313ee301a780440a01c6ea3c69ce15835fa9921fa81ebcb437",
        schema_json: include_str!("../schema/tts_list_voices_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.RemoveVoiceProfile.input.TTSRemoveVoiceProfileRequest",
        method_id: "TTS.RemoveVoiceProfile",
        direction: "input",
        model_name: "TTSRemoveVoiceProfileRequest",
        schema_hash: "3813fa711e9fa360947190d7d2928121cd26926492db05401ad31a5be45f5a36",
        schema_json: include_str!("../schema/tts_remove_voice_profile_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.RemoveVoiceProfile.output.TTSRemoveVoiceProfileResponse",
        method_id: "TTS.RemoveVoiceProfile",
        direction: "output",
        model_name: "TTSRemoveVoiceProfileResponse",
        schema_hash: "952c43ac09fbbacf6f7e684a50a5ed5398ac530544c3d0e10fcd144f339cd277",
        schema_json: include_str!("../schema/tts_remove_voice_profile_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.Request.input.TTSRequest",
        method_id: "TTS.Request",
        direction: "input",
        model_name: "TTSRequest",
        schema_hash: "efaf5f938c5119a8569cbd8dfe941543adfb31bff29efcc470430420e1d2c467",
        schema_json: include_str!("../schema/tts_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.Request.output.EmptyOutput",
        method_id: "TTS.Request",
        direction: "output",
        model_name: "EmptyOutput",
        schema_hash: "d752bd45e4fd44c7a57678a37407a5fc08f6330355fef98e81c5fa20f89bf06b",
        schema_json: include_str!("../schema/empty_output.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.SetDefaultVoice.input.TTSSetDefaultVoiceRequest",
        method_id: "TTS.SetDefaultVoice",
        direction: "input",
        model_name: "TTSSetDefaultVoiceRequest",
        schema_hash: "84a64ea71948775d1c1aa4c23f0480a113799c305f5b9dfec6cd6509da292ba0",
        schema_json: include_str!("../schema/tts_set_default_voice_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.SetDefaultVoice.output.TTSSetDefaultVoiceResponse",
        method_id: "TTS.SetDefaultVoice",
        direction: "output",
        model_name: "TTSSetDefaultVoiceResponse",
        schema_hash: "bf2c58f7681e18671af70e4df7377a7608b6e07808c4440ea7f483190b550c5b",
        schema_json: include_str!("../schema/tts_set_default_voice_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.StreamChunk.input.TTSStreamChunkRequest",
        method_id: "TTS.StreamChunk",
        direction: "input",
        model_name: "TTSStreamChunkRequest",
        schema_hash: "0c0d3bc9834efb039133fa4cc21f200ce4eee0b13727e8a39cf63697c899399d",
        schema_json: include_str!("../schema/tts_stream_chunk_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.StreamChunk.output.EmptyOutput",
        method_id: "TTS.StreamChunk",
        direction: "output",
        model_name: "EmptyOutput",
        schema_hash: "d752bd45e4fd44c7a57678a37407a5fc08f6330355fef98e81c5fa20f89bf06b",
        schema_json: include_str!("../schema/empty_output.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.StreamEnd.input.TTSStreamEndRequest",
        method_id: "TTS.StreamEnd",
        direction: "input",
        model_name: "TTSStreamEndRequest",
        schema_hash: "059faba0be794cfba1e8e30ed272273132ba9440fcf014566c097499f8d7fb61",
        schema_json: include_str!("../schema/tts_stream_end_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.StreamEnd.output.EmptyOutput",
        method_id: "TTS.StreamEnd",
        direction: "output",
        model_name: "EmptyOutput",
        schema_hash: "d752bd45e4fd44c7a57678a37407a5fc08f6330355fef98e81c5fa20f89bf06b",
        schema_json: include_str!("../schema/empty_output.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.StreamStart.input.TTSStreamStartRequest",
        method_id: "TTS.StreamStart",
        direction: "input",
        model_name: "TTSStreamStartRequest",
        schema_hash: "b4d6db1532cd3519475101c2b6bf28cb6a6d144eb4b42293680f51a1768f31e6",
        schema_json: include_str!("../schema/tts_stream_start_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.StreamStart.output.EmptyOutput",
        method_id: "TTS.StreamStart",
        direction: "output",
        model_name: "EmptyOutput",
        schema_hash: "d752bd45e4fd44c7a57678a37407a5fc08f6330355fef98e81c5fa20f89bf06b",
        schema_json: include_str!("../schema/empty_output.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.Synthesize.input.TTSSynthesizeRequest",
        method_id: "TTS.Synthesize",
        direction: "input",
        model_name: "TTSSynthesizeRequest",
        schema_hash: "d5408ff48dccb96b3ee7c1c578ce9c27b10f7a33e37fbb97430e2d8222ab8bb6",
        schema_json: include_str!("../schema/tts_synthesize_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.Synthesize.output.TTSSynthesizeResponse",
        method_id: "TTS.Synthesize",
        direction: "output",
        model_name: "TTSSynthesizeResponse",
        schema_hash: "65e6311d9a20d865d39d56b774eedd48af949d792c84f5930a348b6ee223f793",
        schema_json: include_str!("../schema/tts_synthesize_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.UpdateVoiceProfile.input.TTSUpdateVoiceProfileRequest",
        method_id: "TTS.UpdateVoiceProfile",
        direction: "input",
        model_name: "TTSUpdateVoiceProfileRequest",
        schema_hash: "6d6f9506f805c64ab710207e85f8b5173b5733c3f2f24e2797dd6d1d33b9d322",
        schema_json: include_str!("../schema/tts_update_voice_profile_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.UpdateVoiceProfile.output.TTSUpdateVoiceProfileResponse",
        method_id: "TTS.UpdateVoiceProfile",
        direction: "output",
        model_name: "TTSUpdateVoiceProfileResponse",
        schema_hash: "99c191a2d71a227bae0fb07d810c4095d288d851ee7ecd223c3aa35b878ae123",
        schema_json: include_str!("../schema/tts_update_voice_profile_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.VoiceImportAbort.input.TTSVoiceImportAbortRequest",
        method_id: "TTS.VoiceImportAbort",
        direction: "input",
        model_name: "TTSVoiceImportAbortRequest",
        schema_hash: "3928201a9870fb651c3185bdf9d47b07e0f984a49d0eaddad56498928f26fe42",
        schema_json: include_str!("../schema/tts_voice_import_abort_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.VoiceImportAbort.output.TTSVoiceImportAbortResponse",
        method_id: "TTS.VoiceImportAbort",
        direction: "output",
        model_name: "TTSVoiceImportAbortResponse",
        schema_hash: "94423e37f4ea1801b4e2277f843c9a1b141a70cc8e9e334c142f46090d8d232c",
        schema_json: include_str!("../schema/tts_voice_import_abort_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.VoiceImportChunk.input.TTSVoiceImportChunkRequest",
        method_id: "TTS.VoiceImportChunk",
        direction: "input",
        model_name: "TTSVoiceImportChunkRequest",
        schema_hash: "813355b26dfa4064225fc3d9c7e65e7bb79accd6d36a7e2ad4c4f5a8e95d54a2",
        schema_json: include_str!("../schema/tts_voice_import_chunk_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.VoiceImportChunk.output.TTSVoiceImportChunkResponse",
        method_id: "TTS.VoiceImportChunk",
        direction: "output",
        model_name: "TTSVoiceImportChunkResponse",
        schema_hash: "ca95163fbd47ba84e4471f0ea9dffdcc5e151b7666f942d8d4a6a7006dce0f40",
        schema_json: include_str!("../schema/tts_voice_import_chunk_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.VoiceImportEnd.input.TTSVoiceImportEndRequest",
        method_id: "TTS.VoiceImportEnd",
        direction: "input",
        model_name: "TTSVoiceImportEndRequest",
        schema_hash: "bb326382f76c85b75383af4471633293462ae386ecbca8a820b8adb737dcf353",
        schema_json: include_str!("../schema/tts_voice_import_end_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.VoiceImportEnd.output.TTSVoiceImportEndResponse",
        method_id: "TTS.VoiceImportEnd",
        direction: "output",
        model_name: "TTSVoiceImportEndResponse",
        schema_hash: "9e5f37f673a52a5b05716f0d043df4ceb6224911d2710df9d99c8e43de025cad",
        schema_json: include_str!("../schema/tts_voice_import_end_response.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.VoiceImportStart.input.TTSVoiceImportStartRequest",
        method_id: "TTS.VoiceImportStart",
        direction: "input",
        model_name: "TTSVoiceImportStartRequest",
        schema_hash: "b9c72eea8b848e4ff2dc30d93a77f06e6f44994bcbb4ce6a1ab92f1914caeb40",
        schema_json: include_str!("../schema/tts_voice_import_start_request.json"),
    },
    SchemaDescriptor {
        schema_id: "TTS.VoiceImportStart.output.TTSVoiceImportStartResponse",
        method_id: "TTS.VoiceImportStart",
        direction: "output",
        model_name: "TTSVoiceImportStartResponse",
        schema_hash: "7c39813952f7454a85462d14b1e923588e3cb19bb22194f54778776e927a8030",
        schema_json: include_str!("../schema/tts_voice_import_start_response.json"),
    },
    SchemaDescriptor {
        schema_id: "Tooling.ExecuteTool.input.ToolingExecuteToolRequest",
        method_id: "Tooling.ExecuteTool",
        direction: "input",
        model_name: "ToolingExecuteToolRequest",
        schema_hash: "9547a17d13c96218f08f90c83258a985fc6d5aad9aef7aff3a643f784b001132",
        schema_json: include_str!("../schema/tooling_execute_tool_request.json"),
    },
    SchemaDescriptor {
        schema_id: "Tooling.ExecuteTool.output.ToolingExecuteToolResponse",
        method_id: "Tooling.ExecuteTool",
        direction: "output",
        model_name: "ToolingExecuteToolResponse",
        schema_hash: "e248ae6d8dfc0f2e73cd4362d9c4e4f6351fba4373e94f843cf4d7465b5bb9a7",
        schema_json: include_str!("../schema/tooling_execute_tool_response.json"),
    },
    SchemaDescriptor {
        schema_id: "Tooling.GetExportCatalog.input.ToolingGetExportCatalogRequest",
        method_id: "Tooling.GetExportCatalog",
        direction: "input",
        model_name: "ToolingGetExportCatalogRequest",
        schema_hash: "cdeed2488d3f60ba2f6e26409c88256af3b7d5527f3a2a8e104bcf7e722726ba",
        schema_json: include_str!("../schema/tooling_get_export_catalog_request.json"),
    },
    SchemaDescriptor {
        schema_id: "Tooling.GetExportCatalog.output.ToolingGetExportCatalogResponse",
        method_id: "Tooling.GetExportCatalog",
        direction: "output",
        model_name: "ToolingGetExportCatalogResponse",
        schema_hash: "db8352b1f39720c12988729b5da6564175e90fc9dc13a72be38f40b0d94399f8",
        schema_json: include_str!("../schema/tooling_get_export_catalog_response.json"),
    },
    SchemaDescriptor {
        schema_id: "Tooling.GetTools.input.ToolingGetToolsRequest",
        method_id: "Tooling.GetTools",
        direction: "input",
        model_name: "ToolingGetToolsRequest",
        schema_hash: "b40b50bac773b8e49ad345b17fffb816097a6d2e15fd88bbae6fa1bb0e910def",
        schema_json: include_str!("../schema/tooling_get_tools_request.json"),
    },
    SchemaDescriptor {
        schema_id: "Tooling.GetTools.output.ToolingGetToolsResponse",
        method_id: "Tooling.GetTools",
        direction: "output",
        model_name: "ToolingGetToolsResponse",
        schema_hash: "07afe3e44ed858f19b9cfbf8080a4a2f207b087bc4f2b6be7e431a08dd66c76c",
        schema_json: include_str!("../schema/tooling_get_tools_response.json"),
    },
    SchemaDescriptor {
        schema_id: "Tooling.PrepareExecution.input.ToolingPrepareExecutionRequest",
        method_id: "Tooling.PrepareExecution",
        direction: "input",
        model_name: "ToolingPrepareExecutionRequest",
        schema_hash: "f9fc82d8593ec382d85754ffd7bd43eb27c3088ab325676185e428493f6b4083",
        schema_json: include_str!("../schema/tooling_prepare_execution_request.json"),
    },
    SchemaDescriptor {
        schema_id: "Tooling.PrepareExecution.output.ToolingPrepareExecutionResponse",
        method_id: "Tooling.PrepareExecution",
        direction: "output",
        model_name: "ToolingPrepareExecutionResponse",
        schema_hash: "9985c7c5b15f4e0aa59980459a983c7f3c70fbf8e4bbcd1a065aedbdacd9928e",
        schema_json: include_str!("../schema/tooling_prepare_execution_response.json"),
    },
    SchemaDescriptor {
        schema_id: "Transcription.ProcessAudio.input.STTAudioChunk",
        method_id: "Transcription.ProcessAudio",
        direction: "input",
        model_name: "STTAudioChunk",
        schema_hash: "3670479489138802e7d52d4b7d5623c52b363cd4166db2ee7916f6449a10233e",
        schema_json: include_str!("../schema/stt_audio_chunk.json"),
    },
    SchemaDescriptor {
        schema_id: "Transcription.ProcessAudio.output.EmptyOutput",
        method_id: "Transcription.ProcessAudio",
        direction: "output",
        model_name: "EmptyOutput",
        schema_hash: "d752bd45e4fd44c7a57678a37407a5fc08f6330355fef98e81c5fa20f89bf06b",
        schema_json: include_str!("../schema/empty_output.json"),
    },
    SchemaDescriptor {
        schema_id: "Transcription.Transcribe.input.TranscribeAudioRequest",
        method_id: "Transcription.Transcribe",
        direction: "input",
        model_name: "TranscribeAudioRequest",
        schema_hash: "00a0d251f18c3afec3b2593dfe57999a7fdaae76d3b937b3bdec90bbd3a7f56f",
        schema_json: include_str!("../schema/transcribe_audio_request.json"),
    },
    SchemaDescriptor {
        schema_id: "Transcription.Transcribe.output.TranscribeAudioResponse",
        method_id: "Transcription.Transcribe",
        direction: "output",
        model_name: "TranscribeAudioResponse",
        schema_hash: "b7ac3e6f267b25a27363d98499342a6364bdb49530363ed96918d544a92fce5f",
        schema_json: include_str!("../schema/transcribe_audio_response.json"),
    },
    SchemaDescriptor {
        schema_id: "WakeWord.Detect.input.WakeWordDetectRequest",
        method_id: "WakeWord.Detect",
        direction: "input",
        model_name: "WakeWordDetectRequest",
        schema_hash: "6d84e293fe9bf90a30317d78b1e8043cb52d45e13e8fce5ceb84e63185984735",
        schema_json: include_str!("../schema/wake_word_detect_request.json"),
    },
    SchemaDescriptor {
        schema_id: "WakeWord.Detect.output.WakeWordDetectResponse",
        method_id: "WakeWord.Detect",
        direction: "output",
        model_name: "WakeWordDetectResponse",
        schema_hash: "c9675c0beade1d9158903798837dc11ae51429775bf4368ceb4783bdfdb793cf",
        schema_json: include_str!("../schema/wake_word_detect_response.json"),
    },
    SchemaDescriptor {
        schema_id: "WakeWord.ProcessAudio.input.STTAudioChunk",
        method_id: "WakeWord.ProcessAudio",
        direction: "input",
        model_name: "STTAudioChunk",
        schema_hash: "3670479489138802e7d52d4b7d5623c52b363cd4166db2ee7916f6449a10233e",
        schema_json: include_str!("../schema/stt_audio_chunk.json"),
    },
    SchemaDescriptor {
        schema_id: "WakeWord.ProcessAudio.output.EmptyOutput",
        method_id: "WakeWord.ProcessAudio",
        direction: "output",
        model_name: "EmptyOutput",
        schema_hash: "d752bd45e4fd44c7a57678a37407a5fc08f6330355fef98e81c5fa20f89bf06b",
        schema_json: include_str!("../schema/empty_output.json"),
    },
];

pub static METHOD_DESCRIPTORS: &[MethodDescriptor] = &[
    MethodDescriptor {
        method_id: "Tooling.GetTools",
        bus_topic: "Tooling.GetTools",
        module: "Tooling",
        name: "GetTools",
        method_type: "use",
        exposure: "both",
        route_path: "/api/Tooling/GetTools",
        route_kind: "dynamic",
        required_permissions: &["Tooling.GetTools"],
        callable_feature_ids: &["catalog_discovery"],
        input_schema_id: "Tooling.GetTools.input.ToolingGetToolsRequest",
        output_schema_id: "Tooling.GetTools.output.ToolingGetToolsResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "Tooling.GetExportCatalog",
        bus_topic: "Tooling.GetExportCatalog",
        module: "Tooling",
        name: "GetExportCatalog",
        method_type: "use",
        exposure: "both",
        route_path: "/api/Tooling/GetExportCatalog",
        route_kind: "dynamic",
        required_permissions: &["Tooling.GetTools"],
        callable_feature_ids: &["catalog_discovery"],
        input_schema_id: "Tooling.GetExportCatalog.input.ToolingGetExportCatalogRequest",
        output_schema_id: "Tooling.GetExportCatalog.output.ToolingGetExportCatalogResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "Tooling.PrepareExecution",
        bus_topic: "Tooling.PrepareExecution",
        module: "Tooling",
        name: "PrepareExecution",
        method_type: "use",
        exposure: "both",
        route_path: "/api/Tooling/PrepareExecution",
        route_kind: "dynamic",
        required_permissions: &["Tooling.ExecuteTool"],
        callable_feature_ids: &["execution"],
        input_schema_id: "Tooling.PrepareExecution.input.ToolingPrepareExecutionRequest",
        output_schema_id: "Tooling.PrepareExecution.output.ToolingPrepareExecutionResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "Tooling.ExecuteTool",
        bus_topic: "Tooling.ExecuteTool",
        module: "Tooling",
        name: "ExecuteTool",
        method_type: "use",
        exposure: "both",
        route_path: "/api/Tooling/ExecuteTool",
        route_kind: "dynamic",
        required_permissions: &["Tooling.ExecuteTool"],
        callable_feature_ids: &["execution"],
        input_schema_id: "Tooling.ExecuteTool.input.ToolingExecuteToolRequest",
        output_schema_id: "Tooling.ExecuteTool.output.ToolingExecuteToolResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "Gateway.ExplainRoute",
        bus_topic: "Gateway.ExplainRoute",
        module: "Gateway",
        name: "ExplainRoute",
        method_type: "use",
        exposure: "external",
        route_path: "/api/Gateway/ExplainRoute",
        route_kind: "dynamic",
        required_permissions: &["Gateway.use"],
        callable_feature_ids: &[],
        input_schema_id: "Gateway.ExplainRoute.input.RouteExplainRequest",
        output_schema_id: "Gateway.ExplainRoute.output.RouteExplainResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.GetCapabilities",
        bus_topic: "TTS.GetCapabilities",
        module: "TTS",
        name: "GetCapabilities",
        method_type: "use",
        exposure: "both",
        route_path: "/api/TTS/GetCapabilities",
        route_kind: "dynamic",
        required_permissions: &["TTS.use"],
        callable_feature_ids: &["speech_voice_discovery"],
        input_schema_id: "TTS.GetCapabilities.input.TTSGetCapabilitiesRequest",
        output_schema_id: "TTS.GetCapabilities.output.TTSGetCapabilitiesResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.ListVoices",
        bus_topic: "TTS.ListVoices",
        module: "TTS",
        name: "ListVoices",
        method_type: "use",
        exposure: "both",
        route_path: "/api/TTS/ListVoices",
        route_kind: "dynamic",
        required_permissions: &["TTS.use"],
        callable_feature_ids: &["speech_voice_discovery"],
        input_schema_id: "TTS.ListVoices.input.TTSListVoicesRequest",
        output_schema_id: "TTS.ListVoices.output.TTSListVoicesResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.ListVoiceProfiles",
        bus_topic: "TTS.ListVoiceProfiles",
        module: "TTS",
        name: "ListVoiceProfiles",
        method_type: "manage",
        exposure: "both",
        route_path: "/api/TTS/ListVoiceProfiles",
        route_kind: "dynamic",
        required_permissions: &["TTS.manage"],
        callable_feature_ids: &["speech_voice_management"],
        input_schema_id: "TTS.ListVoiceProfiles.input.TTSListVoiceProfilesRequest",
        output_schema_id: "TTS.ListVoiceProfiles.output.TTSListVoiceProfilesResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.GetVoiceProfile",
        bus_topic: "TTS.GetVoiceProfile",
        module: "TTS",
        name: "GetVoiceProfile",
        method_type: "manage",
        exposure: "both",
        route_path: "/api/TTS/GetVoiceProfile",
        route_kind: "dynamic",
        required_permissions: &["TTS.manage"],
        callable_feature_ids: &["speech_voice_management"],
        input_schema_id: "TTS.GetVoiceProfile.input.TTSGetVoiceProfileRequest",
        output_schema_id: "TTS.GetVoiceProfile.output.TTSGetVoiceProfileResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.UpdateVoiceProfile",
        bus_topic: "TTS.UpdateVoiceProfile",
        module: "TTS",
        name: "UpdateVoiceProfile",
        method_type: "manage",
        exposure: "both",
        route_path: "/api/TTS/UpdateVoiceProfile",
        route_kind: "dynamic",
        required_permissions: &["TTS.manage"],
        callable_feature_ids: &["speech_voice_management"],
        input_schema_id: "TTS.UpdateVoiceProfile.input.TTSUpdateVoiceProfileRequest",
        output_schema_id: "TTS.UpdateVoiceProfile.output.TTSUpdateVoiceProfileResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.InstallVoiceProfile",
        bus_topic: "TTS.InstallVoiceProfile",
        module: "TTS",
        name: "InstallVoiceProfile",
        method_type: "manage",
        exposure: "both",
        route_path: "/api/TTS/InstallVoiceProfile",
        route_kind: "dynamic",
        required_permissions: &["TTS.manage"],
        callable_feature_ids: &["speech_voice_management"],
        input_schema_id: "TTS.InstallVoiceProfile.input.TTSInstallVoiceProfileRequest",
        output_schema_id: "TTS.InstallVoiceProfile.output.TTSInstallVoiceProfileResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.RemoveVoiceProfile",
        bus_topic: "TTS.RemoveVoiceProfile",
        module: "TTS",
        name: "RemoveVoiceProfile",
        method_type: "manage",
        exposure: "both",
        route_path: "/api/TTS/RemoveVoiceProfile",
        route_kind: "dynamic",
        required_permissions: &["TTS.manage"],
        callable_feature_ids: &["speech_voice_management"],
        input_schema_id: "TTS.RemoveVoiceProfile.input.TTSRemoveVoiceProfileRequest",
        output_schema_id: "TTS.RemoveVoiceProfile.output.TTSRemoveVoiceProfileResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.SetDefaultVoice",
        bus_topic: "TTS.SetDefaultVoice",
        module: "TTS",
        name: "SetDefaultVoice",
        method_type: "manage",
        exposure: "both",
        route_path: "/api/TTS/SetDefaultVoice",
        route_kind: "dynamic",
        required_permissions: &["TTS.manage"],
        callable_feature_ids: &["speech_voice_management"],
        input_schema_id: "TTS.SetDefaultVoice.input.TTSSetDefaultVoiceRequest",
        output_schema_id: "TTS.SetDefaultVoice.output.TTSSetDefaultVoiceResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.VoiceImportStart",
        bus_topic: "TTS.VoiceImportStart",
        module: "TTS",
        name: "VoiceImportStart",
        method_type: "manage",
        exposure: "both",
        route_path: "/api/TTS/VoiceImportStart",
        route_kind: "dynamic",
        required_permissions: &["TTS.manage"],
        callable_feature_ids: &["speech_voice_management"],
        input_schema_id: "TTS.VoiceImportStart.input.TTSVoiceImportStartRequest",
        output_schema_id: "TTS.VoiceImportStart.output.TTSVoiceImportStartResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.VoiceImportChunk",
        bus_topic: "TTS.VoiceImportChunk",
        module: "TTS",
        name: "VoiceImportChunk",
        method_type: "manage",
        exposure: "both",
        route_path: "/api/TTS/VoiceImportChunk",
        route_kind: "dynamic",
        required_permissions: &["TTS.manage"],
        callable_feature_ids: &["speech_voice_management"],
        input_schema_id: "TTS.VoiceImportChunk.input.TTSVoiceImportChunkRequest",
        output_schema_id: "TTS.VoiceImportChunk.output.TTSVoiceImportChunkResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.VoiceImportEnd",
        bus_topic: "TTS.VoiceImportEnd",
        module: "TTS",
        name: "VoiceImportEnd",
        method_type: "manage",
        exposure: "both",
        route_path: "/api/TTS/VoiceImportEnd",
        route_kind: "dynamic",
        required_permissions: &["TTS.manage"],
        callable_feature_ids: &["speech_voice_management"],
        input_schema_id: "TTS.VoiceImportEnd.input.TTSVoiceImportEndRequest",
        output_schema_id: "TTS.VoiceImportEnd.output.TTSVoiceImportEndResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.VoiceImportAbort",
        bus_topic: "TTS.VoiceImportAbort",
        module: "TTS",
        name: "VoiceImportAbort",
        method_type: "manage",
        exposure: "both",
        route_path: "/api/TTS/VoiceImportAbort",
        route_kind: "dynamic",
        required_permissions: &["TTS.manage"],
        callable_feature_ids: &["speech_voice_management"],
        input_schema_id: "TTS.VoiceImportAbort.input.TTSVoiceImportAbortRequest",
        output_schema_id: "TTS.VoiceImportAbort.output.TTSVoiceImportAbortResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.CreateVoiceProfile",
        bus_topic: "TTS.CreateVoiceProfile",
        module: "TTS",
        name: "CreateVoiceProfile",
        method_type: "manage",
        exposure: "both",
        route_path: "/api/TTS/CreateVoiceProfile",
        route_kind: "dynamic",
        required_permissions: &["TTS.manage"],
        callable_feature_ids: &["speech_voice_management"],
        input_schema_id: "TTS.CreateVoiceProfile.input.TTSCreateVoiceProfileRequest",
        output_schema_id: "TTS.CreateVoiceProfile.output.TTSCreateVoiceProfileResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.DeleteVoiceProfile",
        bus_topic: "TTS.DeleteVoiceProfile",
        module: "TTS",
        name: "DeleteVoiceProfile",
        method_type: "manage",
        exposure: "both",
        route_path: "/api/TTS/DeleteVoiceProfile",
        route_kind: "dynamic",
        required_permissions: &["TTS.manage"],
        callable_feature_ids: &["speech_voice_management"],
        input_schema_id: "TTS.DeleteVoiceProfile.input.TTSDeleteVoiceProfileRequest",
        output_schema_id: "TTS.DeleteVoiceProfile.output.TTSDeleteVoiceProfileResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.Request",
        bus_topic: "TTS.Request",
        module: "TTS",
        name: "Request",
        method_type: "use",
        exposure: "both",
        route_path: "/api/TTS/Request",
        route_kind: "dynamic",
        required_permissions: &["TTS.Request"],
        callable_feature_ids: &["speech_playback"],
        input_schema_id: "TTS.Request.input.TTSRequest",
        output_schema_id: "TTS.Request.output.EmptyOutput",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "TTS.StreamStart",
        bus_topic: "TTS.StreamStart",
        module: "TTS",
        name: "StreamStart",
        method_type: "use",
        exposure: "both",
        route_path: "/api/TTS/StreamStart",
        route_kind: "dynamic",
        required_permissions: &["TTS.StreamStart"],
        callable_feature_ids: &["speech_streaming"],
        input_schema_id: "TTS.StreamStart.input.TTSStreamStartRequest",
        output_schema_id: "TTS.StreamStart.output.EmptyOutput",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: Some("tts_text_stream"),
            event_topic: Some("TTS.AudioChunk"),
        },
    },
    MethodDescriptor {
        method_id: "TTS.StreamChunk",
        bus_topic: "TTS.StreamChunk",
        module: "TTS",
        name: "StreamChunk",
        method_type: "use",
        exposure: "both",
        route_path: "/api/TTS/StreamChunk",
        route_kind: "dynamic",
        required_permissions: &["TTS.StreamChunk"],
        callable_feature_ids: &["speech_streaming"],
        input_schema_id: "TTS.StreamChunk.input.TTSStreamChunkRequest",
        output_schema_id: "TTS.StreamChunk.output.EmptyOutput",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: Some("tts_text_stream"),
            event_topic: Some("TTS.AudioChunk"),
        },
    },
    MethodDescriptor {
        method_id: "TTS.StreamEnd",
        bus_topic: "TTS.StreamEnd",
        module: "TTS",
        name: "StreamEnd",
        method_type: "use",
        exposure: "both",
        route_path: "/api/TTS/StreamEnd",
        route_kind: "dynamic",
        required_permissions: &["TTS.StreamEnd"],
        callable_feature_ids: &["speech_streaming"],
        input_schema_id: "TTS.StreamEnd.input.TTSStreamEndRequest",
        output_schema_id: "TTS.StreamEnd.output.EmptyOutput",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: Some("tts_text_stream"),
            event_topic: Some("TTS.AudioChunk"),
        },
    },
    MethodDescriptor {
        method_id: "TTS.Synthesize",
        bus_topic: "TTS.Synthesize",
        module: "TTS",
        name: "Synthesize",
        method_type: "use",
        exposure: "both",
        route_path: "/api/TTS/Synthesize",
        route_kind: "dynamic",
        required_permissions: &["TTS.Synthesize"],
        callable_feature_ids: &["speech_synthesis"],
        input_schema_id: "TTS.Synthesize.input.TTSSynthesizeRequest",
        output_schema_id: "TTS.Synthesize.output.TTSSynthesizeResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "STTCoordinator.Listen",
        bus_topic: "STTCoordinator.Listen",
        module: "STTCoordinator",
        name: "Listen",
        method_type: "use",
        exposure: "both",
        route_path: "/api/STTCoordinator/Listen",
        route_kind: "dynamic",
        required_permissions: &["STTCoordinator.use"],
        callable_feature_ids: &["listening_session_control"],
        input_schema_id: "STTCoordinator.Listen.input.STTListenRequest",
        output_schema_id: "STTCoordinator.Listen.output.STTListenResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "STTCoordinator.StopListening",
        bus_topic: "STTCoordinator.StopListening",
        module: "STTCoordinator",
        name: "StopListening",
        method_type: "use",
        exposure: "both",
        route_path: "/api/STTCoordinator/StopListening",
        route_kind: "dynamic",
        required_permissions: &["STTCoordinator.use"],
        callable_feature_ids: &["listening_session_control"],
        input_schema_id: "STTCoordinator.StopListening.input.STTStopListeningRequest",
        output_schema_id: "STTCoordinator.StopListening.output.EmptyOutput",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "WakeWord.ProcessAudio",
        bus_topic: "WakeWord.ProcessAudio",
        module: "WakeWord",
        name: "ProcessAudio",
        method_type: "use",
        exposure: "both",
        route_path: "/api/WakeWord/ProcessAudio",
        route_kind: "dynamic",
        required_permissions: &["WakeWord.ProcessAudio"],
        callable_feature_ids: &["wake_word_detection"],
        input_schema_id: "WakeWord.ProcessAudio.input.STTAudioChunk",
        output_schema_id: "WakeWord.ProcessAudio.output.EmptyOutput",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "WakeWord.Detect",
        bus_topic: "WakeWord.Detect",
        module: "WakeWord",
        name: "Detect",
        method_type: "use",
        exposure: "both",
        route_path: "/api/WakeWord/Detect",
        route_kind: "dynamic",
        required_permissions: &["WakeWord.Detect"],
        callable_feature_ids: &["wake_word_detection"],
        input_schema_id: "WakeWord.Detect.input.WakeWordDetectRequest",
        output_schema_id: "WakeWord.Detect.output.WakeWordDetectResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "Transcription.ProcessAudio",
        bus_topic: "Transcription.ProcessAudio",
        module: "Transcription",
        name: "ProcessAudio",
        method_type: "use",
        exposure: "both",
        route_path: "/api/Transcription/ProcessAudio",
        route_kind: "dynamic",
        required_permissions: &["Transcription.ProcessAudio"],
        callable_feature_ids: &["audio_transcription"],
        input_schema_id: "Transcription.ProcessAudio.input.STTAudioChunk",
        output_schema_id: "Transcription.ProcessAudio.output.EmptyOutput",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
    MethodDescriptor {
        method_id: "Transcription.Transcribe",
        bus_topic: "Transcription.Transcribe",
        module: "Transcription",
        name: "Transcribe",
        method_type: "use",
        exposure: "both",
        route_path: "/api/Transcription/Transcribe",
        route_kind: "dynamic",
        required_permissions: &["Transcription.Transcribe"],
        callable_feature_ids: &["audio_transcription"],
        input_schema_id: "Transcription.Transcribe.input.TranscribeAudioRequest",
        output_schema_id: "Transcription.Transcribe.output.TranscribeAudioResponse",
        streaming: StreamingDescriptor {
            rpc_kind: "unary",
            request_stream: false,
            response_stream: false,
            ordered_command_group: None,
            event_topic: None,
        },
    },
];

pub static EVENT_DESCRIPTORS: &[EventDescriptor] = &[EventDescriptor {
    event_topic: "TTS.AudioChunk",
    module: "TTS",
    name: "AudioChunk",
    schema_id: "TTS.AudioChunk.event.TTSAudioChunkEvent",
    schema_hash: "8f2a4c111920f068e5dae7ac8c6ea4dd031f7f50989af157d3c68fa5989760a6",
    required_permissions: &["TTS.use"],
    bounded: true,
    authorized: true,
    ordered_event_group: Some("tts_text_stream"),
    remote_raw_audio_route: false,
}];

pub fn schema_by_id(schema_id: &str) -> Option<&'static SchemaDescriptor> {
    SCHEMA_DESCRIPTORS
        .iter()
        .find(|item| item.schema_id == schema_id)
}

pub fn method_by_id(method_id: &str) -> Option<&'static MethodDescriptor> {
    METHOD_DESCRIPTORS
        .iter()
        .find(|item| item.method_id == method_id)
}

pub fn event_by_topic(topic: &str) -> Option<&'static EventDescriptor> {
    EVENT_DESCRIPTORS
        .iter()
        .find(|item| item.event_topic == topic)
}

pub fn normalize_generated_contract(
    schema_id: &str,
    value: serde_json::Value,
) -> Result<serde_json::Value, ContractParseError> {
    let (normalized, compiled) = normalize_contract_value(schema_id, value)?;
    validate_normalized_contract_schema(schema_id, compiled, &normalized)?;
    match schema_id {
        "Gateway.ExplainRoute.input.RouteExplainRequest" => {
            serde_json::from_value::<models::route_explain_request::RouteExplainRequest>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        "Gateway.ExplainRoute.output.RouteExplainResponse" => serde_json::from_value::<
            models::route_explain_response::RouteExplainResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "STTCoordinator.Listen.input.STTListenRequest" => {
            serde_json::from_value::<models::stt_listen_request::SttListenRequest>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        "STTCoordinator.Listen.output.STTListenResponse" => {
            serde_json::from_value::<models::stt_listen_response::SttListenResponse>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        "STTCoordinator.StopListening.input.STTStopListeningRequest" => serde_json::from_value::<
            models::stt_stop_listening_request::SttStopListeningRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "STTCoordinator.StopListening.output.EmptyOutput" => {
            serde_json::from_value::<models::empty_output::EmptyOutput>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        "TTS.AudioChunk.event.TTSAudioChunkEvent" => {
            serde_json::from_value::<models::tts_audio_chunk_event::TtsAudioChunkEvent>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        "TTS.CreateVoiceProfile.input.TTSCreateVoiceProfileRequest" => serde_json::from_value::<
            models::tts_create_voice_profile_request::TtsCreateVoiceProfileRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.CreateVoiceProfile.output.TTSCreateVoiceProfileResponse" => serde_json::from_value::<
            models::tts_create_voice_profile_response::TtsCreateVoiceProfileResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.DeleteVoiceProfile.input.TTSDeleteVoiceProfileRequest" => serde_json::from_value::<
            models::tts_delete_voice_profile_request::TtsDeleteVoiceProfileRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.DeleteVoiceProfile.output.TTSDeleteVoiceProfileResponse" => serde_json::from_value::<
            models::tts_delete_voice_profile_response::TtsDeleteVoiceProfileResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.GetCapabilities.input.TTSGetCapabilitiesRequest" => serde_json::from_value::<
            models::tts_get_capabilities_request::TtsGetCapabilitiesRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.GetCapabilities.output.TTSGetCapabilitiesResponse" => serde_json::from_value::<
            models::tts_get_capabilities_response::TtsGetCapabilitiesResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.GetVoiceProfile.input.TTSGetVoiceProfileRequest" => serde_json::from_value::<
            models::tts_get_voice_profile_request::TtsGetVoiceProfileRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.GetVoiceProfile.output.TTSGetVoiceProfileResponse" => serde_json::from_value::<
            models::tts_get_voice_profile_response::TtsGetVoiceProfileResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.InstallVoiceProfile.input.TTSInstallVoiceProfileRequest" => serde_json::from_value::<
            models::tts_install_voice_profile_request::TtsInstallVoiceProfileRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.InstallVoiceProfile.output.TTSInstallVoiceProfileResponse" => {
            serde_json::from_value::<
                models::tts_install_voice_profile_response::TtsInstallVoiceProfileResponse,
            >(normalized)
            .and_then(serde_json::to_value)
            .map_err(|_| ContractParseError::Decode {
                schema_id: schema_id.to_owned(),
            })
        }
        "TTS.ListVoiceProfiles.input.TTSListVoiceProfilesRequest" => serde_json::from_value::<
            models::tts_list_voice_profiles_request::TtsListVoiceProfilesRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.ListVoiceProfiles.output.TTSListVoiceProfilesResponse" => serde_json::from_value::<
            models::tts_list_voice_profiles_response::TtsListVoiceProfilesResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.ListVoices.input.TTSListVoicesRequest" => serde_json::from_value::<
            models::tts_list_voices_request::TtsListVoicesRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.ListVoices.output.TTSListVoicesResponse" => serde_json::from_value::<
            models::tts_list_voices_response::TtsListVoicesResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.RemoveVoiceProfile.input.TTSRemoveVoiceProfileRequest" => serde_json::from_value::<
            models::tts_remove_voice_profile_request::TtsRemoveVoiceProfileRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.RemoveVoiceProfile.output.TTSRemoveVoiceProfileResponse" => serde_json::from_value::<
            models::tts_remove_voice_profile_response::TtsRemoveVoiceProfileResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.Request.input.TTSRequest" => {
            serde_json::from_value::<models::tts_request::TtsRequest>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        "TTS.Request.output.EmptyOutput" => {
            serde_json::from_value::<models::empty_output::EmptyOutput>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        "TTS.SetDefaultVoice.input.TTSSetDefaultVoiceRequest" => serde_json::from_value::<
            models::tts_set_default_voice_request::TtsSetDefaultVoiceRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.SetDefaultVoice.output.TTSSetDefaultVoiceResponse" => serde_json::from_value::<
            models::tts_set_default_voice_response::TtsSetDefaultVoiceResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.StreamChunk.input.TTSStreamChunkRequest" => serde_json::from_value::<
            models::tts_stream_chunk_request::TtsStreamChunkRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.StreamChunk.output.EmptyOutput" => {
            serde_json::from_value::<models::empty_output::EmptyOutput>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        "TTS.StreamEnd.input.TTSStreamEndRequest" => serde_json::from_value::<
            models::tts_stream_end_request::TtsStreamEndRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.StreamEnd.output.EmptyOutput" => {
            serde_json::from_value::<models::empty_output::EmptyOutput>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        "TTS.StreamStart.input.TTSStreamStartRequest" => serde_json::from_value::<
            models::tts_stream_start_request::TtsStreamStartRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.StreamStart.output.EmptyOutput" => {
            serde_json::from_value::<models::empty_output::EmptyOutput>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        "TTS.Synthesize.input.TTSSynthesizeRequest" => serde_json::from_value::<
            models::tts_synthesize_request::TtsSynthesizeRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.Synthesize.output.TTSSynthesizeResponse" => serde_json::from_value::<
            models::tts_synthesize_response::TtsSynthesizeResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.UpdateVoiceProfile.input.TTSUpdateVoiceProfileRequest" => serde_json::from_value::<
            models::tts_update_voice_profile_request::TtsUpdateVoiceProfileRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.UpdateVoiceProfile.output.TTSUpdateVoiceProfileResponse" => serde_json::from_value::<
            models::tts_update_voice_profile_response::TtsUpdateVoiceProfileResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.VoiceImportAbort.input.TTSVoiceImportAbortRequest" => serde_json::from_value::<
            models::tts_voice_import_abort_request::TtsVoiceImportAbortRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.VoiceImportAbort.output.TTSVoiceImportAbortResponse" => serde_json::from_value::<
            models::tts_voice_import_abort_response::TtsVoiceImportAbortResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.VoiceImportChunk.input.TTSVoiceImportChunkRequest" => serde_json::from_value::<
            models::tts_voice_import_chunk_request::TtsVoiceImportChunkRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.VoiceImportChunk.output.TTSVoiceImportChunkResponse" => serde_json::from_value::<
            models::tts_voice_import_chunk_response::TtsVoiceImportChunkResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.VoiceImportEnd.input.TTSVoiceImportEndRequest" => serde_json::from_value::<
            models::tts_voice_import_end_request::TtsVoiceImportEndRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.VoiceImportEnd.output.TTSVoiceImportEndResponse" => serde_json::from_value::<
            models::tts_voice_import_end_response::TtsVoiceImportEndResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.VoiceImportStart.input.TTSVoiceImportStartRequest" => serde_json::from_value::<
            models::tts_voice_import_start_request::TtsVoiceImportStartRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "TTS.VoiceImportStart.output.TTSVoiceImportStartResponse" => serde_json::from_value::<
            models::tts_voice_import_start_response::TtsVoiceImportStartResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "Tooling.ExecuteTool.input.ToolingExecuteToolRequest" => serde_json::from_value::<
            models::tooling_execute_tool_request::ToolingExecuteToolRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "Tooling.ExecuteTool.output.ToolingExecuteToolResponse" => serde_json::from_value::<
            models::tooling_execute_tool_response::ToolingExecuteToolResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "Tooling.GetExportCatalog.input.ToolingGetExportCatalogRequest" => {
            serde_json::from_value::<
                models::tooling_get_export_catalog_request::ToolingGetExportCatalogRequest,
            >(normalized)
            .and_then(serde_json::to_value)
            .map_err(|_| ContractParseError::Decode {
                schema_id: schema_id.to_owned(),
            })
        }
        "Tooling.GetExportCatalog.output.ToolingGetExportCatalogResponse" => {
            serde_json::from_value::<
                models::tooling_get_export_catalog_response::ToolingGetExportCatalogResponse,
            >(normalized)
            .and_then(serde_json::to_value)
            .map_err(|_| ContractParseError::Decode {
                schema_id: schema_id.to_owned(),
            })
        }
        "Tooling.GetTools.input.ToolingGetToolsRequest" => serde_json::from_value::<
            models::tooling_get_tools_request::ToolingGetToolsRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "Tooling.GetTools.output.ToolingGetToolsResponse" => serde_json::from_value::<
            models::tooling_get_tools_response::ToolingGetToolsResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "Tooling.PrepareExecution.input.ToolingPrepareExecutionRequest" => {
            serde_json::from_value::<
                models::tooling_prepare_execution_request::ToolingPrepareExecutionRequest,
            >(normalized)
            .and_then(serde_json::to_value)
            .map_err(|_| ContractParseError::Decode {
                schema_id: schema_id.to_owned(),
            })
        }
        "Tooling.PrepareExecution.output.ToolingPrepareExecutionResponse" => {
            serde_json::from_value::<
                models::tooling_prepare_execution_response::ToolingPrepareExecutionResponse,
            >(normalized)
            .and_then(serde_json::to_value)
            .map_err(|_| ContractParseError::Decode {
                schema_id: schema_id.to_owned(),
            })
        }
        "Transcription.ProcessAudio.input.STTAudioChunk" => {
            serde_json::from_value::<models::stt_audio_chunk::SttAudioChunk>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        "Transcription.ProcessAudio.output.EmptyOutput" => {
            serde_json::from_value::<models::empty_output::EmptyOutput>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        "Transcription.Transcribe.input.TranscribeAudioRequest" => serde_json::from_value::<
            models::transcribe_audio_request::TranscribeAudioRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "Transcription.Transcribe.output.TranscribeAudioResponse" => serde_json::from_value::<
            models::transcribe_audio_response::TranscribeAudioResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "WakeWord.Detect.input.WakeWordDetectRequest" => serde_json::from_value::<
            models::wake_word_detect_request::WakeWordDetectRequest,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "WakeWord.Detect.output.WakeWordDetectResponse" => serde_json::from_value::<
            models::wake_word_detect_response::WakeWordDetectResponse,
        >(normalized)
        .and_then(serde_json::to_value)
        .map_err(|_| ContractParseError::Decode {
            schema_id: schema_id.to_owned(),
        }),
        "WakeWord.ProcessAudio.input.STTAudioChunk" => {
            serde_json::from_value::<models::stt_audio_chunk::SttAudioChunk>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        "WakeWord.ProcessAudio.output.EmptyOutput" => {
            serde_json::from_value::<models::empty_output::EmptyOutput>(normalized)
                .and_then(serde_json::to_value)
                .map_err(|_| ContractParseError::Decode {
                    schema_id: schema_id.to_owned(),
                })
        }
        _ => Err(ContractParseError::UnknownSchema(schema_id.to_owned())),
    }
}

pub fn validate_generated_contract(
    schema_id: &str,
    value: serde_json::Value,
) -> Result<(), ContractParseError> {
    normalize_generated_contract(schema_id, value).map(|_| ())
}
