"""Tests for Enhancement A — Auto-generate room ID and password.

Requires optional WebRTC stack (``aiortc``); skipped in minimal installs.
"""

from unittest.mock import AsyncMock, MagicMock, patch

import pytest

pytest.importorskip("aiortc", reason="Gateway WebRTC tests require aiortc")

# Patched where ``ConfigAPI`` is defined (imported inside ``_start_webrtc``).
_PATCH_CONFIG_API = "app.shared.config.interface.ConfigAPI"
_PATCH_RTC = "app.services.gateway.webrtc.rtc_client.RTCClient"
_PATCH_SET_RTC = "app.services.gateway.dependencies.set_rtc_client"


@pytest.fixture
def mock_gateway_service():
    """Create a GatewayService with mocked dependencies."""
    from app.services.gateway.service import GatewayService

    service = GatewayService()
    service._bus = MagicMock()
    service._registry_aggregator = AsyncMock()
    return service


def _mock_config_api(saved_values: dict):
    mock_api = MagicMock()

    async def capture_update(key, value, *, timeout=15.0):
        saved_values[key] = value
        return True

    mock_api.aupdate_config = AsyncMock(side_effect=capture_update)
    return mock_api


@pytest.mark.asyncio
async def test_room_autogenerated_on_default(mock_gateway_service):
    """With room='default', start WebRTC auto-generates a new room name."""
    service = mock_gateway_service

    settings = MagicMock()
    settings.webrtc.enabled = True
    settings.webrtc.room = "default"
    settings.webrtc.password = "existing-password"
    settings.api.auth_enabled = False
    settings.permissions.webrtc_pairing_timeout_seconds = 300.0

    saved_values = {}
    mock_api = _mock_config_api(saved_values)

    with (
        patch.object(service, "_get_gateway_config", return_value=settings),
        patch(_PATCH_CONFIG_API, return_value=mock_api),
        patch(_PATCH_RTC) as mock_rtc_cls,
        patch(_PATCH_SET_RTC),
    ):
        mock_rtc = AsyncMock()
        mock_rtc_cls.return_value = mock_rtc

        await service._start_webrtc()

    assert "services.gateway.webrtc.room" in saved_values
    assert saved_values["services.gateway.webrtc.room"].startswith("aurora-")
    assert len(saved_values["services.gateway.webrtc.room"]) > len("aurora-")


@pytest.mark.asyncio
async def test_password_autogenerated_on_empty(mock_gateway_service):
    """With password='', start WebRTC auto-generates a new password."""
    service = mock_gateway_service

    settings = MagicMock()
    settings.webrtc.enabled = True
    settings.webrtc.room = "my-room"
    settings.webrtc.password = ""
    settings.api.auth_enabled = False
    settings.permissions.webrtc_pairing_timeout_seconds = 300.0

    saved_values = {}
    mock_api = _mock_config_api(saved_values)

    with (
        patch.object(service, "_get_gateway_config", return_value=settings),
        patch(_PATCH_CONFIG_API, return_value=mock_api),
        patch(_PATCH_RTC) as mock_rtc_cls,
        patch(_PATCH_SET_RTC),
    ):
        mock_rtc = AsyncMock()
        mock_rtc_cls.return_value = mock_rtc

        await service._start_webrtc()

    assert "services.gateway.webrtc.password" in saved_values
    assert len(saved_values["services.gateway.webrtc.password"]) > 0


@pytest.mark.asyncio
async def test_existing_room_not_overwritten(mock_gateway_service):
    """With room='my-custom-room', start WebRTC preserves the room name."""
    service = mock_gateway_service

    settings = MagicMock()
    settings.webrtc.enabled = True
    settings.webrtc.room = "my-custom-room"
    settings.webrtc.password = "my-secret"
    settings.api.auth_enabled = False
    settings.permissions.webrtc_pairing_timeout_seconds = 300.0

    saved_values = {}
    mock_api = _mock_config_api(saved_values)

    with (
        patch.object(service, "_get_gateway_config", return_value=settings),
        patch(_PATCH_CONFIG_API, return_value=mock_api),
        patch(_PATCH_RTC) as mock_rtc_cls,
        patch(_PATCH_SET_RTC),
    ):
        mock_rtc = AsyncMock()
        mock_rtc_cls.return_value = mock_rtc

        await service._start_webrtc()

    assert "services.gateway.webrtc.room" not in saved_values
    assert "services.gateway.webrtc.password" not in saved_values


@pytest.mark.asyncio
async def test_existing_password_not_overwritten(mock_gateway_service):
    """With password='my-secret', start WebRTC preserves the password."""
    service = mock_gateway_service

    settings = MagicMock()
    settings.webrtc.enabled = True
    settings.webrtc.room = "default"
    settings.webrtc.password = "my-secret"
    settings.api.auth_enabled = False
    settings.permissions.webrtc_pairing_timeout_seconds = 300.0

    saved_values = {}
    mock_api = _mock_config_api(saved_values)

    with (
        patch.object(service, "_get_gateway_config", return_value=settings),
        patch(_PATCH_CONFIG_API, return_value=mock_api),
        patch(_PATCH_RTC) as mock_rtc_cls,
        patch(_PATCH_SET_RTC),
    ):
        mock_rtc = AsyncMock()
        mock_rtc_cls.return_value = mock_rtc

        await service._start_webrtc()

    assert "services.gateway.webrtc.room" in saved_values
    assert "services.gateway.webrtc.password" not in saved_values
