"""Tests for Enhancement A — Auto-generate room ID and password."""

from unittest.mock import AsyncMock, MagicMock, patch

import pytest

_PATCH_CFGMGR = "app.services.config.config_manager.ConfigManager"
_PATCH_RTC = "app.services.gateway.webrtc.rtc_client.RTCClient"
_PATCH_SET_RTC = "app.services.gateway.dependencies.set_rtc_client"


@pytest.fixture
def mock_gateway_service():
    """Create a GatewayService with mocked dependencies."""
    from app.services.gateway.service import GatewayService

    service = GatewayService()
    service._bus = MagicMock()
    service._registry_aggregator = AsyncMock()
    return service


@pytest.mark.asyncio
async def test_room_autogenerated_on_default(mock_gateway_service):
    """With room='default', start WebRTC auto-generates a new room name."""
    service = mock_gateway_service

    settings = MagicMock()
    settings.webrtc.enabled = True
    settings.webrtc.room = "default"
    settings.webrtc.password = "existing-password"
    settings.api.auth_enabled = False
    settings.permissions.webrtc_pairing_timeout_seconds = 300.0

    mock_config_mgr = MagicMock()
    saved_values = {}

    def mock_set(key, value, save=True):
        saved_values[key] = value

    mock_config_mgr.set = mock_set

    with (
        patch.object(service, "_get_gateway_config", return_value=settings),
        patch(_PATCH_CFGMGR, return_value=mock_config_mgr),
        patch(_PATCH_RTC) as mock_rtc_cls,
        patch(_PATCH_SET_RTC),
    ):
        mock_rtc = AsyncMock()
        mock_rtc_cls.return_value = mock_rtc

        await service._start_webrtc()

    assert "gateway.webrtc.room" in saved_values
    assert saved_values["gateway.webrtc.room"].startswith("aurora-")
    assert len(saved_values["gateway.webrtc.room"]) > len("aurora-")


@pytest.mark.asyncio
async def test_password_autogenerated_on_empty(mock_gateway_service):
    """With password='', start WebRTC auto-generates a new password."""
    service = mock_gateway_service

    settings = MagicMock()
    settings.webrtc.enabled = True
    settings.webrtc.room = "my-room"
    settings.webrtc.password = ""
    settings.api.auth_enabled = False
    settings.permissions.webrtc_pairing_timeout_seconds = 300.0

    mock_config_mgr = MagicMock()
    saved_values = {}

    def mock_set(key, value, save=True):
        saved_values[key] = value

    mock_config_mgr.set = mock_set

    with (
        patch.object(service, "_get_gateway_config", return_value=settings),
        patch(_PATCH_CFGMGR, return_value=mock_config_mgr),
        patch(_PATCH_RTC) as mock_rtc_cls,
        patch(_PATCH_SET_RTC),
    ):
        mock_rtc = AsyncMock()
        mock_rtc_cls.return_value = mock_rtc

        await service._start_webrtc()

    assert "gateway.webrtc.password" in saved_values
    assert len(saved_values["gateway.webrtc.password"]) > 0


@pytest.mark.asyncio
async def test_existing_room_not_overwritten(mock_gateway_service):
    """With room='my-custom-room', start WebRTC preserves the room name."""
    service = mock_gateway_service

    settings = MagicMock()
    settings.webrtc.enabled = True
    settings.webrtc.room = "my-custom-room"
    settings.webrtc.password = "my-secret"
    settings.api.auth_enabled = False
    settings.permissions.webrtc_pairing_timeout_seconds = 300.0

    mock_config_mgr = MagicMock()
    saved_values = {}

    def mock_set(key, value, save=True):
        saved_values[key] = value

    mock_config_mgr.set = mock_set

    with (
        patch.object(service, "_get_gateway_config", return_value=settings),
        patch(_PATCH_CFGMGR, return_value=mock_config_mgr),
        patch(_PATCH_RTC) as mock_rtc_cls,
        patch(_PATCH_SET_RTC),
    ):
        mock_rtc = AsyncMock()
        mock_rtc_cls.return_value = mock_rtc

        await service._start_webrtc()

    # Room and password should NOT have been overwritten
    assert "gateway.webrtc.room" not in saved_values
    assert "gateway.webrtc.password" not in saved_values


@pytest.mark.asyncio
async def test_existing_password_not_overwritten(mock_gateway_service):
    """With password='my-secret', start WebRTC preserves the password."""
    service = mock_gateway_service

    settings = MagicMock()
    settings.webrtc.enabled = True
    settings.webrtc.room = "default"  # Room is at default
    settings.webrtc.password = "my-secret"  # But password is custom
    settings.api.auth_enabled = False
    settings.permissions.webrtc_pairing_timeout_seconds = 300.0

    mock_config_mgr = MagicMock()
    saved_values = {}

    def mock_set(key, value, save=True):
        saved_values[key] = value

    mock_config_mgr.set = mock_set

    with (
        patch.object(service, "_get_gateway_config", return_value=settings),
        patch(_PATCH_CFGMGR, return_value=mock_config_mgr),
        patch(_PATCH_RTC) as mock_rtc_cls,
        patch(_PATCH_SET_RTC),
    ):
        mock_rtc = AsyncMock()
        mock_rtc_cls.return_value = mock_rtc

        await service._start_webrtc()

    # Room should be auto-generated
    assert "gateway.webrtc.room" in saved_values
    # Password should NOT be overwritten
    assert "gateway.webrtc.password" not in saved_values
