import { describe, expect, it } from 'vitest'

import {
  WebRtcManifestParseError,
  buildWebRtcManifestAck,
  parseWebRtcMeshManifest
} from '../src/webrtc/manifest.js'

function validFrame(): Record<string, unknown> & { shared_services: unknown[] } {
  return {
    type: 'manifest',
    peer_id: 'stable-peer-1',
    node_name: 'Kitchen Node',
    aurora_version: '0.5.0',
    shared_services: [
      {
        module: 'TTS',
        version: '1.2.0',
        capabilities: ['streaming', 'piper'],
        provider_id: 'mesh:stable-peer-1:TTS',
        service_instance_id: 'remote:stable-peer-1:TTS',
        methods: [
          { name: 'Request', bus_topic: 'TTS.Request', exposure: 'both' },
          { name: 'AudioChunk', bus_topic: 'TTS.AudioChunk', exposure: 'external' }
        ]
      },
      {
        module: 'Gateway',
        methods: ['Gateway.GetRegistry'],
        capabilities: []
      }
    ],
    timestamp: '2026-07-25T00:00:00Z'
  }
}

function projectionFrame(): Record<string, unknown> & { shared_services: unknown[] } {
  const frame = {
    type: 'manifest',
    peer_id: 'stable-peer-1',
    node_name: 'Kitchen Node',
    aurora_version: '0.5.0',
    active_protocol: 'projection-v1',
    active_version: 'v1',
    active_tier: 'projection',
    supported_protocols: ['legacy-unfiltered-v0', 'projection-v1'],
    projection_supported: true,
    projection_active: true,
    granted_permissions: null,
    shared_services: [
      {
        module: 'Empty',
        version: '1.0.0',
        capabilities: [],
        callable_features: [],
        available_feature_ids: [],
        methods: [],
        max_concurrent: 10,
        digest: '833efc794d360ebdd5cb49b9bc3940a72665a841b75d8e6edf1156ede35346fb'
      },
      {
        module: 'Tooling',
        version: '1.0.0',
        capabilities: ['tools'],
        callable_features: [],
        available_feature_ids: [],
        methods: [
          {
            name: 'GetExportCatalog',
            summary: '',
            bus_topic: 'Tooling.GetExportCatalog',
            exposure: 'external',
            input_model: null,
            output_model: null,
            required_perms: [],
            callable_feature_ids: [],
            callable_features: [],
            public_infrastructure: false,
            method_type: 'use',
            // Present and null, as every shipped provider emits it. Python
            // hashes the full model dump, so an omitted optional key changes
            // the digest.
            speech_constraints: null,
            input_schema: {
              type: 'object',
              properties: {
                offset: { type: 'number', default: 0 },
                ratio: { type: 'number', default: 1.5 }
              }
            },
            output_schema: null
          }
        ],
        max_concurrent: 10,
        digest: '1605ec959d1504cc33d97a0fd831f81843ce719192a63e64e3c5bf4d7d9e6899'
      }
    ],
    recipient_projection_evidence: {
      provider_peer_id: 'stable-peer-1',
      recipient_peer_id: 'thin-consumer-1',
      registry_revision: 'registry-7',
      registry_digest: '1'.repeat(64),
      policy_revision: 'export-4',
      policy_digest: '2'.repeat(64),
      auth_grant_revision: 9,
      auth_grant_state: 'active',
      auth_grant_digest: 'b18eee7c870701b06c6f809999fc66fd171ff8cda2ff2e31819fb95a956f53cc',
      grants_digest: '2288a5b40b8984d648f981ce5bce325cb274908ed11e816becfce86f861439c2',
      protocol_tier: 'projection-v1',
      // Whole evidence chain generated by app.services.gateway.mesh.negotiation
      // (_compute_service_digest, manifest_projection_digest, and
      // finalize_recipient_projection_evidence) so this fixture stays an
      // authoritative Python vector rather than self-referential values.
      projection_digest: '16737db247187fd1d934d2788f536173b01a9c8ca936dd268e8644df38217470',
      evidence_digest: '16b8ed74add000e338fd4d492554fb1f2a7dbd64c27c4c9c97ddf1401349419a',
      grants: []
    },
    timestamp: '2026-07-25T00:00:00Z'
  }
  return frame
}

describe('WebRTC mesh manifest parser', () => {
  it('normalizes a valid Python-shaped manifest and preserves raw frame', () => {
    const frame = validFrame()
    const parsed = parseWebRtcMeshManifest(frame, 'stable-peer-1')
    expect(parsed).toEqual({
      peerId: 'stable-peer-1',
      nodeName: 'Kitchen Node',
      version: '0.5.0',
      authenticated: true,
      trusted: false,
      services: [
        {
          module: 'TTS',
          version: '1.2.0',
          methods: ['TTS.Request', 'TTS.AudioChunk'],
          capabilities: ['streaming', 'piper'],
          providerId: 'mesh:stable-peer-1:TTS',
          serviceInstanceId: 'remote:stable-peer-1:TTS'
        },
        {
          module: 'Gateway',
          methods: ['Gateway.GetRegistry'],
          capabilities: []
        }
      ],
      raw: frame
    })
  })

  it('rejects signaling/transient ID substitution', () => {
    expect(() => parseWebRtcMeshManifest({ ...validFrame(), peer_id: 'sig-peer-1' }, 'stable-peer-1')).toThrow(/peer_id/u)
  })

  it('rejects accessor and prototype-bearing objects', () => {
    const accessor = validFrame() as Record<string, unknown>
    Object.defineProperty(accessor, 'node_name', { get: () => 'leak', enumerable: true })
    expect(() => parseWebRtcMeshManifest(accessor, 'stable-peer-1')).toThrow(WebRtcManifestParseError)

    class ManifestLike {
      type = 'manifest'
      peer_id = 'stable-peer-1'
      node_name = 'n'
      shared_services = []
    }
    expect(() =>
      parseWebRtcMeshManifest(new ManifestLike() as unknown as Record<string, unknown>, 'stable-peer-1')
    ).toThrow(WebRtcManifestParseError)

    const polluted = JSON.parse(
      '{"type":"manifest","peer_id":"stable-peer-1","node_name":"n","shared_services":[],"__proto__":{"polluted":true}}'
    ) as Record<string, unknown>
    expect(() => parseWebRtcMeshManifest(polluted, 'stable-peer-1')).toThrow(/unsafe/u)
  })

  it('rejects malformed services and methods', () => {
    expect(() =>
      parseWebRtcMeshManifest({ ...validFrame(), shared_services: [{ module: '', methods: [] }] }, 'stable-peer-1')
    ).toThrow(/module/u)
    expect(() =>
      parseWebRtcMeshManifest(
        { ...validFrame(), shared_services: [{ module: 'TTS', methods: [{ name: 'Request' }] }] },
        'stable-peer-1'
      )
    ).toThrow(/bus_topic/u)
    expect(() =>
      parseWebRtcMeshManifest(
        { ...validFrame(), shared_services: [{ module: 'TTS', methods: ['not-a-topic'] }] },
        'stable-peer-1'
      )
    ).toThrow(/topic/u)
  })

  it('rejects duplicate service modules', () => {
    const frame = validFrame()
    frame.shared_services = [frame.shared_services[0]!, { ...frame.shared_services[0]!, version: '2.0.0' }]
    expect(() => parseWebRtcMeshManifest(frame, 'stable-peer-1')).toThrow(/duplicate/u)
  })

  it('rejects bounded-size violations', () => {
    expect(() =>
      parseWebRtcMeshManifest({ ...validFrame(), node_name: 'x'.repeat(600) }, 'stable-peer-1')
    ).toThrow(/node_name/u)
    expect(() =>
      parseWebRtcMeshManifest(
        {
          ...validFrame(),
          shared_services: Array.from({ length: 129 }, (_, index) => ({ module: `M${index}`, methods: [] }))
        },
        'stable-peer-1'
      )
    ).toThrow(/shared_services/u)
    expect(() =>
      parseWebRtcMeshManifest(
        {
          ...validFrame(),
          shared_services: [{ module: 'TTS', methods: Array.from({ length: 513 }, () => 'TTS.Request') }]
        },
        'stable-peer-1'
      )
    ).toThrow(/methods/u)
  })

  it('rejects explicit consumer-only provider claims', () => {
    expect(() => parseWebRtcMeshManifest({ ...validFrame(), role: 'consumer' }, 'stable-peer-1')).toThrow(/consumer-only/u)
    expect(() => parseWebRtcMeshManifest({ ...validFrame(), capabilities: ['consumer_only_v1'] }, 'stable-peer-1')).toThrow(/consumer-only/u)
  })

  it('builds a Python-compatible projection manifest ACK from authoritative raw evidence', () => {
    const parsed = parseWebRtcMeshManifest(projectionFrame(), 'stable-peer-1')
    const ack = buildWebRtcManifestAck(parsed)

    expect(ack).toEqual({
      type: 'manifest_ack',
      compatible_services: ['Tooling'],
      incompatible_services: ['Empty'],
      unused_services: [],
      active_protocol: 'projection-v1',
      active_version: 'v1',
      active_tier: 'projection',
      protocol_revision: 'v1',
      registry_revision: 'registry-7',
      export_policy_revision: 'export-4',
      auth_grant_revision: 9,
      projection_digest: '16737db247187fd1d934d2788f536173b01a9c8ca936dd268e8644df38217470',
      services: [
        {
          service_id: 'Empty',
          service_label: '',
          status: 'incompatible',
          reason_codes: ['method_not_advertised'],
          reason: ''
        },
        {
          service_id: 'Tooling',
          service_label: '',
          status: 'compatible',
          reason_codes: [],
          reason: ''
        }
      ]
    })
  })

  describe('projection evidence chain', () => {
    // Each case is one Python `_classify_projection_manifest` rejection that
    // this parser previously accepted, leaving the two implementations
    // disagreeing about which peers were usable.
    function ackFor(mutate: (frame: Record<string, unknown> & { shared_services: unknown[] }) => void) {
      const frame = projectionFrame()
      mutate(frame)
      return () => buildWebRtcManifestAck(parseWebRtcMeshManifest(frame, 'stable-peer-1'))
    }

    function evidenceOf(frame: Record<string, unknown>): Record<string, unknown> {
      return frame.recipient_projection_evidence as Record<string, unknown>
    }

    it('rejects an authority that is not active', () => {
      expect(ackFor((frame) => { evidenceOf(frame).auth_grant_state = 'revoked' })).toThrow(/authority is not active/)
    })

    it('rejects an unknown authority revision', () => {
      expect(ackFor((frame) => { evidenceOf(frame).auth_grant_revision = 0 })).toThrow(/authority revision is unknown/)
    })

    it('rejects grants that contradict grants_digest', () => {
      expect(ackFor((frame) => {
        evidenceOf(frame).grants = [{ permission: 'Tooling.ExecuteTool', source: 'effective' }]
      })).toThrow(/grants_digest contradicts/)
    })

    it('rejects a tampered authority digest', () => {
      expect(ackFor((frame) => { evidenceOf(frame).auth_grant_digest = 'a'.repeat(64) })).toThrow(/auth_grant_digest contradicts/)
    })

    it('rejects a tampered evidence digest', () => {
      expect(ackFor((frame) => { evidenceOf(frame).evidence_digest = 'b'.repeat(64) })).toThrow(/evidence_digest contradicts/)
    })

    it('rejects unknown evidence fields', () => {
      expect(ackFor((frame) => { evidenceOf(frame).smuggled = 'value' })).toThrow(/unknown field/)
    })

    it('rejects a service whose digest does not match its contents', () => {
      expect(ackFor((frame) => {
        const service = frame.shared_services[1] as Record<string, unknown>
        service.version = '9.9.9'
      })).toThrow(/service digest contradicts/)
    })

    it('rejects a service that omits its digest', () => {
      expect(ackFor((frame) => {
        const service = frame.shared_services[0] as Record<string, unknown>
        delete service.digest
      })).toThrow(/missing its digest/)
    })

    it('rejects services that are not in canonical order', () => {
      expect(ackFor((frame) => { frame.shared_services = [...frame.shared_services].reverse() })).toThrow(/not canonical/)
    })

    it('rejects legacy granted_permissions smuggled into a projection manifest', () => {
      expect(ackFor((frame) => { frame.granted_permissions = ['Tooling.GetTools'] })).toThrow(/legacy granted_permissions/)
    })
  })

  it('fails closed for legacy manifests without inventing projection evidence', () => {
    const parsed = parseWebRtcMeshManifest(validFrame(), 'stable-peer-1')
    expect(buildWebRtcManifestAck(parsed)).toMatchObject({
      type: 'manifest_ack',
      compatible_services: [],
      incompatible_services: ['Gateway', 'TTS'],
      unused_services: [],
      protocol_revision: null,
      export_policy_revision: null,
      projection_digest: null,
      services: [
        { service_id: 'Gateway', status: 'incompatible', reason_codes: ['legacy_unverifiable'] },
        { service_id: 'TTS', status: 'incompatible', reason_codes: ['legacy_unverifiable'] }
      ]
    })
  })

  it('orders ACK service IDs using Python-compatible code point order', () => {
    const frame = validFrame()
    frame.shared_services = [
      { module: 'Transcription', methods: ['Transcription.Transcribe'], capabilities: [] },
      { module: 'TTS', methods: ['TTS.Synthesize'], capabilities: [] },
      { module: 'Tooling', methods: ['Tooling.GetTools'], capabilities: [] },
      { module: 'Orchestrator', methods: ['Orchestrator.ExternalUserInput'], capabilities: [] }
    ]

    const ack = buildWebRtcManifestAck(parseWebRtcMeshManifest(frame, 'stable-peer-1'))

    expect(ack.incompatible_services).toEqual(['Orchestrator', 'TTS', 'Tooling', 'Transcription'])
    expect(ack.services?.map((service) => service.service_id)).toEqual([
      'Orchestrator',
      'TTS',
      'Tooling',
      'Transcription'
    ])
  })

  it('rejects projection ACKs with missing or contradictory authority evidence', () => {
    const missingEvidence = parseWebRtcMeshManifest(
      { ...projectionFrame(), recipient_projection_evidence: undefined },
      'stable-peer-1'
    )
    expect(() => buildWebRtcManifestAck(missingEvidence)).toThrow(/recipient_projection_evidence/u)

    const contradictory = projectionFrame()
    contradictory.recipient_projection_evidence = {
      ...(contradictory.recipient_projection_evidence as Record<string, unknown>),
      projection_digest: '0'.repeat(64)
    }
    const parsed = parseWebRtcMeshManifest(contradictory, 'stable-peer-1')
    // Rewriting projection_digest also invalidates the evidence digest that
    // covers it, and that check now runs first.
    expect(() => buildWebRtcManifestAck(parsed)).toThrow(/evidence_digest contradicts/u)
  })

  it('rejects unsafe manifest ACK inputs before reading authority fields', () => {
    const parsed = parseWebRtcMeshManifest(projectionFrame(), 'stable-peer-1') as unknown as Record<string, unknown>
    Object.defineProperty(parsed, 'peerId', { get: () => 'stable-peer-1', enumerable: true })
    expect(() => buildWebRtcManifestAck(parsed as never)).toThrow(WebRtcManifestParseError)
  })
})
