// Generated by scripts/generate-browser-voice-catalog.mjs. Do not edit manually.
import type { AuroraBrowserRawTtsEntry } from './browser-voice-catalog.js'

export const AURORA_BROWSER_POCKETTTS_OVERLAY = {
  "schema_version": 1,
  "catalog_id": "aurora-sherpa-pockettts-language-packs-v1",
  "revision": "bootstrap-en-fr-converted-v1",
  "temporary_bootstrap": true,
  "removal_point": "After GitHub release tag sherpa-pockettts-language-packs publishes stable archive URLs, replace overlay download URLs with those assets and delete .github/workflows/sherpa-pockettts-language-packs.yml convert/build steps.",
  "download_base": "https://github.com/joaojhgs/aurora/releases/download/sherpa-pockettts-language-packs/",
  "entries": [
    {
      "archive": {
        "asset_id": 900000001,
        "byte_size": 202924056,
        "filename": "aurora-pockettts-en-2026-04.tar.bz2",
        "format": "tar_bzip2",
        "root": "aurora-pockettts-en-2026-04",
        "sha256": "bb38a3597c9c90d3f341b821f3558a0ad812c664c962ad47393a1d8cc4a4f5c1",
        "updated_at": "2026-08-15T23:15:26Z",
        "url": "https://github.com/joaojhgs/aurora/releases/download/sherpa-pockettts-language-packs/aurora-pockettts-en-2026-04.tar.bz2"
      },
      "bindings": {
        "decoder": "aurora-pockettts-en-2026-04/decoder.int8.onnx",
        "encoder": "aurora-pockettts-en-2026-04/encoder.onnx",
        "lm_flow": "aurora-pockettts-en-2026-04/lm_flow.int8.onnx",
        "lm_main": "aurora-pockettts-en-2026-04/lm_main.int8.onnx",
        "model_card": "aurora-pockettts-en-2026-04/README.md",
        "text_conditioner": "aurora-pockettts-en-2026-04/text_conditioner.onnx",
        "token_scores_json": "aurora-pockettts-en-2026-04/token_scores.json",
        "vocab_json": "aurora-pockettts-en-2026-04/vocab.json",
        "reference_audio": "aurora-pockettts-en-2026-04/internal_reference.wav"
      },
      "capability": {
        "encoder_status": "zeroed_by_remove_voice_cloning_and_push",
        "license": "CC-BY-4.0",
        "reference_audio_mode": "internal",
        "source_repo": "kyutai/pocket-tts-without-voice-cloning",
        "source_revision": "e041936c75475d350b405bc870bcf7c22da4e9e6",
        "voice_cloning": false
      },
      "display_name": "PocketTTS English",
      "engine": "sherpa_onnx",
      "language": "en-us",
      "model_family": "pockettts",
      "precision": "int8",
      "quality": null,
      "sample_rate_hz": 24000,
      "terms": {
        "download_initiated_by_user": true,
        "redistributed_by_aurora": true,
        "source": "upstream_model_card"
      },
      "voice_id": "standard:pockettts:aurora-pockettts-en-2026-04"
    },
    {
      "archive": {
        "asset_id": 900000002,
        "byte_size": 686925861,
        "filename": "aurora-pockettts-fr-24l.tar.bz2",
        "format": "tar_bzip2",
        "root": "aurora-pockettts-fr-24l",
        "sha256": "d24491918f7097c84c6d3440c7219d0342d746184674ea0926b5ef9ea07c697f",
        "updated_at": "2026-08-16T00:57:00Z",
        "url": "https://github.com/joaojhgs/aurora/releases/download/sherpa-pockettts-language-packs/aurora-pockettts-fr-24l.tar.bz2"
      },
      "bindings": {
        "decoder": "aurora-pockettts-fr-24l/decoder.int8.onnx",
        "encoder": "aurora-pockettts-fr-24l/encoder.onnx",
        "lm_flow": "aurora-pockettts-fr-24l/lm_flow.int8.onnx",
        "lm_main": "aurora-pockettts-fr-24l/lm_main.int8.onnx",
        "model_card": "aurora-pockettts-fr-24l/README.md",
        "text_conditioner": "aurora-pockettts-fr-24l/text_conditioner.onnx",
        "token_scores_json": "aurora-pockettts-fr-24l/token_scores.json",
        "vocab_json": "aurora-pockettts-fr-24l/vocab.json",
        "reference_audio": "aurora-pockettts-fr-24l/internal_reference.wav"
      },
      "capability": {
        "encoder_status": "zeroed_by_remove_voice_cloning_and_push",
        "license": "CC-BY-4.0",
        "reference_audio_mode": "internal",
        "source_repo": "kyutai/pocket-tts-without-voice-cloning",
        "source_revision": "e041936c75475d350b405bc870bcf7c22da4e9e6",
        "voice_cloning": false
      },
      "display_name": "PocketTTS French",
      "engine": "sherpa_onnx",
      "language": "fr-fr",
      "model_family": "pockettts",
      "precision": "int8",
      "quality": null,
      "sample_rate_hz": 24000,
      "terms": {
        "download_initiated_by_user": true,
        "redistributed_by_aurora": true,
        "source": "upstream_model_card"
      },
      "voice_id": "standard:pockettts:aurora-pockettts-fr-24l"
    }
  ]
} as const satisfies {
  readonly schema_version: number
  readonly catalog_id: string
  readonly revision: string
  readonly temporary_bootstrap: boolean
  readonly removal_point: string
  readonly download_base: string
  readonly entries: readonly AuroraBrowserRawTtsEntry[]
}
