// Generated by scripts/generate-browser-voice-catalog.mjs. Do not edit manually.
import type { AuroraBrowserRawTtsEntry } from './browser-voice-catalog.js'

export const AURORA_BROWSER_POCKETTTS_OVERLAY = {
  "schema_version": 1,
  "catalog_id": "aurora-sherpa-pockettts-language-packs-v1",
  "revision": "bootstrap-en-fr-fixed-state-v1",
  "temporary_bootstrap": true,
  "removal_point": "After GitHub release tag sherpa-pockettts-language-packs publishes stable archive URLs, replace overlay download URLs with those assets and delete .github/workflows/sherpa-pockettts-language-packs.yml convert/build steps.",
  "download_base": "https://github.com/joaojhgs/aurora/releases/download/sherpa-pockettts-language-packs/",
  "entries": [
    {
      "archive": {
        "asset_id": 900000001,
        "byte_size": 75167501,
        "filename": "aurora-pockettts-en-2026-04.tar.bz2",
        "format": "tar_bzip2",
        "root": "aurora-pockettts-en-2026-04",
        "sha256": "eb7009f8e42d826a70e3f520501b33be7fbd7d60e2f8a798a69717ba81ff1063",
        "updated_at": "2026-08-16T05:29:31Z",
        "url": "https://github.com/joaojhgs/aurora/releases/download/sherpa-pockettts-language-packs/aurora-pockettts-en-2026-04.tar.bz2"
      },
      "bindings": {
        "bos_before_voice": "aurora-pockettts-en-2026-04/bos_before_voice.bin",
        "decoder": "aurora-pockettts-en-2026-04/decoder.int8.onnx",
        "encoder": "aurora-pockettts-en-2026-04/encoder.onnx",
        "fixed_voice_state": "aurora-pockettts-en-2026-04/fixed_voice_state.bin",
        "lm_flow": "aurora-pockettts-en-2026-04/lm_flow.int8.onnx",
        "lm_main": "aurora-pockettts-en-2026-04/lm_main.int8.onnx",
        "model_card": "aurora-pockettts-en-2026-04/README.md",
        "pocket_protocol": "aurora-pockettts-en-2026-04/pocket_protocol.json",
        "text_conditioner": "aurora-pockettts-en-2026-04/text_conditioner.onnx",
        "token_scores_json": "aurora-pockettts-en-2026-04/token_scores.json",
        "vocab_json": "aurora-pockettts-en-2026-04/vocab.json"
      },
      "capability": {
        "encoder_status": "zeroed_by_remove_voice_cloning_and_push",
        "license": "CC-BY-4.0",
        "reference_audio_mode": "internal",
        "source_repo": "kyutai/pocket-tts-without-voice-cloning",
        "source_revision": "e041936c75475d350b405bc870bcf7c22da4e9e6",
        "voice_cloning": false
      },
      "display_name": "PocketTTS English",
      "engine": "sherpa_onnx",
      "language": "en-us",
      "model_family": "pockettts",
      "precision": "int8",
      "quality": null,
      "sample_rate_hz": 24000,
      "terms": {
        "download_initiated_by_user": true,
        "redistributed_by_aurora": true,
        "source": "upstream_model_card"
      },
      "voice_id": "standard:pockettts:aurora-pockettts-en-2026-04"
    },
    {
      "archive": {
        "asset_id": 900000002,
        "byte_size": 271119980,
        "filename": "aurora-pockettts-fr-24l.tar.bz2",
        "format": "tar_bzip2",
        "root": "aurora-pockettts-fr-24l",
        "sha256": "92fee41aace81ec4878b1119cbff5b28e06471a61434b9def449b7bfeebe9ee2",
        "updated_at": "2026-08-16T05:34:44Z",
        "url": "https://github.com/joaojhgs/aurora/releases/download/sherpa-pockettts-language-packs/aurora-pockettts-fr-24l.tar.bz2"
      },
      "bindings": {
        "bos_before_voice": "aurora-pockettts-fr-24l/bos_before_voice.bin",
        "decoder": "aurora-pockettts-fr-24l/decoder.int8.onnx",
        "encoder": "aurora-pockettts-fr-24l/encoder.onnx",
        "fixed_voice_state": "aurora-pockettts-fr-24l/fixed_voice_state.bin",
        "lm_flow": "aurora-pockettts-fr-24l/lm_flow.int8.onnx",
        "lm_main": "aurora-pockettts-fr-24l/lm_main.int8.onnx",
        "model_card": "aurora-pockettts-fr-24l/README.md",
        "pocket_protocol": "aurora-pockettts-fr-24l/pocket_protocol.json",
        "text_conditioner": "aurora-pockettts-fr-24l/text_conditioner.onnx",
        "token_scores_json": "aurora-pockettts-fr-24l/token_scores.json",
        "vocab_json": "aurora-pockettts-fr-24l/vocab.json"
      },
      "capability": {
        "encoder_status": "zeroed_by_remove_voice_cloning_and_push",
        "license": "CC-BY-4.0",
        "reference_audio_mode": "internal",
        "source_repo": "kyutai/pocket-tts-without-voice-cloning",
        "source_revision": "e041936c75475d350b405bc870bcf7c22da4e9e6",
        "voice_cloning": false
      },
      "display_name": "PocketTTS French",
      "engine": "sherpa_onnx",
      "language": "fr-fr",
      "model_family": "pockettts",
      "precision": "int8",
      "quality": null,
      "sample_rate_hz": 24000,
      "terms": {
        "download_initiated_by_user": true,
        "redistributed_by_aurora": true,
        "source": "upstream_model_card"
      },
      "voice_id": "standard:pockettts:aurora-pockettts-fr-24l"
    }
  ]
} as const satisfies {
  readonly schema_version: number
  readonly catalog_id: string
  readonly revision: string
  readonly temporary_bootstrap: boolean
  readonly removal_point: string
  readonly download_base: string
  readonly entries: readonly AuroraBrowserRawTtsEntry[]
}
