# generated by datamodel-codegen:
#   filename:  config_schema.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import AnyUrl, Field, SecretStr, constr

from app.shared.config.models_base import BaseConfigModel


class Assistant(BaseConfigModel):
    automatic_tts_readback: bool | None = False
    """
    Automatically play TTS for assistant replies initiated from typed UI prompts. Voice-origin prompts always keep voice-to-voice readback.
    """


class DesktopOverlay(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable the desktop overlay window for quick access to Aurora.
    """
    voice_overlay_enabled: bool | None = True
    """
    Show voice activity and listening state in the desktop overlay when voice features are active.
    """
    text_hotkey: str | None = "CommandOrControl+K"
    """
    Global keyboard shortcut that opens the desktop overlay text input.
    """
    close_behavior: Literal["hide_to_tray"] | None = "hide_to_tray"
    """
    Behavior when the desktop overlay window is closed.
    """
    auto_close_delay_ms: int | None = Field(1200, ge=0)
    """
    Delay in milliseconds before the desktop overlay auto-closes after transient interactions; set to 0 to close immediately.
    """
    visible_on_all_workspaces: bool | None = True
    """
    Keep the desktop overlay visible across all virtual desktops or workspaces when supported by the OS.
    """
    persist_positions: bool | None = True
    """
    Remember desktop overlay window positions between app launches.
    """


class Ui(BaseConfigModel):
    activate: bool | None = False
    """
    Enable graphical user interface
    """
    dark_mode: bool | None = False
    """
    Enable dark mode theme
    """
    debug: bool | None = False
    """
    Enable debug mode for verbose logging
    """
    assistant: Assistant | None = None
    """
    Assistant UI behavior settings
    """
    desktop_overlay: DesktopOverlay | None = None
    """
    Desktop assistant overlay window behavior and persistence settings.
    """


class System(BaseConfigModel):
    models_dir: str | None = "voice_models/"
    """
    Base directory for voice/model files
    """
    primary_language: str | None = Field(
        "en",
        max_length=255,
        min_length=2,
        pattern="^(?:[A-Za-z]{2,8}(?:[-_][A-Za-z0-9]{1,8})*|[IiXx](?:[-_][A-Za-z0-9]{1,8})+)$",
        title="Primary language",
    )
    """
    BCP 47 language tag Aurora uses whenever one device language is required. Available choices come from the installed speech-pack catalog.
    """
    voice_language: str | None = Field(
        "auto",
        max_length=255,
        min_length=2,
        pattern="^(?:[Aa][Uu][Tt][Oo]|[A-Za-z]{2,8}(?:[-_][A-Za-z0-9]{1,8})*|[IiXx](?:[-_][A-Za-z0-9]{1,8})+)$",
        title="Voice language",
    )
    """
    Automatic detection or a BCP 47 speech language tag from the installed speech-pack catalog.
    """


class Cors(BaseConfigModel):
    origins: list[str] | None = ["*"]
    """
    Allowed CORS origins
    """
    allow_credentials: bool | None = True
    """
    Allow credentials in CORS requests
    """


class Api(BaseConfigModel):
    host: str | None = "0.0.0.0"
    """
    Host address to bind the gateway
    """
    port: int | None = Field(8000, ge=1, le=65535)
    """
    Port number for the gateway
    """
    request_timeout_s: float | None = Field(30.0, ge=1.0, le=300.0)
    """
    Request timeout in seconds
    """
    cors: Cors | None = None
    """
    CORS configuration
    """
    token_secret: SecretStr | None = ""
    """
    Secret for JWT signing and mesh inbound token encryption. Prefer AURORA_TOKEN_SECRET in .env.
    """


class MeshNetwork(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable P2P mesh networking
    """
    node_name: str | None = ""
    """
    Human-readable name for this node in the mesh
    """
    version_policy: Literal["exact", "compatible", "any"] | None = "compatible"
    """
    How strictly to enforce version matching
    """
    peer_selection: Literal["lowest_latency", "round_robin", "random"] | None = "lowest_latency"
    """
    Strategy for choosing among multiple peers
    """
    ping_interval_s: float | None = Field(30.0, ge=1.0)
    """
    How often to measure peer latency (seconds)
    """
    registry_announce_interval_s: float | None = Field(60.0, ge=1.0)
    """
    How often to re-announce manifest (seconds)
    """
    stale_peer_timeout_s: float | None = Field(120.0, ge=1.0)
    """
    Mark peer stale after this many seconds without pong
    """
    remote_timeout_s: float | None = Field(30.0, ge=1.0)
    """
    Timeout for remote bus publish calls (seconds)
    """


class Webrtc(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable WebRTC transport
    """
    strategy: str | None = "mqtt"
    """
    Signaling strategy
    """
    app_id: str | None = "aurora"
    """
    Application ID for signaling
    """
    room: str | None = "default"
    """
    Signaling room name. Auto-generated on first run if set to 'default' or empty.
    """
    password: SecretStr | None = ""
    """
    Room password for signaling encryption. Auto-generated on first run if empty. Prefer AURORA_WEBRTC_PASSWORD in .env.
    """
    encrypt_signaling: bool | None = True
    """
    Enable signaling encryption
    """
    enable_app_layer_e2ee: bool | None = False
    """
    When true, all WebRTC DataChannel JSON messages are sealed as binary AEAD payloads with the room data key. Peers with mismatched settings do not fall back to plaintext.
    """
    legacy_event_broadcast: bool | None = True
    """
    Temporary compatibility switch for non-sensitive events sent to peers that do not advertise scoped_event_subscriptions_v1. Sensitive and scoped-only topics remain blocked regardless of this value.
    """
    stun_servers: list[str] | None = ["stun:stun.l.google.com:19302"]
    """
    STUN server URLs for NAT traversal
    """
    turn_servers: list[Any] | None = []
    """
    TURN server configurations for relay
    """


class SignalingMqtt(BaseConfigModel):
    brokers: list[str] | None = [
        "wss://broker.emqx.io:8084/mqtt",
        "wss://test.mosquitto.org:8081/mqtt",
    ]
    """
    MQTT broker WebSocket URLs
    """
    topic_root: str | None = "aurora"
    """
    Root MQTT topic for signaling
    """


class Gateway(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable HTTP Gateway for REST API access
    """
    api: Api | None = None
    """
    REST API settings
    """
    mesh_network: MeshNetwork | None = None
    """
    P2P mesh networking configuration
    """
    webrtc: Webrtc | None = None
    """
    WebRTC transport configuration
    """
    signaling_mqtt: SignalingMqtt | None = None
    """
    MQTT signaling configuration for WebRTC
    """


class Auth(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable authentication service
    """
    api_keys: list[SecretStr] | None = []
    """
    List of valid API keys (sensitive; prefer AURORA_GATEWAY_API_KEYS in .env)
    """
    token_expiry_days: int | None = Field(365, ge=1)
    """
    Default token expiry in days
    """
    session_token_expiry_hours: int | None = Field(24, ge=1)
    """
    Session token expiry in hours (for login)
    """
    pairing_code_expiry_minutes: int | None = Field(5, ge=1)
    """
    Pairing code expiry in minutes
    """
    pairing_max_attempts_per_ip: int | None = Field(5, ge=1)
    """
    Max pairing attempts per IP before rate limiting
    """
    default_pairing_permissions: list[str] | None = []
    """
    Default permissions assigned to new devices during pairing
    """
    webrtc_auth_timeout_seconds: float | None = Field(10.0, ge=1.0)
    """
    Timeout in seconds for WebRTC peer authentication
    """
    webrtc_pairing_timeout_seconds: float | None = Field(300.0, ge=10.0)
    """
    Timeout in seconds for peers in the pairing flow (awaiting human approval)
    """
    audit_enabled: bool | None = True
    """
    Enable audit logging of security events
    """
    audit_retention_days: int | None = Field(90, ge=1)
    """
    Audit log retention period in days
    """


class Piper(BaseConfigModel):
    model_file_path: str | None = "voice_models/en_US-lessac-medium.onnx"
    """
    Path to the Piper model file
    """
    model_config_file_path: str | None = "voice_models/en_US-lessac-medium.onnx.txt"
    """
    Path to the Piper model configuration file
    """
    model_sample_rate: int | None = Field(22050, ge=8000, le=48000)
    """
    Sample rate for Piper output
    """
    executable_path: str | None = ""
    """
    Path to Piper executable
    """


class Pockettts(BaseConfigModel):
    quality_tier: Literal["compact", "quality"] | None = "compact"
    custom_config_path: str | None = None
    cache_dir: str | None = "voice_models/pockettts"
    voice_state_dir: str | None = "voice_models/pockettts/voices"
    device: Literal["cpu"] | None = "cpu"
    initialization_timeout_s: float | None = Field(120.0, ge=1.0)
    request_timeout_s: float | None = Field(120.0, ge=1.0)
    max_concurrent_requests: int | None = Field(1, ge=1, le=1)
    preload_model: bool | None = True
    preload_voice_ids: list[str] | None = []
    temperature: float | None = None
    lsd_decode_steps: int | None = Field(1, ge=1)
    noise_clamp: float | None = None
    eos_threshold: float | None = -4.0
    quantize: bool | None = False


class Providers(BaseConfigModel):
    piper: Piper | None = Field({}, validate_default=True)
    """
    Piper provider settings
    """
    pockettts: Pockettts | None = Field({}, validate_default=True)
    """
    PocketTTS provider settings
    """


class VoiceRegistry(BaseConfigModel):
    manifest_path: str | None = "voice_models/voices.manifest.json"
    asset_base_url: str | None = None
    cache_dir: str | None = "voice_models/voice-pack"
    verify_sha256: bool | None = True
    standard_pack_enabled: bool | None = True
    cloning_enabled: bool | None = True
    retain_clone_source: bool | None = False
    clone_min_duration_s: float | None = Field(6.0, ge=0.1)
    clone_max_duration_s: float | None = Field(15.0, ge=0.1)
    clone_max_source_bytes: int | None = Field(20971520, ge=1)
    clone_max_wire_bytes: int | None = Field(2097152, ge=1)
    accepted_import_formats: list[Literal["wav", "mp3", "mp4", "m4a", "webm"]] | None = [
        "wav",
        "mp3",
        "mp4",
        "m4a",
        "webm",
    ]


class AmbientTranscription(BaseConfigModel):
    enable: bool | None = False
    """
    Enable ambient transcription
    """
    chunk_duration: float | None = Field(3.0, ge=0.5, le=60.0)
    """
    Duration in seconds of audio chunks to process
    """
    storage_path: str | None = "ambient_logs/"
    """
    Directory path for file storage
    """
    filter_short_transcriptions: bool | None = True
    """
    Filter out short transcriptions to reduce noise
    """
    min_transcription_length: int | None = Field(10, ge=0)
    """
    Minimum character length for transcriptions when filtering
    """


class AudioInput(BaseConfigModel):
    device_index: int | None = None
    """
    Audio input device index (null for default)
    """
    sample_rate: Literal[8000, 16000, 22050, 44100, 48000] | None = 16000
    """
    Audio sample rate in Hz
    """
    channels: int | None = Field(1, ge=1, le=2)
    """
    Number of audio channels
    """
    chunk_size: int | None = Field(1024, ge=128, le=8192)
    """
    Audio chunk size in frames
    """
    format: Literal["int16", "int32", "float32"] | None = "int16"
    """
    Audio sample format
    """


class RealtimeModel(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable realtime transcription model
    """
    model_size: Literal["tiny", "base", "small", "medium", "large"] | None = "tiny"
    """
    Whisper model size for realtime transcription
    """
    device: Literal["cpu", "cuda", "auto"] | None = "cpu"
    """
    Device for realtime model
    """
    compute_type: Literal["int8", "int16", "float16", "float32"] | None = "int8"
    """
    Compute type for realtime model
    """


class AccurateModel(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable accurate transcription model
    """
    model_size: Literal["tiny", "base", "small", "medium", "large"] | None = "base"
    """
    Whisper model size for accurate transcription
    """
    device: Literal["cpu", "cuda", "auto"] | None = "cpu"
    """
    Device for accurate model
    """
    compute_type: Literal["int8", "int16", "float16", "float32"] | None = "int8"
    """
    Compute type for accurate model
    """


class Options(BaseConfigModel):
    api_key: SecretStr | None = ""
    """
    OpenAI API key (sensitive; prefer OPENAI_API_KEY in .env)
    """
    model: str | None = "gpt-4o"
    """
    OpenAI model to use
    """
    temperature: float | None = Field(0.7, ge=0.0, le=2.0)
    """
    Sampling temperature for OpenAI models
    """
    max_tokens: int | None = Field(512, ge=1, le=4096)
    """
    Maximum tokens for OpenAI responses
    """


class Openai(BaseConfigModel):
    options: Options | None = None


class Options1(BaseConfigModel):
    endpoint_url: str | None = ""
    """
    HuggingFace endpoint URL
    """
    model: str | None = ""
    """
    HuggingFace model name
    """
    access_token: SecretStr | None = ""
    """
    HuggingFace access token (sensitive; prefer .env)
    """
    temperature: float | None = Field(0.7, ge=0.0, le=2.0)
    """
    Sampling temperature
    """
    max_tokens: int | None = Field(512, ge=1, le=4096)
    """
    Maximum tokens for responses
    """


class HuggingfaceEndpoint(BaseConfigModel):
    options: Options1 | None = None


class ThirdParty(BaseConfigModel):
    openai: Openai | None = None
    huggingface_endpoint: HuggingfaceEndpoint | None = None


class Options2(BaseConfigModel):
    model: str | None = "microsoft/DialoGPT-medium"
    """
    HuggingFace model name for local pipeline
    """
    temperature: float | None = Field(0.7, ge=0.0, le=2.0)
    """
    Sampling temperature
    """
    max_tokens: int | None = Field(None, ge=1)
    """
    Maximum tokens for responses
    """
    torch_dtype: Literal["auto", "float32", "float16", "bfloat16"] | None = "auto"
    """
    PyTorch data type
    """
    device: Literal["cpu", "cuda", "auto"] | None = None
    """
    Device to run the model on
    """
    pipeline_kwargs: dict[str, Any] | None = None
    """
    Additional pipeline keyword arguments
    """
    model_kwargs: dict[str, Any] | None = None
    """
    Additional model keyword arguments
    """


class HuggingfacePipeline(BaseConfigModel):
    options: Options2 | None = None


class Options3(BaseConfigModel):
    model_path: str | None = ""
    """
    Path to the GGUF model file
    """
    temperature: float | None = Field(1.0, ge=0.0, le=2.0)
    """
    Sampling temperature for Llama.cpp
    """
    max_tokens: int | None = Field(512, ge=1, le=4096)
    """
    Maximum tokens for responses
    """
    n_ctx: int | None = Field(2048, ge=512, le=32768)
    """
    Context window size
    """
    n_gpu_layers: int | None = Field(0, ge=0, le=100)
    """
    Number of layers to offload to GPU
    """
    n_batch: int | None = Field(1000, ge=1, le=2048)
    """
    Batch size for processing
    """
    top_p: float | None = Field(0.95, ge=0.0, le=1.0)
    """
    Top-p sampling parameter
    """
    top_k: int | None = Field(64, ge=1, le=200)
    """
    Top-k sampling parameter
    """
    repeat_penalty: float | None = Field(1.0, ge=0.1, le=2.0)
    """
    Repetition penalty
    """
    min_p: float | None = Field(0.0, ge=0.0, le=1.0)
    """
    Minimum probability threshold
    """
    chat_format: (
        Literal["chatml", "chatml-function-calling", "llama-2", "alpaca", "vicuna"] | None
    ) = "chatml-function-calling"
    """
    Chat format template to use
    """


class LlamaCpp(BaseConfigModel):
    options: Options3 | None = None


class Local(BaseConfigModel):
    huggingface_pipeline: HuggingfacePipeline | None = None
    llama_cpp: LlamaCpp | None = None


class RemotePeer(BaseConfigModel):
    peer_id: str | None = None
    """
    Stable mesh peer id to route inference to
    """
    provider_id: str | None = None
    """
    Provider alias or peer id to route inference to
    """
    service_instance_id: str | None = None
    """
    Remote service instance id such as remote:<peer>:Orchestrator
    """
    resource_namespace: str | None = "inference"
    timeout_s: float | None = Field(60, ge=1.0)


class MeshPeer(BaseConfigModel):
    peer_id: str | None = None
    provider_id: str | None = None
    service_instance_id: str | None = None
    resource_namespace: str | None = "inference"
    timeout_s: float | None = Field(60, ge=1.0)


class Llm(BaseConfigModel):
    provider: (
        Literal[
            "openai",
            "huggingface_endpoint",
            "huggingface_pipeline",
            "llama_cpp",
            "remote_peer",
            "mesh_peer",
        ]
        | None
    ) = "openai"
    """
    LLM provider to use
    """
    third_party: ThirdParty | None = None
    """
    Third-party LLM provider options
    """
    local: Local | None = None
    """
    Local LLM provider options
    """
    remote_peer: RemotePeer | None = None
    """
    Remote mesh peer LLM routing options. Tools and graph execution remain local; only chat inference is delegated.
    """
    mesh_peer: MeshPeer | None = None
    """
    Alias for remote_peer LLM routing options
    """


class DispatchDefault(BaseConfigModel):
    enabled: bool | None = False
    peer_id: str | None = None
    provider_id: str | None = None
    service_instance_id: str | None = None
    resource_namespace: str | None = None
    timeout_s: float | None = Field(None, ge=1.0)


class InferenceDefault(BaseConfigModel):
    provider: Literal["local", "configured", "remote_peer", "mesh_peer"] | None = "configured"
    peer_id: str | None = None
    provider_id: str | None = None
    service_instance_id: str | None = None
    resource_namespace: str | None = "inference"
    model_id: str | None = None
    timeout_s: float | None = Field(60, ge=1.0)


class Routing(BaseConfigModel):
    dispatch_default: DispatchDefault | None = None
    """
    Default mesh dispatch route for external orchestrator requests when no runtime dispatch selector is supplied
    """
    inference_default: InferenceDefault | None = None
    """
    Default chat inference provider for local orchestration; does not affect dispatch routing
    """


class Embeddings(BaseConfigModel):
    use_local: bool | None = True
    """
    Use local embeddings model instead of API
    """


class HardwareAcceleration(BaseConfigModel):
    ocr_bg: bool | None = False
    """
    Enable hardware acceleration for background OCR
    """
    ocr_curr: bool | None = False
    """
    Enable hardware acceleration for current OCR
    """


class Servers(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable or disable this MCP server
    """
    transport: Literal["stdio", "streamable_http", "sse", "websocket"]
    """
    Transport protocol for MCP communication
    """
    command: str | None = None
    """
    Command to start the MCP server (required for stdio transport)
    """
    args: list[str] | None = []
    """
    Arguments to pass to the command (used with stdio transport)
    """
    url: AnyUrl | None = None
    """
    URL endpoint for HTTP-based transports (required for streamable_http, sse, websocket)
    """
    headers: dict[constr(pattern=r"^.+$"), str] | None = {}
    """
    Custom HTTP headers for authentication and configuration
    """
    env: dict[constr(pattern=r"^.+$"), str] | None = {}
    """
    Environment variables for the MCP server process (used with stdio transport)
    """
    cwd: str | None = None
    """
    Working directory for the MCP server process (used with stdio transport)
    """
    timeout: float | None = Field(30, ge=1.0, le=300.0)
    """
    Connection timeout in seconds
    """


class Mcp(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable Model Context Protocol integration
    """
    servers: dict[constr(pattern=r"^[a-zA-Z][a-zA-Z0-9_-]*$"), Servers] | None = Field(
        {}, validate_default=True
    )
    """
    MCP server configurations indexed by server name
    """


class Google(BaseConfigModel):
    credentials_file: SecretStr | None = "google_credentials.json"
    """
    Path to Google credentials JSON file (sensitive; prefer .env)
    """


class Jira(BaseConfigModel):
    activate: bool | None = False
    """
    Enable Jira integration
    """
    api_token: SecretStr | None = ""
    """
    Jira API token (sensitive; prefer .env)
    """
    username: str | None = ""
    """
    Jira username
    """
    instance_url: AnyUrl | None = "https://jira.atlassian.net/"
    """
    Jira instance URL
    """


class Openrecall(BaseConfigModel):
    activate: bool | None = False
    """
    Enable OpenRecall integration
    """


class BraveSearch(BaseConfigModel):
    activate: bool | None = False
    """
    Enable Brave Search integration
    """
    api_key: SecretStr | None = ""
    """
    Brave Search API key (sensitive; prefer .env)
    """


class Github(BaseConfigModel):
    activate: bool | None = False
    """
    Enable GitHub integration
    """
    app_id: str | None = ""
    """
    GitHub App ID
    """
    app_private_key: SecretStr | None = ""
    """
    GitHub App private key (sensitive; prefer .env)
    """
    repository: str | None = ""
    """
    GitHub repository
    """


class Slack(BaseConfigModel):
    activate: bool | None = False
    """
    Enable Slack integration
    """
    user_token: SecretStr | None = ""
    """
    Slack user token (sensitive; prefer .env)
    """


class Gmail(BaseConfigModel):
    activate: bool | None = False
    """
    Enable Gmail integration
    """


class Gcalendar(BaseConfigModel):
    activate: bool | None = False
    """
    Enable Google Calendar integration
    """


class Plugins(BaseConfigModel):
    google: Google | None = None
    jira: Jira | None = None
    openrecall: Openrecall | None = None
    brave_search: BraveSearch | None = None
    github: Github | None = None
    slack: Slack | None = None
    gmail: Gmail | None = None
    gcalendar: Gcalendar | None = None


class Config(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable config service
    """


class MeshSharing(BaseConfigModel):
    share: bool | None = False
    """
    Whether to share this service with the network
    """
    max_concurrent: int | None = Field(10, ge=0)
    """
    Maximum concurrent remote calls
    """
    allowed_peers: list[str] | None = None
    """
    Specific stable mesh peer IDs allowed to call this shared service. Null allows any authenticated peer.
    """
    prefer: Literal["local", "network", "network_only", "local_only"] | None = "local"
    """
    Routing preference
    """
    fallback: Literal["local", "network", "error", "none"] | None = "local"
    """
    Fallback strategy
    """
    min_version: str | None = None
    """
    Minimum compatible remote service version required when routing to this service.
    """
    required_capabilities: list[str] | None = []
    """
    Remote service capabilities required before this service may be selected as a mesh provider.
    """
    require_explicit_selector: bool | None = False
    """
    Require callers to provide an explicit mesh peer/provider/resource selector before this service may route remotely.
    """
    unshared_feature_ids: list[str] | None = []
    """
    Subtractive stable feature IDs excluded from sharing; empty means no exclusions so all external-or-both features remain shared. Unknown or stale IDs are retained.
    """
    unshared_method_ids: list[str] | None = []
    """
    Subtractive canonical full bus topics excluded from sharing; empty means no exclusions so all external-or-both methods remain shared. Unknown or stale IDs are retained.
    """


class MeshRouting(BaseConfigModel):
    prefer: Literal["local", "network", "network_only", "local_only"] | None = "local"
    """
    Routing preference for selecting local or network providers.
    """
    fallback: Literal["local", "network", "error", "none"] | None = "local"
    """
    Fallback strategy when the preferred provider path is unavailable.
    """
    allowed_provider_peer_ids: list[str] | None = None
    """
    Stable provider peer IDs eligible for outbound routing. Null means any otherwise-eligible provider, an empty array denies network providers, and populated arrays allow only listed stable IDs. Never grants inbound authority.
    """
    min_version: str | None = None
    """
    Minimum compatible provider service version required for outbound routing.
    """
    required_provider_feature_ids: list[str] | None = []
    """
    All-of stable feature IDs that a recipient-visible callable provider must expose before it is eligible for outbound routing.
    """
    required_provider_capability_tags: list[str] | None = []
    """
    All-of provider metadata capability tags required for outbound routing. These tags are separate from feature IDs and never grant authority.
    """
    require_explicit_selector: bool | None = False
    """
    Require callers to provide an explicit mesh peer/provider/resource selector before this service may route remotely.
    """


class ToolingApprovalPolicyRule(BaseConfigModel):
    rule_id: str
    """
    Stable operator-defined rule identifier
    """
    share: bool | None = True
    """
    Whether matching tools are shared/discoverable/executable
    """
    approval_mode: (
        Literal[
            "deny_all",
            "ask_each_time",
            "allow_once",
            "allow_until_expiry",
            "approve_all_for_session",
            "approve_all_for_peer",
            "approve_all_local_safe",
            "dry_run_only",
        ]
        | None
    ) = "ask_each_time"
    tool_name: str | None = None
    global_tool_id: str | None = None
    execution_location: Literal["local", "remote"] | None = None
    source_type: Literal["core", "plugin", "mcp", "toolkit", "unknown"] | None = None
    toolkit_name: str | None = None
    safety_class: Literal["standard", "sensitive", "dangerous"] | None = None
    operation_class: (
        Literal["read", "write", "external", "admin", "hardware", "data-egress"] | None
    ) = None
    resource_namespace: str | None = None
    hardware_target: str | None = None
    data_scope: str | None = None
    caller_peer_id: str | None = None
    caller_principal_id: str | None = None
    caller_device_id: str | None = None
    provider_peer_id: str | None = None
    provider_service_instance_id: str | None = None
    route_privacy_class: str | None = None
    token_ttl_seconds: int | None = Field(300, ge=1)
    """
    Approval token lifetime for this rule
    """


class Tts(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable TTS service
    """
    provider: Literal["piper", "pockettts"] | None = "piper"
    """
    Text-to-speech provider
    """
    fallback_provider: Literal["piper", "pockettts"] | None = None
    """
    Explicit fallback provider used only when configured
    """
    default_voice_id: str | None = None
    """
    Default logical voice for this device
    """
    mesh_sharing: MeshSharing | None = None
    mesh_routing: MeshRouting | None = None
    hardware_acceleration: bool | None = False
    """
    Enable hardware acceleration for TTS
    """
    providers: Providers | None = Field({}, validate_default=True)
    """
    Provider-specific text-to-speech settings
    """
    voice_registry: VoiceRegistry | None = Field({}, validate_default=True)
    """
    Logical voice registry settings
    """
    model_file_path: str | None = "voice_models/en_US-lessac-medium.onnx"
    """
    Path to the TTS model file
    """
    model_config_file_path: str | None = "voice_models/en_US-lessac-medium.onnx.txt"
    """
    Path to the TTS model configuration file
    """
    model_sample_rate: int | None = Field(22050, ge=8000, le=48000)
    """
    Sample rate for TTS output
    """
    piper_path: str | None = ""
    """
    Path to Piper TTS executable
    """


class Coordinator(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable STT coordinator
    """
    mesh_sharing: MeshSharing | None = None
    mesh_routing: MeshRouting | None = None
    session_timeout_s: float | None = Field(30.0, ge=1.0, le=300.0)
    """
    Session timeout in seconds
    """
    multi_turn_enabled: bool | None = False
    """
    Enable multi-turn conversation
    """
    pause_tts_on_listen: bool | None = True
    """
    Pause TTS when listening for speech
    """
    ambient_transcription: AmbientTranscription | None = None
    """
    Ambient transcription settings
    """
    audio_input: AudioInput | None = None
    """
    Audio input device settings
    """


class Wakeword(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable wake word detection
    """
    mesh_sharing: MeshSharing | None = None
    mesh_routing: MeshRouting | None = None
    backend: Literal["oww", "pvp"] | None = "oww"
    """
    Wake word backend: 'oww' (OpenWakeWord) or 'pvp' (Porcupine)
    """
    model_path: str | None = None
    """
    Path to wake word model file
    """
    threshold: float | None = Field(0.5, ge=0.0, le=1.0)
    """
    Wake word detection threshold
    """
    inference_framework: Literal["onnx", "tflite"] | None = "onnx"
    """
    Inference framework for wake word detection
    """


class Transcription(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable transcription service
    """
    mesh_sharing: MeshSharing | None = None
    mesh_routing: MeshRouting | None = None
    vad_enabled: bool | None = True
    """
    Enable voice activity detection
    """
    vad_threshold: float | None = Field(0.5, ge=0.0, le=1.0)
    """
    VAD threshold
    """
    silence_duration_ms: int | None = Field(900, ge=100, le=5000)
    """
    Silence duration in milliseconds before stopping
    """
    max_speech_duration_s: int | None = Field(30, ge=5, le=300)
    """
    Maximum speech duration in seconds
    """
    realtime_model: RealtimeModel | None = None
    """
    Realtime transcription model settings
    """
    accurate_model: AccurateModel | None = None
    """
    Accurate transcription model settings
    """


class Stt(BaseConfigModel):
    language: str | None = Field(
        "en",
        max_length=255,
        pattern="^(?:|[A-Za-z]{2,8}(?:[-_][A-Za-z0-9]{1,8})*|[IiXx](?:[-_][A-Za-z0-9]{1,8})+)$",
    )
    """
    BCP 47 language tag for speech recognition (empty for auto-detect)
    """
    coordinator: Coordinator | None = None
    """
    STT coordinator service settings
    """
    wakeword: Wakeword | None = None
    """
    Wake word detection service settings
    """
    transcription: Transcription | None = None
    """
    Transcription service settings
    """
    hardware_acceleration: bool | None = False
    """
    Enable hardware acceleration for STT
    """


class Orchestrator(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable orchestrator service
    """
    mesh_sharing: MeshSharing | None = None
    mesh_routing: MeshRouting | None = None
    hardware_acceleration: bool | None = False
    """
    Enable hardware acceleration for LLM
    """
    llm: Llm | None = None
    """
    LLM provider configuration
    """
    routing: Routing | None = None
    """
    Separate dispatch and inference routing defaults for orchestrator requests
    """


class Db(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable database service
    """
    mesh_sharing: MeshSharing | None = None
    mesh_routing: MeshRouting | None = None
    embeddings: Embeddings | None = None
    """
    Embeddings configuration
    """


class Scheduler(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable scheduler service
    """
    mesh_sharing: MeshSharing | None = None
    mesh_routing: MeshRouting | None = None


class ToolingApprovalPolicy(BaseConfigModel):
    default_share: bool | None = True
    """
    Whether tools are discoverable/executable unless a more specific rule overrides this
    """
    default_approval_mode: (
        Literal[
            "deny_all",
            "ask_each_time",
            "allow_once",
            "allow_until_expiry",
            "approve_all_for_session",
            "approve_all_for_peer",
            "approve_all_local_safe",
            "dry_run_only",
        ]
        | None
    ) = "approve_all_local_safe"
    """
    Default approval behavior when no scoped rule matches
    """
    policy_mode: (
        Literal["enforce", "dry_run_only", "deny_all", "unrestricted_except_blocked"] | None
    ) = "enforce"
    """
    Global Tooling policy mode. unrestricted_except_blocked bypasses approval prompts only for non-blocked tools and remains admin/operator controlled.
    """
    default_token_ttl_seconds: int | None = Field(300, ge=1)
    """
    Default lifetime for approval tokens issued by matching rules
    """
    rules: list[ToolingApprovalPolicyRule] | None = Field([], validate_default=True)
    """
    First-match scoped sharing and approval rules. Unset fields act as wildcards.
    """


class Tooling(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable tooling service
    """
    mesh_sharing: MeshSharing | None = None
    mesh_routing: MeshRouting | None = None
    approval_policy: ToolingApprovalPolicy | None = None
    hardware_acceleration: HardwareAcceleration | None = None
    """
    Hardware acceleration for OCR features
    """
    mcp: Mcp | None = None
    """
    Model Context Protocol integration
    """
    plugins: Plugins | None = None
    """
    Plugin integrations
    """


class Services(BaseConfigModel):
    gateway: Gateway | None = None
    """
    HTTP Gateway configuration for REST API, WebRTC, and mesh networking
    """
    auth: Auth | None = None
    """
    Authentication and authorization service
    """
    tts: Tts | None = None
    """
    Text-to-speech service configuration
    """
    stt: Stt | None = None
    """
    Speech-to-text services configuration
    """
    orchestrator: Orchestrator | None = None
    """
    Orchestrator service (LLM coordination, tool calls)
    """
    db: Db | None = None
    """
    Database service configuration
    """
    tooling: Tooling | None = None
    """
    Tooling service (plugins, MCP, tools)
    """
    scheduler: Scheduler | None = None
    """
    Scheduler service for cron jobs and scheduled tasks
    """
    config: Config | None = None
    """
    Config service settings
    """


class Model(BaseConfigModel):
    ui: Ui | None = None
    """
    User interface settings
    """
    system: System | None = None
    """
    System-wide settings
    """
    services: Services | None = None
    """
    Per-service configuration sections
    """
