# generated by datamodel-codegen:
#   filename:  config_schema.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import AnyUrl, Field, SecretStr, constr

from app.shared.config.models_base import BaseConfigModel


class Ui(BaseConfigModel):
    activate: bool | None = False
    """
    Enable graphical user interface
    """
    dark_mode: bool | None = False
    """
    Enable dark mode theme
    """
    debug: bool | None = False
    """
    Enable debug mode for verbose logging
    """


class System(BaseConfigModel):
    models_dir: str | None = "voice_models/"
    """
    Base directory for voice/model files
    """


class Cors(BaseConfigModel):
    origins: list[str] | None = ["*"]
    """
    Allowed CORS origins
    """
    allow_credentials: bool | None = True
    """
    Allow credentials in CORS requests
    """


class Api(BaseConfigModel):
    host: str | None = "0.0.0.0"
    """
    Host address to bind the gateway
    """
    port: int | None = Field(8000, ge=1, le=65535)
    """
    Port number for the gateway
    """
    request_timeout_s: float | None = Field(30.0, ge=1.0, le=300.0)
    """
    Request timeout in seconds
    """
    cors: Cors | None = None
    """
    CORS configuration
    """
    token_secret: SecretStr | None = ""
    """
    Secret for JWT signing and mesh inbound token encryption. Prefer AURORA_TOKEN_SECRET in .env.
    """


class MeshNetwork(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable P2P mesh networking
    """
    node_name: str | None = ""
    """
    Human-readable name for this node in the mesh
    """
    version_policy: Literal["exact", "compatible", "any"] | None = "compatible"
    """
    How strictly to enforce version matching
    """
    peer_selection: Literal["lowest_latency", "round_robin", "random"] | None = "lowest_latency"
    """
    Strategy for choosing among multiple peers
    """
    ping_interval_s: float | None = Field(30.0, ge=1.0)
    """
    How often to measure peer latency (seconds)
    """
    registry_announce_interval_s: float | None = Field(60.0, ge=1.0)
    """
    How often to re-announce manifest (seconds)
    """
    stale_peer_timeout_s: float | None = Field(120.0, ge=1.0)
    """
    Mark peer stale after this many seconds without pong
    """
    remote_timeout_s: float | None = Field(30.0, ge=1.0)
    """
    Timeout for remote bus publish calls (seconds)
    """


class Webrtc(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable WebRTC transport
    """
    strategy: str | None = "mqtt"
    """
    Signaling strategy
    """
    app_id: str | None = "aurora"
    """
    Application ID for signaling
    """
    room: str | None = "default"
    """
    Signaling room name. Auto-generated on first run if set to 'default' or empty.
    """
    password: SecretStr | None = ""
    """
    Room password for signaling encryption. Auto-generated on first run if empty. Prefer AURORA_WEBRTC_PASSWORD in .env.
    """
    encrypt_signaling: bool | None = True
    """
    Enable signaling encryption
    """
    enable_app_layer_e2ee: bool | None = False
    """
    When true, all WebRTC DataChannel JSON messages are sealed as binary AEAD payloads with the room data key. Peers with mismatched settings do not fall back to plaintext.
    """
    stun_servers: list[str] | None = ["stun:stun.l.google.com:19302"]
    """
    STUN server URLs for NAT traversal
    """
    turn_servers: list[Any] | None = []
    """
    TURN server configurations for relay
    """


class SignalingMqtt(BaseConfigModel):
    brokers: list[str] | None = [
        "wss://broker.emqx.io:8084/mqtt",
        "wss://test.mosquitto.org:8081/mqtt",
    ]
    """
    MQTT broker WebSocket URLs
    """
    topic_root: str | None = "aurora"
    """
    Root MQTT topic for signaling
    """


class Gateway(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable HTTP Gateway for REST API access
    """
    api: Api | None = None
    """
    REST API settings
    """
    mesh_network: MeshNetwork | None = None
    """
    P2P mesh networking configuration
    """
    webrtc: Webrtc | None = None
    """
    WebRTC transport configuration
    """
    signaling_mqtt: SignalingMqtt | None = None
    """
    MQTT signaling configuration for WebRTC
    """


class Auth(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable authentication service
    """
    api_keys: list[SecretStr] | None = []
    """
    List of valid API keys (sensitive; prefer AURORA_GATEWAY_API_KEYS in .env)
    """
    token_expiry_days: int | None = Field(365, ge=1)
    """
    Default token expiry in days
    """
    session_token_expiry_hours: int | None = Field(24, ge=1)
    """
    Session token expiry in hours (for login)
    """
    pairing_code_expiry_minutes: int | None = Field(5, ge=1)
    """
    Pairing code expiry in minutes
    """
    pairing_max_attempts_per_ip: int | None = Field(5, ge=1)
    """
    Max pairing attempts per IP before rate limiting
    """
    default_pairing_permissions: list[str] | None = []
    """
    Default permissions assigned to new devices during pairing
    """
    webrtc_auth_timeout_seconds: float | None = Field(10.0, ge=1.0)
    """
    Timeout in seconds for WebRTC peer authentication
    """
    webrtc_pairing_timeout_seconds: float | None = Field(300.0, ge=10.0)
    """
    Timeout in seconds for peers in the pairing flow (awaiting human approval)
    """
    audit_enabled: bool | None = True
    """
    Enable audit logging of security events
    """
    audit_retention_days: int | None = Field(90, ge=1)
    """
    Audit log retention period in days
    """


class AmbientTranscription(BaseConfigModel):
    enable: bool | None = False
    """
    Enable ambient transcription
    """
    chunk_duration: float | None = Field(3.0, ge=0.5, le=60.0)
    """
    Duration in seconds of audio chunks to process
    """
    storage_path: str | None = "ambient_logs/"
    """
    Directory path for file storage
    """
    filter_short_transcriptions: bool | None = True
    """
    Filter out short transcriptions to reduce noise
    """
    min_transcription_length: int | None = Field(10, ge=0)
    """
    Minimum character length for transcriptions when filtering
    """


class AudioInput(BaseConfigModel):
    device_index: int | None = None
    """
    Audio input device index (null for default)
    """
    sample_rate: Literal[8000, 16000, 22050, 44100, 48000] | None = 16000
    """
    Audio sample rate in Hz
    """
    channels: int | None = Field(1, ge=1, le=2)
    """
    Number of audio channels
    """
    chunk_size: int | None = Field(1024, ge=128, le=8192)
    """
    Audio chunk size in frames
    """
    format: Literal["int16", "int32", "float32"] | None = "int16"
    """
    Audio sample format
    """


class RealtimeModel(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable realtime transcription model
    """
    model_size: Literal["tiny", "base", "small", "medium", "large"] | None = "tiny"
    """
    Whisper model size for realtime transcription
    """
    device: Literal["cpu", "cuda", "auto"] | None = "cpu"
    """
    Device for realtime model
    """
    compute_type: Literal["int8", "int16", "float16", "float32"] | None = "int8"
    """
    Compute type for realtime model
    """


class AccurateModel(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable accurate transcription model
    """
    model_size: Literal["tiny", "base", "small", "medium", "large"] | None = "base"
    """
    Whisper model size for accurate transcription
    """
    device: Literal["cpu", "cuda", "auto"] | None = "cpu"
    """
    Device for accurate model
    """
    compute_type: Literal["int8", "int16", "float16", "float32"] | None = "int8"
    """
    Compute type for accurate model
    """


class Options(BaseConfigModel):
    api_key: SecretStr | None = ""
    """
    OpenAI API key (sensitive; prefer OPENAI_API_KEY in .env)
    """
    model: str | None = "gpt-4o"
    """
    OpenAI model to use
    """
    temperature: float | None = Field(0.7, ge=0.0, le=2.0)
    """
    Sampling temperature for OpenAI models
    """
    max_tokens: int | None = Field(512, ge=1, le=4096)
    """
    Maximum tokens for OpenAI responses
    """


class Openai(BaseConfigModel):
    options: Options | None = None


class Options1(BaseConfigModel):
    endpoint_url: str | None = ""
    """
    HuggingFace endpoint URL
    """
    model: str | None = ""
    """
    HuggingFace model name
    """
    access_token: SecretStr | None = ""
    """
    HuggingFace access token (sensitive; prefer .env)
    """
    temperature: float | None = Field(0.7, ge=0.0, le=2.0)
    """
    Sampling temperature
    """
    max_tokens: int | None = Field(512, ge=1, le=4096)
    """
    Maximum tokens for responses
    """


class HuggingfaceEndpoint(BaseConfigModel):
    options: Options1 | None = None


class ThirdParty(BaseConfigModel):
    openai: Openai | None = None
    huggingface_endpoint: HuggingfaceEndpoint | None = None


class Options2(BaseConfigModel):
    model: str | None = "microsoft/DialoGPT-medium"
    """
    HuggingFace model name for local pipeline
    """
    temperature: float | None = Field(0.7, ge=0.0, le=2.0)
    """
    Sampling temperature
    """
    max_tokens: int | None = Field(None, ge=1)
    """
    Maximum tokens for responses
    """
    torch_dtype: Literal["auto", "float32", "float16", "bfloat16"] | None = "auto"
    """
    PyTorch data type
    """
    device: Literal["cpu", "cuda", "auto"] | None = None
    """
    Device to run the model on
    """
    pipeline_kwargs: dict[str, Any] | None = None
    """
    Additional pipeline keyword arguments
    """
    model_kwargs: dict[str, Any] | None = None
    """
    Additional model keyword arguments
    """


class HuggingfacePipeline(BaseConfigModel):
    options: Options2 | None = None


class Options3(BaseConfigModel):
    model_path: str | None = ""
    """
    Path to the GGUF model file
    """
    temperature: float | None = Field(1.0, ge=0.0, le=2.0)
    """
    Sampling temperature for Llama.cpp
    """
    max_tokens: int | None = Field(512, ge=1, le=4096)
    """
    Maximum tokens for responses
    """
    n_ctx: int | None = Field(2048, ge=512, le=32768)
    """
    Context window size
    """
    n_gpu_layers: int | None = Field(0, ge=0, le=100)
    """
    Number of layers to offload to GPU
    """
    n_batch: int | None = Field(1000, ge=1, le=2048)
    """
    Batch size for processing
    """
    top_p: float | None = Field(0.95, ge=0.0, le=1.0)
    """
    Top-p sampling parameter
    """
    top_k: int | None = Field(64, ge=1, le=200)
    """
    Top-k sampling parameter
    """
    repeat_penalty: float | None = Field(1.0, ge=0.1, le=2.0)
    """
    Repetition penalty
    """
    min_p: float | None = Field(0.0, ge=0.0, le=1.0)
    """
    Minimum probability threshold
    """
    chat_format: (
        Literal["chatml", "chatml-function-calling", "llama-2", "alpaca", "vicuna"] | None
    ) = "chatml-function-calling"
    """
    Chat format template to use
    """


class LlamaCpp(BaseConfigModel):
    options: Options3 | None = None


class Local(BaseConfigModel):
    huggingface_pipeline: HuggingfacePipeline | None = None
    llama_cpp: LlamaCpp | None = None


class Llm(BaseConfigModel):
    provider: (
        Literal["openai", "huggingface_endpoint", "huggingface_pipeline", "llama_cpp"] | None
    ) = "openai"
    """
    LLM provider to use
    """
    third_party: ThirdParty | None = None
    """
    Third-party LLM provider options
    """
    local: Local | None = None
    """
    Local LLM provider options
    """


class Embeddings(BaseConfigModel):
    use_local: bool | None = True
    """
    Use local embeddings model instead of API
    """


class HardwareAcceleration(BaseConfigModel):
    ocr_bg: bool | None = False
    """
    Enable hardware acceleration for background OCR
    """
    ocr_curr: bool | None = False
    """
    Enable hardware acceleration for current OCR
    """


class Servers(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable or disable this MCP server
    """
    transport: Literal["stdio", "streamable_http", "sse", "websocket"]
    """
    Transport protocol for MCP communication
    """
    command: str | None = None
    """
    Command to start the MCP server (required for stdio transport)
    """
    args: list[str] | None = []
    """
    Arguments to pass to the command (used with stdio transport)
    """
    url: AnyUrl | None = None
    """
    URL endpoint for HTTP-based transports (required for streamable_http, sse, websocket)
    """
    headers: dict[constr(pattern=r"^.+$"), str] | None = {}
    """
    Custom HTTP headers for authentication and configuration
    """
    env: dict[constr(pattern=r"^.+$"), str] | None = {}
    """
    Environment variables for the MCP server process (used with stdio transport)
    """
    cwd: str | None = None
    """
    Working directory for the MCP server process (used with stdio transport)
    """
    timeout: float | None = Field(30, ge=1.0, le=300.0)
    """
    Connection timeout in seconds
    """


class Mcp(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable Model Context Protocol integration
    """
    servers: dict[constr(pattern=r"^[a-zA-Z][a-zA-Z0-9_-]*$"), Servers] | None = Field(
        {}, validate_default=True
    )
    """
    MCP server configurations indexed by server name
    """


class Google(BaseConfigModel):
    credentials_file: SecretStr | None = "google_credentials.json"
    """
    Path to Google credentials JSON file (sensitive; prefer .env)
    """


class Jira(BaseConfigModel):
    activate: bool | None = False
    """
    Enable Jira integration
    """
    api_token: SecretStr | None = ""
    """
    Jira API token (sensitive; prefer .env)
    """
    username: str | None = ""
    """
    Jira username
    """
    instance_url: AnyUrl | None = "https://jira.atlassian.net/"
    """
    Jira instance URL
    """


class Openrecall(BaseConfigModel):
    activate: bool | None = False
    """
    Enable OpenRecall integration
    """


class BraveSearch(BaseConfigModel):
    activate: bool | None = False
    """
    Enable Brave Search integration
    """
    api_key: SecretStr | None = ""
    """
    Brave Search API key (sensitive; prefer .env)
    """


class Github(BaseConfigModel):
    activate: bool | None = False
    """
    Enable GitHub integration
    """
    app_id: str | None = ""
    """
    GitHub App ID
    """
    app_private_key: SecretStr | None = ""
    """
    GitHub App private key (sensitive; prefer .env)
    """
    repository: str | None = ""
    """
    GitHub repository
    """


class Slack(BaseConfigModel):
    activate: bool | None = False
    """
    Enable Slack integration
    """
    user_token: SecretStr | None = ""
    """
    Slack user token (sensitive; prefer .env)
    """


class Gmail(BaseConfigModel):
    activate: bool | None = False
    """
    Enable Gmail integration
    """


class Gcalendar(BaseConfigModel):
    activate: bool | None = False
    """
    Enable Google Calendar integration
    """


class Plugins(BaseConfigModel):
    google: Google | None = None
    jira: Jira | None = None
    openrecall: Openrecall | None = None
    brave_search: BraveSearch | None = None
    github: Github | None = None
    slack: Slack | None = None
    gmail: Gmail | None = None
    gcalendar: Gcalendar | None = None


class Config(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable config service
    """


class MeshSharing(BaseConfigModel):
    share: bool | None = False
    """
    Whether to share this service with the network
    """
    max_concurrent: int | None = Field(10, ge=0)
    """
    Maximum concurrent remote calls
    """
    allowed_peers: list[str] | None = None
    """
    Specific stable mesh peer IDs allowed to call this shared service. Null allows any authenticated peer.
    """
    prefer: Literal["local", "network", "network_only", "local_only"] | None = "local"
    """
    Routing preference
    """
    fallback: Literal["local", "network", "error", "none"] | None = "local"
    """
    Fallback strategy
    """
    min_version: str | None = None
    """
    Minimum compatible remote service version required when routing to this service.
    """
    required_capabilities: list[str] | None = []
    """
    Remote service capabilities required before this service may be selected as a mesh provider.
    """


class Tts(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable TTS service
    """
    mesh_sharing: MeshSharing | None = None
    hardware_acceleration: bool | None = False
    """
    Enable hardware acceleration for TTS
    """
    model_file_path: str | None = "voice_models/en_US-lessac-medium.onnx"
    """
    Path to the TTS model file
    """
    model_config_file_path: str | None = "voice_models/en_US-lessac-medium.onnx.txt"
    """
    Path to the TTS model configuration file
    """
    model_sample_rate: int | None = Field(22050, ge=8000, le=48000)
    """
    Sample rate for TTS output
    """
    piper_path: str | None = ""
    """
    Path to Piper TTS executable
    """


class Coordinator(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable STT coordinator
    """
    mesh_sharing: MeshSharing | None = None
    session_timeout_s: float | None = Field(10.0, ge=1.0, le=300.0)
    """
    Session timeout in seconds
    """
    multi_turn_enabled: bool | None = False
    """
    Enable multi-turn conversation
    """
    pause_tts_on_listen: bool | None = True
    """
    Pause TTS when listening for speech
    """
    ambient_transcription: AmbientTranscription | None = None
    """
    Ambient transcription settings
    """
    audio_input: AudioInput | None = None
    """
    Audio input device settings
    """


class Wakeword(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable wake word detection
    """
    mesh_sharing: MeshSharing | None = None
    backend: Literal["oww", "pvp"] | None = "oww"
    """
    Wake word backend: 'oww' (OpenWakeWord) or 'pvp' (Porcupine)
    """
    model_path: str | None = None
    """
    Path to wake word model file
    """
    threshold: float | None = Field(0.5, ge=0.0, le=1.0)
    """
    Wake word detection threshold
    """
    inference_framework: Literal["onnx", "tflite"] | None = "onnx"
    """
    Inference framework for wake word detection
    """


class Transcription(BaseConfigModel):
    enabled: bool | None = False
    """
    Enable transcription service
    """
    mesh_sharing: MeshSharing | None = None
    vad_enabled: bool | None = True
    """
    Enable voice activity detection
    """
    vad_threshold: float | None = Field(0.5, ge=0.0, le=1.0)
    """
    VAD threshold
    """
    silence_duration_ms: int | None = Field(900, ge=100, le=5000)
    """
    Silence duration in milliseconds before stopping
    """
    max_speech_duration_s: int | None = Field(30, ge=5, le=300)
    """
    Maximum speech duration in seconds
    """
    realtime_model: RealtimeModel | None = None
    """
    Realtime transcription model settings
    """
    accurate_model: AccurateModel | None = None
    """
    Accurate transcription model settings
    """


class Stt(BaseConfigModel):
    language: Literal["", "en", "pt", "es", "fr", "de", "it", "ja", "ko", "zh"] | None = "en"
    """
    Language for speech recognition (empty for auto-detect)
    """
    coordinator: Coordinator | None = None
    """
    STT coordinator service settings
    """
    wakeword: Wakeword | None = None
    """
    Wake word detection service settings
    """
    transcription: Transcription | None = None
    """
    Transcription service settings
    """
    hardware_acceleration: bool | None = False
    """
    Enable hardware acceleration for STT
    """


class Orchestrator(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable orchestrator service
    """
    mesh_sharing: MeshSharing | None = None
    hardware_acceleration: bool | None = False
    """
    Enable hardware acceleration for LLM
    """
    llm: Llm | None = None
    """
    LLM provider configuration
    """


class Db(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable database service
    """
    mesh_sharing: MeshSharing | None = None
    embeddings: Embeddings | None = None
    """
    Embeddings configuration
    """


class Tooling(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable tooling service
    """
    mesh_sharing: MeshSharing | None = None
    hardware_acceleration: HardwareAcceleration | None = None
    """
    Hardware acceleration for OCR features
    """
    mcp: Mcp | None = None
    """
    Model Context Protocol integration
    """
    plugins: Plugins | None = None
    """
    Plugin integrations
    """


class Scheduler(BaseConfigModel):
    enabled: bool | None = True
    """
    Enable scheduler service
    """
    mesh_sharing: MeshSharing | None = None


class Services(BaseConfigModel):
    gateway: Gateway | None = None
    """
    HTTP Gateway configuration for REST API, WebRTC, and mesh networking
    """
    auth: Auth | None = None
    """
    Authentication and authorization service
    """
    tts: Tts | None = None
    """
    Text-to-speech service configuration
    """
    stt: Stt | None = None
    """
    Speech-to-text services configuration
    """
    orchestrator: Orchestrator | None = None
    """
    Orchestrator service (LLM coordination, tool calls)
    """
    db: Db | None = None
    """
    Database service configuration
    """
    tooling: Tooling | None = None
    """
    Tooling service (plugins, MCP, tools)
    """
    scheduler: Scheduler | None = None
    """
    Scheduler service for cron jobs and scheduled tasks
    """
    config: Config | None = None
    """
    Config service settings
    """


class Model(BaseConfigModel):
    ui: Ui | None = None
    """
    User interface settings
    """
    system: System | None = None
    """
    System-wide settings
    """
    services: Services | None = None
    """
    Per-service configuration sections
    """
