#!/usr/bin/env node

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

const basePath = resolve(requiredOption('--base'))
const summaryPath = resolve(requiredOption('--summary'))
const outputPath = resolve(requiredOption('--output'))
const base = readFileSync(basePath, 'utf8').trim()
const rawSummary = readFileSync(summaryPath, 'utf8').trim()
const summaryBytes = Buffer.byteLength(rawSummary, 'utf8')

if (summaryBytes < 80) throw new Error('Copilot release summary is too short')
if (summaryBytes > 12_000) throw new Error('Copilot release summary exceeds 12,000 bytes')
if (/```|<!--|-->|https?:\/\/|www\.|\]\(|<\/?[A-Za-z!/]/u.test(rawSummary)) {
  throw new Error('Copilot release summary contains forbidden links, HTML, markers, or code fences')
}
if (/^#{1,6}\s/mu.test(rawSummary)) {
  throw new Error('Copilot release summary must not contain headings')
}
const bulletCount = [...rawSummary.matchAll(/^[-*]\s/gmu)].length
if (bulletCount < 6 || bulletCount > 10) {
  throw new Error('Copilot release summary must contain 6 to 10 Markdown bullets')
}
const firstBulletOffset = rawSummary.search(/^[-*]\s/mu)
const introduction = rawSummary.slice(0, firstBulletOffset).trim()
if (introduction.length < 40) {
  throw new Error('Copilot release summary must begin with an overview paragraph')
}

const aiSectionPattern = /\n?<!-- aurora:ai-summary:start -->[\s\S]*?<!-- aurora:ai-summary:end -->\n?/gu
const cleanBase = base.replace(aiSectionPattern, '\n').trim()
const changelogMarker = '<!-- aurora:full-changelog:start -->'
const changelogEndMarker = '<!-- aurora:full-changelog:end -->'
const changelogStartCount = cleanBase.split(changelogMarker).length - 1
const changelogEndCount = cleanBase.split(changelogEndMarker).length - 1
if (changelogStartCount !== 1 || changelogEndCount !== 1) {
  throw new Error('base release notes must contain exactly one complete changelog section')
}
const changelogOffset = cleanBase.indexOf(changelogMarker)

const safeSummary = rawSummary.replace(/@(?=[A-Za-z0-9-])/gu, '@\u200b')
const aiSection = [
  '<!-- aurora:ai-summary:start -->',
  '## AI-generated release overview',
  '',
  '> Generated by GitHub Copilot from the complete commit history. The semantic notes, manifest, checksums, and exhaustive changelog remain authoritative.',
  '',
  safeSummary,
  '<!-- aurora:ai-summary:end -->',
].join('\n')
const beforeChangelog = cleanBase.slice(0, changelogOffset).trimEnd()
const changelogSection = cleanBase.slice(changelogOffset).trimStart()
const finalNotes = `${beforeChangelog}\n\n${aiSection}\n\n${changelogSection}\n`

mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, finalNotes)
console.log(`Composed Copilot release summary (${summaryBytes} bytes)`)

function requiredOption(name) {
  const index = process.argv.indexOf(name)
  const value = index === -1 ? '' : process.argv[index + 1]?.trim() ?? ''
  if (!value) throw new Error(`${name} is required`)
  return value
}
