"""Generate deterministic Rust DTOs and descriptors from Aurora contract schemas."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import tempfile
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCHEMA_INPUT = REPO_ROOT / "packages/aurora-sdk/src/generated/backend-contracts.schema.json"
DEFAULT_CRATE_DIR = REPO_ROOT / "rust/crates/aurora-contracts"
DEFAULT_FIXTURE_OUTPUT = (
    REPO_ROOT / "tests/fixtures/local_speech/runtime/contracts/backend_contract_parse_vectors.json"
)
GENERATOR_FORMAT_VERSION = "aurora-rust-contract-codegen-v1"
GENERATED_HEADER = "// Generated by scripts/generate_rust_contracts.py. Do not edit by hand."


class GenerationError(ValueError):
    """Raised when normalized backend contracts cannot produce safe Rust output."""


def canonical_json(value: Any) -> str:
    """Return Aurora's deterministic JSON representation."""

    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def sha256_text(value: str) -> str:
    """Return the lowercase SHA-256 digest for UTF-8 text."""

    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def snake_case(value: str) -> str:
    """Convert a generated model name into a stable Rust module name."""

    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", value):
        raise GenerationError(f"unsafe generated model name: {value!r}")
    first = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", value)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", first).lower()


def rust_type_name(value: str) -> str:
    """Return typify's stable UpperCamelCase spelling for a model name."""

    return "".join(part.capitalize() for part in snake_case(value).split("_"))


def rust_string(value: str) -> str:
    """Render a Python string as a Rust string literal."""

    return json.dumps(value, ensure_ascii=False)


def rust_option(value: str | None) -> str:
    """Render an optional Rust string literal."""

    return "None" if value is None else f"Some({rust_string(value)})"


def rust_slice(values: Iterable[str]) -> str:
    """Render a static Rust string slice."""

    return "&[" + ", ".join(rust_string(value) for value in values) + "]"


def _deduplicated_schemas(contract_schema: Mapping[str, Any]) -> list[dict[str, Any]]:
    by_model: dict[str, dict[str, Any]] = {}
    for raw in contract_schema.get("schemas", []):
        if not isinstance(raw, dict):
            raise GenerationError("contract schemas must be objects")
        model_name = raw.get("model_name")
        schema_hash = raw.get("schema_hash")
        schema = raw.get("schema")
        if not isinstance(model_name, str) or not isinstance(schema_hash, str):
            raise GenerationError("contract schema identity is incomplete")
        if not isinstance(schema, dict):
            raise GenerationError(f"contract schema {model_name} is not an object")
        existing = by_model.get(model_name)
        if existing is not None and existing["schema_hash"] != schema_hash:
            raise GenerationError(f"model {model_name} has conflicting schema hashes")
        by_model.setdefault(model_name, raw)
    return sorted(by_model.values(), key=lambda item: item["model_name"])


def _render_models(contract_schema: Mapping[str, Any]) -> tuple[str, dict[str, str]]:
    lines = ["pub mod models {"]
    model_modules: dict[str, str] = {}
    for item in _deduplicated_schemas(contract_schema):
        model_name = item["model_name"]
        module_name = snake_case(model_name)
        rust_name = rust_type_name(model_name)
        model_modules[model_name] = module_name
        lines.extend(
            [
                f"    pub mod {module_name} {{",
                f'        typify::import_types!(schema = "schema/{module_name}.json");',
                "    }",
                f"    pub use {module_name}::{rust_name};",
            ]
        )
    lines.append("}")
    return "\n".join(lines), model_modules


def _render_schema_descriptors(
    contract_schema: Mapping[str, Any], model_modules: Mapping[str, str]
) -> str:
    lines = ["pub static SCHEMA_DESCRIPTORS: &[SchemaDescriptor] = &["]
    for item in contract_schema["schemas"]:
        module_name = model_modules[item["model_name"]]
        lines.extend(
            [
                "    SchemaDescriptor {",
                f"        schema_id: {rust_string(item['schema_id'])},",
                f"        method_id: {rust_string(item['method_id'])},",
                f"        direction: {rust_string(item['direction'])},",
                f"        model_name: {rust_string(item['model_name'])},",
                f"        schema_hash: {rust_string(item['schema_hash'])},",
                f'        schema_json: include_str!("../schema/{module_name}.json"),',
                "    },",
            ]
        )
    lines.append("];")
    return "\n".join(lines)


def _render_method_descriptors(contract_schema: Mapping[str, Any]) -> str:
    lines = ["pub static METHOD_DESCRIPTORS: &[MethodDescriptor] = &["]
    for item in contract_schema["method_descriptors"]:
        streaming = item["streaming"]
        lines.extend(
            [
                "    MethodDescriptor {",
                f"        method_id: {rust_string(item['method_id'])},",
                f"        bus_topic: {rust_string(item['bus_topic'])},",
                f"        module: {rust_string(item['module'])},",
                f"        name: {rust_string(item['name'])},",
                f"        method_type: {rust_string(item['method_type'])},",
                f"        exposure: {rust_string(item['exposure'])},",
                f"        route_path: {rust_string(item['route_path'])},",
                f"        route_kind: {rust_string(item['route_kind'])},",
                f"        required_permissions: {rust_slice(item['required_perms'])},",
                f"        callable_feature_ids: {rust_slice(item['callable_feature_ids'])},",
                f"        input_schema_id: {rust_string(item['input_schema_id'])},",
                f"        output_schema_id: {rust_string(item['output_schema_id'])},",
                "        streaming: StreamingDescriptor {",
                f"            rpc_kind: {rust_string(streaming['rpc_kind'])},",
                f"            request_stream: {str(streaming['request_stream']).lower()},",
                f"            response_stream: {str(streaming['response_stream']).lower()},",
                "            ordered_command_group: "
                f"{rust_option(streaming['ordered_command_group'])},",
                f"            event_topic: {rust_option(streaming['event_topic'])},",
                "        },",
                "    },",
            ]
        )
    lines.append("];")
    return "\n".join(lines)


def _render_event_descriptors(contract_schema: Mapping[str, Any]) -> str:
    lines = ["pub static EVENT_DESCRIPTORS: &[EventDescriptor] = &["]
    for item in contract_schema["event_descriptors"]:
        lines.extend(
            [
                "    EventDescriptor {",
                f"        event_topic: {rust_string(item['event_topic'])},",
                f"        module: {rust_string(item['module'])},",
                f"        name: {rust_string(item['name'])},",
                f"        schema_id: {rust_string(item['schema_id'])},",
                f"        schema_hash: {rust_string(item['schema_hash'])},",
                f"        required_permissions: {rust_slice(item['required_perms'])},",
                f"        bounded: {str(item['bounded']).lower()},",
                f"        authorized: {str(item['authorized']).lower()},",
                f"        ordered_event_group: {rust_option(item['ordered_event_group'])},",
                f"        remote_raw_audio_route: {str(item['remote_raw_audio_route']).lower()},",
                "    },",
            ]
        )
    lines.append("];")
    return "\n".join(lines)


def _render_validator(contract_schema: Mapping[str, Any], model_modules: Mapping[str, str]) -> str:
    arms: list[str] = []
    for item in contract_schema["schemas"]:
        model_name = item["model_name"]
        module_name = model_modules[model_name]
        rust_name = rust_type_name(model_name)
        arms.append(
            f"        {rust_string(item['schema_id'])} => "
            f"serde_json::from_value::<models::{module_name}::{rust_name}>(value)"
            ".and_then(serde_json::to_value).map_err(|_| ContractParseError::Decode { "
            "schema_id: schema_id.to_owned() }),"
        )
    arms.append("        _ => Err(ContractParseError::UnknownSchema(schema_id.to_owned())),")
    return "\n".join(
        [
            "pub fn normalize_generated_contract(",
            "    schema_id: &str,",
            "    value: serde_json::Value,",
            ") -> Result<serde_json::Value, ContractParseError> {",
            "    validate_contract_schema(schema_id, &value)?;",
            "    match schema_id {",
            *arms,
            "    }",
            "}",
            "",
            "pub fn validate_generated_contract(",
            "    schema_id: &str,",
            "    value: serde_json::Value,",
            ") -> Result<(), ContractParseError> {",
            "    normalize_generated_contract(schema_id, value).map(|_| ())",
            "}",
        ]
    )


def render_rust_module(contract_schema: Mapping[str, Any]) -> str:
    """Render generated typed modules and descriptor tables."""

    models, model_modules = _render_models(contract_schema)
    sections = [
        GENERATED_HEADER,
        "use crate::{validate_contract_schema, ContractParseError, EventDescriptor, MethodDescriptor, SchemaDescriptor, StreamingDescriptor};",
        models,
        _render_schema_descriptors(contract_schema, model_modules),
        _render_method_descriptors(contract_schema),
        _render_event_descriptors(contract_schema),
        "pub fn schema_by_id(schema_id: &str) -> Option<&'static SchemaDescriptor> {\n"
        "    SCHEMA_DESCRIPTORS.iter().find(|item| item.schema_id == schema_id)\n}",
        "pub fn method_by_id(method_id: &str) -> Option<&'static MethodDescriptor> {\n"
        "    METHOD_DESCRIPTORS.iter().find(|item| item.method_id == method_id)\n}",
        "pub fn event_by_topic(topic: &str) -> Option<&'static EventDescriptor> {\n"
        "    EVENT_DESCRIPTORS.iter().find(|item| item.event_topic == topic)\n}",
        _render_validator(contract_schema, model_modules),
    ]
    return "\n\n".join(sections) + "\n"


def render_vector_fixture(contract_schema: Mapping[str, Any]) -> str:
    """Render the shared Python/Zod/Rust parser-vector artifact."""

    vectors: list[dict[str, Any]] = []
    for item in contract_schema["schemas"]:
        raw_vectors = item.get("vectors") or {}
        positive = raw_vectors.get("positive")
        if positive:
            vectors.append(
                {
                    "accepted": True,
                    "direction": item["direction"],
                    "input": positive["input"],
                    "method_id": item["method_id"],
                    "model_name": item["model_name"],
                    "normalized": positive["normalized"],
                    "normalized_hash": positive["normalized_hash"],
                    "schema_id": item["schema_id"],
                }
            )
        for index, negative in enumerate(raw_vectors.get("negative_cases") or []):
            vectors.append(
                {
                    "accepted": False,
                    "case_index": index,
                    "direction": item["direction"],
                    "input": negative["input"],
                    "issue_category": negative["issue_category"],
                    "issue_path": negative["issue_path"],
                    "method_id": item["method_id"],
                    "model_name": item["model_name"],
                    "schema_id": item["schema_id"],
                }
            )
    fixture = {
        "artifact": "aurora-rust-contract-parse-vectors",
        "generator_format_version": GENERATOR_FORMAT_VERSION,
        "schema_artifact": contract_schema["artifact"],
        "schema_content_hash": sha256_text(canonical_json(contract_schema)),
        "vectors": vectors,
    }
    return json.dumps(fixture, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def render_outputs(contract_schema: Mapping[str, Any]) -> dict[str, str]:
    """Render every checked crate output keyed by a crate-relative path."""

    outputs = {"src/generated.rs": _format_rust(render_rust_module(contract_schema))}
    for item in _deduplicated_schemas(contract_schema):
        module_name = snake_case(item["model_name"])
        outputs[f"schema/{module_name}.json"] = (
            json.dumps(item["schema"], ensure_ascii=False, indent=2, sort_keys=True) + "\n"
        )
    return outputs


def _write_atomic(path: Path, source: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False
    ) as handle:
        handle.write(source)
        tmp_path = Path(handle.name)
    try:
        os.replace(tmp_path, path)
    finally:
        tmp_path.unlink(missing_ok=True)


def _format_rust(source: str) -> str:
    """Format generated Rust with the workspace-pinned toolchain."""

    result = subprocess.run(
        ["rustfmt", "--edition", "2021", "--emit", "stdout"],
        cwd=REPO_ROOT / "rust",
        input=source,
        capture_output=True,
        check=False,
        encoding="utf-8",
    )
    if result.returncode != 0:
        raise GenerationError(f"rustfmt rejected generated contracts: {result.stderr.strip()}")
    return result.stdout


def _display_path(path: Path) -> str:
    """Render paths relative to the repository when possible."""

    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def generate(
    *, schema_input: Path, crate_dir: Path, fixture_output: Path, check: bool = False
) -> None:
    """Generate or verify all Rust contract outputs."""

    contract_schema = json.loads(schema_input.read_text(encoding="utf-8"))
    outputs = render_outputs(contract_schema)
    expected_schema_paths = {
        crate_dir / relative for relative in outputs if relative.startswith("schema/")
    }
    existing_schema_paths = set((crate_dir / "schema").glob("*.json"))
    stale_paths = existing_schema_paths - expected_schema_paths
    fixture_source = render_vector_fixture(contract_schema)

    mismatches: list[Path] = []
    for relative, source in outputs.items():
        path = crate_dir / relative
        if not path.exists() or path.read_text(encoding="utf-8") != source:
            mismatches.append(path)
    if not fixture_output.exists() or fixture_output.read_text(encoding="utf-8") != fixture_source:
        mismatches.append(fixture_output)
    mismatches.extend(sorted(stale_paths))

    if check:
        if mismatches:
            rendered = ", ".join(_display_path(path) for path in mismatches)
            raise GenerationError(f"Rust contract outputs are stale: {rendered}")
        return

    for stale_path in sorted(stale_paths):
        stale_path.unlink()
    for relative, source in outputs.items():
        _write_atomic(crate_dir / relative, source)
    _write_atomic(fixture_output, fixture_source)


def main() -> int:
    """Run deterministic Rust contract generation or a no-diff check."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema-input", type=Path, default=DEFAULT_SCHEMA_INPUT)
    parser.add_argument("--crate-dir", type=Path, default=DEFAULT_CRATE_DIR)
    parser.add_argument("--fixture-output", type=Path, default=DEFAULT_FIXTURE_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generate(
        schema_input=args.schema_input,
        crate_dir=args.crate_dir,
        fixture_output=args.fixture_output,
        check=args.check,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
