"""Generate deterministic Rust DTOs and descriptors from Aurora contract schemas."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import tempfile
from collections.abc import Iterable, Mapping
from importlib import import_module
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCHEMA_INPUT = REPO_ROOT / "packages/aurora-sdk/src/generated/backend-contracts.schema.json"
DEFAULT_CRATE_DIR = REPO_ROOT / "rust/crates/aurora-contracts"
DEFAULT_FIXTURE_OUTPUT = (
    REPO_ROOT / "tests/fixtures/local_speech/runtime/contracts/backend_contract_parse_vectors.json"
)
GENERATOR_FORMAT_VERSION = "aurora-rust-contract-codegen-v1"
GENERATED_HEADER = "// Generated by scripts/generate_rust_contracts.py. Do not edit by hand."
NORMALIZATION_MARKERS = {
    "x-aurora-tts-operation-id",
    "x-aurora-speech-language-string-normalize",
    "x-aurora-speech-language-auto-null",
    "x-aurora-speech-language-array-normalize",
    "x-aurora-bounded-nonblank-string-set-normalize",
    "x-aurora-unique-string-array-normalize",
    "x-aurora-route-explain-no-raw-payload",
    "x-aurora-route-explain-selector-fields",
    "x-aurora-route-explain-speech-no-raw-payload",
}

_CLONE_VOICE_ID = "clone:123e4567-e89b-42d3-a456-426614174000"
_STANDARD_VOICE_ID = "standard:starter:voice"
_SHA256 = "1" * 64
_MARKER_POSITIVE_INPUTS: dict[str, dict[str, Any]] = {
    "Gateway.ExplainRoute.input.RouteExplainRequest": {
        "topic": "TTS.Request",
        "selector": {"peer_id": "peer-1"},
        "speech": {
            "language_requirement": {
                "mode": "auto",
                "auto_language_candidates": [" EN ", "de", "en"],
                "digest": "9b3fc27fe4d574def0265873b3d71aa1efa79169d71005ae823a56f398aac40c",
            }
        },
    },
    "TTS.CreateVoiceProfile.input.TTSCreateVoiceProfileRequest": {
        "operation_id": " create-1 ",
        "display_name": "Clone",
        "sealed_audio_ref": "voice-import:upload-1",
        "language": " EN ",
        "consent": True,
    },
    "TTS.DeleteVoiceProfile.input.TTSDeleteVoiceProfileRequest": {
        "operation_id": " delete-1 ",
        "voice_id": _CLONE_VOICE_ID,
    },
    "TTS.GetCapabilities.output.TTSGetCapabilitiesResponse": {
        "capabilities": {
            "ready": True,
            "model_status": "ready",
            "supported_language_pack_ids": ["pack-b", "pack-a", "pack-a"],
            "installed_language_pack_ids": ["pack-a", "pack-b"],
            "resident_language_pack_ids": ["pack-a"],
            "resident_language_packs": [
                {"pack_id": "pack-a", "ready_languages": [" EN ", "de", "en"]}
            ],
            "ready_languages": ["de", " EN "],
            "sample_rates": [24000],
            "resident_base_model_count": 1,
        }
    },
    "TTS.GetVoiceProfile.output.TTSGetVoiceProfileResponse": {
        "found": True,
        "profile": {
            "voice_id": _CLONE_VOICE_ID,
            "kind": "cloned",
            "display_name": "Clone",
            "revision": "rev-1",
            "compatible_language_pack_ids": ["pack-b", "pack-a", "pack-a"],
            "visibility": "allowed_peers",
            "allowed_peer_ids": ["peer-b", "peer-a", "peer-b"],
        },
    },
    "TTS.InstallVoiceProfile.input.TTSInstallVoiceProfileRequest": {
        "operation_id": " install-1 ",
        "voice_id": _STANDARD_VOICE_ID,
    },
    "TTS.ListVoiceProfiles.output.TTSListVoiceProfilesResponse": {
        "profiles": [
            {
                "voice_id": _CLONE_VOICE_ID,
                "kind": "cloned",
                "display_name": "Clone",
                "revision": "rev-1",
                "compatible_language_pack_ids": ["pack-b", "pack-a", "pack-a"],
                "visibility": "allowed_peers",
                "allowed_peer_ids": ["peer-b", "peer-a", "peer-b"],
            }
        ]
    },
    "TTS.ListVoices.input.TTSListVoicesRequest": {"language": " EN "},
    "TTS.ListVoices.output.TTSListVoicesResponse": {
        "voices": [
            {
                "voice_id": _STANDARD_VOICE_ID,
                "kind": "standard",
                "display_name": "Voice",
                "revision": "rev-1",
                "ready": True,
                "compatible_language_pack_ids": ["pack-b", "pack-a", "pack-a"],
            }
        ]
    },
    "TTS.RemoveVoiceProfile.input.TTSRemoveVoiceProfileRequest": {
        "operation_id": " remove-1 ",
        "voice_id": _CLONE_VOICE_ID,
    },
    "TTS.Request.input.TTSRequest": {"text": "hello", "language": " EN "},
    "TTS.SetDefaultVoice.input.TTSSetDefaultVoiceRequest": {
        "operation_id": " default-1 ",
        "voice_id": _STANDARD_VOICE_ID,
        "expected_revision": "rev-1",
    },
    "TTS.StreamStart.input.TTSStreamStartRequest": {"stream_id": "stream-1", "language": " EN "},
    "TTS.Synthesize.input.TTSSynthesizeRequest": {"text": "hello", "language": " EN "},
    "TTS.UpdateVoiceProfile.input.TTSUpdateVoiceProfileRequest": {
        "operation_id": " update-1 ",
        "voice_id": _STANDARD_VOICE_ID,
        "visibility": "allowed_peers",
        "allowed_peer_ids": ["peer-b", "peer-a", "peer-b"],
    },
    "TTS.VoiceImportAbort.input.TTSVoiceImportAbortRequest": {
        "operation_id": " abort-1 ",
        "upload_id": "upload-1",
    },
    "TTS.VoiceImportChunk.input.TTSVoiceImportChunkRequest": {
        "operation_id": " chunk-1 ",
        "upload_id": "upload-1",
        "sequence": 0,
        "chunk_data": "aGVsbG8=",
    },
    "TTS.VoiceImportEnd.input.TTSVoiceImportEndRequest": {
        "operation_id": " end-1 ",
        "upload_id": "upload-1",
        "final_sequence": 0,
        "final_sha256": _SHA256,
    },
    "TTS.VoiceImportStart.input.TTSVoiceImportStartRequest": {
        "operation_id": " start-1 ",
        "expected_total_bytes": 5,
        "format": "wav",
        "sample_rate": 24000,
        "sha256": _SHA256,
    },
    "Transcription.Transcribe.input.TranscribeAudioRequest": {
        "audio_data": "AA==",
        "language": " AUTO ",
        "auto_language_candidates": [" EN ", "de", "en"],
    },
}


class GenerationError(ValueError):
    """Raised when normalized backend contracts cannot produce safe Rust output."""


def canonical_json(value: Any) -> str:
    """Return Aurora's deterministic JSON representation."""

    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def sha256_text(value: str) -> str:
    """Return the lowercase SHA-256 digest for UTF-8 text."""

    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def snake_case(value: str) -> str:
    """Convert a generated model name into a stable Rust module name."""

    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", value):
        raise GenerationError(f"unsafe generated model name: {value!r}")
    first = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", value)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", first).lower()


def rust_type_name(value: str) -> str:
    """Return typify's stable UpperCamelCase spelling for a model name."""

    return "".join(part.capitalize() for part in snake_case(value).split("_"))


def rust_string(value: str) -> str:
    """Render a Python string as a Rust string literal."""

    return json.dumps(value, ensure_ascii=False)


def rust_option(value: str | None) -> str:
    """Render an optional Rust string literal."""

    return "None" if value is None else f"Some({rust_string(value)})"


def rust_slice(values: Iterable[str]) -> str:
    """Render a static Rust string slice."""

    return "&[" + ", ".join(rust_string(value) for value in values) + "]"


def _deduplicated_schemas(contract_schema: Mapping[str, Any]) -> list[dict[str, Any]]:
    by_model: dict[str, dict[str, Any]] = {}
    for raw in contract_schema.get("schemas", []):
        if not isinstance(raw, dict):
            raise GenerationError("contract schemas must be objects")
        model_name = raw.get("model_name")
        schema_hash = raw.get("schema_hash")
        schema = raw.get("schema")
        if not isinstance(model_name, str) or not isinstance(schema_hash, str):
            raise GenerationError("contract schema identity is incomplete")
        if not isinstance(schema, dict):
            raise GenerationError(f"contract schema {model_name} is not an object")
        existing = by_model.get(model_name)
        if existing is not None and existing["schema_hash"] != schema_hash:
            raise GenerationError(f"model {model_name} has conflicting schema hashes")
        by_model.setdefault(model_name, raw)
    return sorted(by_model.values(), key=lambda item: item["model_name"])


def _walk_marker_paths(schema: Any, path: str = "$") -> list[str]:
    paths: list[str] = []
    if isinstance(schema, dict):
        for marker in sorted(NORMALIZATION_MARKERS):
            if schema.get(marker) is True:
                paths.append(f"{path}:{marker}")
        for key, value in schema.items():
            if key.startswith("x-aurora"):
                continue
            paths.extend(_walk_marker_paths(value, f"{path}.{key}"))
    elif isinstance(schema, list):
        for index, value in enumerate(schema):
            paths.extend(_walk_marker_paths(value, f"{path}.{index}"))
    return paths


def _model_class(model_name: str) -> Any:
    for module_name in (
        "app.shared.contracts.models.aurora",
        "app.shared.contracts.models.gateway",
        "app.shared.contracts.models.orchestrator",
        "app.shared.contracts.models.stt",
        "app.shared.contracts.models.tts",
        "app.shared.contracts.models.tooling",
    ):
        module = import_module(module_name)
        model = getattr(module, model_name, None)
        if model is not None:
            return model
    raise GenerationError(f"cannot locate Pydantic model for {model_name}")


def _pydantic_normalized(model_name: str, value: Any) -> Any:
    model = _model_class(model_name)
    parsed = model.model_validate(value)
    return parsed.model_dump(mode="json", exclude_none=True)


def _matching_marker_path(marker_paths: list[str], fragment: str, marker: str) -> str:
    matches = [path for path in marker_paths if fragment in path and path.endswith(f":{marker}")]
    if len(matches) != 1:
        raise GenerationError(
            f"expected exactly one marker path for {fragment!r} / {marker}, found {matches}"
        )
    return matches[0]


def _marker_negative_cases(
    schema_id: str, marker_paths: list[str], base: Mapping[str, Any]
) -> list[dict[str, Any]]:
    cases: list[dict[str, Any]] = []

    def add(
        input_value: dict[str, Any],
        issue_path: str,
        issue_category: str,
        marker_path: str,
    ) -> None:
        cases.append(
            {
                "accepted": False,
                "input": input_value,
                "issue_category": issue_category,
                "issue_path": issue_path,
                "marker_paths": [marker_path],
            }
        )

    if "operation_id" in base:
        operation_marker = _matching_marker_path(
            marker_paths, "operation_id", "x-aurora-tts-operation-id"
        )
        invalid = dict(base)
        invalid["operation_id"] = " bad id "
        add(invalid, "$.operation_id", "tts_operation_id", operation_marker)
        oversized = dict(base)
        oversized["operation_id"] = f" {'a' * 127} "
        add(oversized, "$.operation_id", "tts_operation_id", operation_marker)
    if "language" in base and any(
        path.endswith(":x-aurora-speech-language-string-normalize") for path in marker_paths
    ):
        language_marker = _matching_marker_path(
            marker_paths, "language", "x-aurora-speech-language-string-normalize"
        )
        invalid = dict(base)
        invalid["language"] = "pt_BR"
        add(invalid, "$.language", "speech_language", language_marker)
    if schema_id == "TTS.CreateVoiceProfile.input.TTSCreateVoiceProfileRequest":
        language_marker = _matching_marker_path(
            marker_paths, "language", "x-aurora-speech-language-string-normalize"
        )
        invalid = dict(base)
        invalid["language"] = "pt_BR"
        add(invalid, "$.language", "speech_language", language_marker)
    if schema_id == "TTS.UpdateVoiceProfile.input.TTSUpdateVoiceProfileRequest":
        peer_marker = _matching_marker_path(
            marker_paths,
            "allowed_peer_ids",
            "x-aurora-bounded-nonblank-string-set-normalize",
        )
        invalid = dict(base)
        invalid["allowed_peer_ids"] = ["peer-a", "   "]
        add(invalid, "$.allowed_peer_ids", "bounded_nonblank_string_set", peer_marker)
    if schema_id == "TTS.GetCapabilities.output.TTSGetCapabilitiesResponse":
        ready_marker = _matching_marker_path(
            marker_paths,
            "TTSCapabilities.properties.ready_languages",
            "x-aurora-speech-language-array-normalize",
        )
        invalid = json.loads(json.dumps(base))
        invalid["capabilities"]["ready_languages"] = ["pt_BR"]
        add(invalid, "$.capabilities.ready_languages", "speech_language_array", ready_marker)
        resident_pack_ready_marker = _matching_marker_path(
            marker_paths,
            "TTSResidentLanguagePack.properties.ready_languages",
            "x-aurora-speech-language-array-normalize",
        )
        invalid = json.loads(json.dumps(base))
        invalid["capabilities"]["resident_language_packs"][0]["ready_languages"] = ["pt_BR"]
        add(
            invalid,
            "$.capabilities.resident_language_packs.0.ready_languages",
            "speech_language_array",
            resident_pack_ready_marker,
        )
        for field in (
            "supported_language_pack_ids",
            "installed_language_pack_ids",
            "resident_language_pack_ids",
        ):
            pack_marker = _matching_marker_path(
                marker_paths, field, "x-aurora-bounded-nonblank-string-set-normalize"
            )
            invalid = json.loads(json.dumps(base))
            invalid["capabilities"][field] = ["   "]
            add(
                invalid,
                f"$.capabilities.{field}",
                "bounded_nonblank_string_set",
                pack_marker,
            )
    if schema_id == "TTS.GetVoiceProfile.output.TTSGetVoiceProfileResponse":
        allowed_marker = _matching_marker_path(
            marker_paths, "allowed_peer_ids", "x-aurora-bounded-nonblank-string-set-normalize"
        )
        invalid = json.loads(json.dumps(base))
        invalid["profile"]["allowed_peer_ids"] = ["peer-a", "   "]
        add(invalid, "$.profile.allowed_peer_ids", "bounded_nonblank_string_set", allowed_marker)
        pack_marker = _matching_marker_path(
            marker_paths,
            "compatible_language_pack_ids",
            "x-aurora-bounded-nonblank-string-set-normalize",
        )
        invalid = json.loads(json.dumps(base))
        invalid["profile"]["compatible_language_pack_ids"] = ["   "]
        add(
            invalid,
            "$.profile.compatible_language_pack_ids",
            "bounded_nonblank_string_set",
            pack_marker,
        )
    if schema_id == "TTS.ListVoiceProfiles.output.TTSListVoiceProfilesResponse":
        allowed_marker = _matching_marker_path(
            marker_paths, "allowed_peer_ids", "x-aurora-bounded-nonblank-string-set-normalize"
        )
        invalid = json.loads(json.dumps(base))
        invalid["profiles"][0]["allowed_peer_ids"] = ["peer-a", "   "]
        add(
            invalid,
            "$.profiles.0.allowed_peer_ids",
            "bounded_nonblank_string_set",
            allowed_marker,
        )
        pack_marker = _matching_marker_path(
            marker_paths,
            "compatible_language_pack_ids",
            "x-aurora-bounded-nonblank-string-set-normalize",
        )
        invalid = json.loads(json.dumps(base))
        invalid["profiles"][0]["compatible_language_pack_ids"] = ["   "]
        add(
            invalid,
            "$.profiles.0.compatible_language_pack_ids",
            "bounded_nonblank_string_set",
            pack_marker,
        )
    if schema_id == "TTS.ListVoices.output.TTSListVoicesResponse":
        pack_marker = _matching_marker_path(
            marker_paths,
            "compatible_language_pack_ids",
            "x-aurora-bounded-nonblank-string-set-normalize",
        )
        invalid = json.loads(json.dumps(base))
        invalid["voices"][0]["compatible_language_pack_ids"] = ["   "]
        add(
            invalid,
            "$.voices.0.compatible_language_pack_ids",
            "bounded_nonblank_string_set",
            pack_marker,
        )
    if schema_id in {
        "Tooling.GetExportCatalog.output.ToolingGetExportCatalogResponse",
        "Tooling.GetTools.output.ToolingGetToolsResponse",
    }:
        legacy_marker = _matching_marker_path(
            marker_paths, "legacy_global_tool_ids", "x-aurora-unique-string-array-normalize"
        )
        invalid = json.loads(json.dumps(base))
        invalid["tools"][0]["legacy_global_tool_ids"] = ["legacy-a", " trimmed "]
        add(
            invalid,
            "$.tools.0.legacy_global_tool_ids",
            "unique_string_array_normalize",
            legacy_marker,
        )
    if schema_id == "Transcription.Transcribe.input.TranscribeAudioRequest":
        language_marker = _matching_marker_path(
            marker_paths, "language", "x-aurora-speech-language-auto-null"
        )
        invalid = dict(base)
        invalid["language"] = "pt_BR"
        add(invalid, "$.language", "speech_language", language_marker)
        candidates_marker = _matching_marker_path(
            marker_paths,
            "auto_language_candidates",
            "x-aurora-speech-language-array-normalize",
        )
        invalid = dict(base)
        invalid["auto_language_candidates"] = ["pt_BR"]
        add(invalid, "$.auto_language_candidates", "speech_language_array", candidates_marker)
    if schema_id == "Gateway.ExplainRoute.input.RouteExplainRequest":
        raw_marker = _matching_marker_path(
            marker_paths,
            "$:x-aurora-route-explain-no-raw-payload",
            "x-aurora-route-explain-no-raw-payload",
        )
        add(
            {"topic": "TTS.Request", "nested": {"messages": "secret"}},
            "$.nested.messages",
            "route_explain_raw_payload",
            raw_marker,
        )
        selector_marker = _matching_marker_path(
            marker_paths,
            "$:x-aurora-route-explain-selector-fields",
            "x-aurora-route-explain-selector-fields",
        )
        add(
            {"topic": "TTS.Request", "selector": {"peer_id": "peer-1", "raw_peer": "secret"}},
            "$.selector.raw_peer",
            "route_explain_selector_fields",
            selector_marker,
        )
        speech_raw_marker = _matching_marker_path(
            marker_paths,
            "$:x-aurora-route-explain-speech-no-raw-payload",
            "x-aurora-route-explain-speech-no-raw-payload",
        )
        add(
            {"topic": "TTS.Request", "speech": {"input": "secret"}},
            "$.speech.input",
            "route_explain_speech_raw_payload",
            speech_raw_marker,
        )
        language_marker = _matching_marker_path(
            marker_paths,
            "SpeechLanguageRequirement.properties.language",
            "x-aurora-speech-language-string-normalize",
        )
        invalid = json.loads(json.dumps(base))
        invalid["speech"]["language_requirement"] = {"mode": "exact", "language": "pt_BR"}
        add(
            invalid,
            "$.speech.language_requirement.language",
            "speech_language",
            language_marker,
        )
        candidates_marker = _matching_marker_path(
            marker_paths,
            "SpeechLanguageRequirement.properties.auto_language_candidates",
            "x-aurora-speech-language-array-normalize",
        )
        invalid = json.loads(json.dumps(base))
        invalid["speech"]["language_requirement"]["auto_language_candidates"] = ["pt_BR"]
        add(
            invalid,
            "$.speech.language_requirement.auto_language_candidates",
            "speech_language_array",
            candidates_marker,
        )
    return cases


def _marker_vectors(item: Mapping[str, Any], raw_vectors: Mapping[str, Any]) -> dict[str, Any]:
    schema_id = item["schema_id"]
    marker_paths = _walk_marker_paths(item["schema"])
    if not marker_paths:
        return dict(raw_vectors)
    if schema_id not in _MARKER_POSITIVE_INPUTS and not raw_vectors.get("positive"):
        raise GenerationError(f"missing marker vector fixture for {schema_id}")

    positive_input = (
        raw_vectors.get("positive", {}).get("input")
        if raw_vectors.get("positive")
        else _MARKER_POSITIVE_INPUTS[schema_id]
    )
    positive_normalized = _pydantic_normalized(item["model_name"], positive_input)
    positive_cases = [dict(case) for case in raw_vectors.get("positive_cases", ())]
    negative_cases = [dict(case) for case in raw_vectors.get("negative_cases", ())]
    negative_cases.extend(_marker_negative_cases(schema_id, marker_paths, positive_input))
    model = _model_class(item["model_name"])
    for case in negative_cases:
        if not case.get("marker_paths"):
            continue
        try:
            model.model_validate(case["input"])
        except Exception:
            continue
        raise GenerationError(
            f"marker negative vector unexpectedly accepted for {schema_id}: "
            f"{case['issue_category']}"
        )
    return {
        "positive": {
            "accepted": True,
            "input": positive_input,
            "marker_paths": marker_paths,
            "normalized": positive_normalized,
            "normalized_hash": sha256_text(canonical_json(positive_normalized)),
        },
        "positive_cases": positive_cases,
        "negative_cases": negative_cases,
    }


def _render_models(contract_schema: Mapping[str, Any]) -> tuple[str, dict[str, str]]:
    lines = ["pub mod models {"]
    model_modules: dict[str, str] = {}
    for item in _deduplicated_schemas(contract_schema):
        model_name = item["model_name"]
        module_name = snake_case(model_name)
        rust_name = rust_type_name(model_name)
        model_modules[model_name] = module_name
        lines.extend(
            [
                f"    pub mod {module_name} {{",
                f'        typify::import_types!(schema = "schema/{module_name}.json");',
                "    }",
                f"    pub use {module_name}::{rust_name};",
            ]
        )
    lines.append("}")
    return "\n".join(lines), model_modules


def _render_schema_descriptors(
    contract_schema: Mapping[str, Any], model_modules: Mapping[str, str]
) -> str:
    lines = ["pub static SCHEMA_DESCRIPTORS: &[SchemaDescriptor] = &["]
    for item in contract_schema["schemas"]:
        module_name = model_modules[item["model_name"]]
        lines.extend(
            [
                "    SchemaDescriptor {",
                f"        schema_id: {rust_string(item['schema_id'])},",
                f"        method_id: {rust_string(item['method_id'])},",
                f"        direction: {rust_string(item['direction'])},",
                f"        model_name: {rust_string(item['model_name'])},",
                f"        schema_hash: {rust_string(item['schema_hash'])},",
                f'        schema_json: include_str!("../schema/{module_name}.json"),',
                "    },",
            ]
        )
    lines.append("];")
    return "\n".join(lines)


def _render_method_descriptors(contract_schema: Mapping[str, Any]) -> str:
    lines = ["pub static METHOD_DESCRIPTORS: &[MethodDescriptor] = &["]
    for item in contract_schema["method_descriptors"]:
        streaming = item["streaming"]
        lines.extend(
            [
                "    MethodDescriptor {",
                f"        method_id: {rust_string(item['method_id'])},",
                f"        bus_topic: {rust_string(item['bus_topic'])},",
                f"        module: {rust_string(item['module'])},",
                f"        name: {rust_string(item['name'])},",
                f"        method_type: {rust_string(item['method_type'])},",
                f"        exposure: {rust_string(item['exposure'])},",
                f"        route_path: {rust_string(item['route_path'])},",
                f"        route_kind: {rust_string(item['route_kind'])},",
                f"        required_permissions: {rust_slice(item['required_perms'])},",
                f"        callable_feature_ids: {rust_slice(item['callable_feature_ids'])},",
                f"        input_schema_id: {rust_string(item['input_schema_id'])},",
                f"        output_schema_id: {rust_string(item['output_schema_id'])},",
                "        streaming: StreamingDescriptor {",
                f"            rpc_kind: {rust_string(streaming['rpc_kind'])},",
                f"            request_stream: {str(streaming['request_stream']).lower()},",
                f"            response_stream: {str(streaming['response_stream']).lower()},",
                "            ordered_command_group: "
                f"{rust_option(streaming['ordered_command_group'])},",
                f"            event_topic: {rust_option(streaming['event_topic'])},",
                "        },",
                "    },",
            ]
        )
    lines.append("];")
    return "\n".join(lines)


def _render_event_descriptors(contract_schema: Mapping[str, Any]) -> str:
    lines = ["pub static EVENT_DESCRIPTORS: &[EventDescriptor] = &["]
    for item in contract_schema["event_descriptors"]:
        lines.extend(
            [
                "    EventDescriptor {",
                f"        event_topic: {rust_string(item['event_topic'])},",
                f"        module: {rust_string(item['module'])},",
                f"        name: {rust_string(item['name'])},",
                f"        schema_id: {rust_string(item['schema_id'])},",
                f"        schema_hash: {rust_string(item['schema_hash'])},",
                f"        required_permissions: {rust_slice(item['required_perms'])},",
                f"        bounded: {str(item['bounded']).lower()},",
                f"        authorized: {str(item['authorized']).lower()},",
                f"        ordered_event_group: {rust_option(item['ordered_event_group'])},",
                f"        remote_raw_audio_route: {str(item['remote_raw_audio_route']).lower()},",
                "    },",
            ]
        )
    lines.append("];")
    return "\n".join(lines)


def _render_envelope_descriptors(contract_schema: Mapping[str, Any]) -> str:
    lines = ["pub static ENVELOPE_DESCRIPTORS: &[EnvelopeDescriptor] = &["]
    for item in contract_schema.get("envelope_descriptors", []):
        lines.extend(
            [
                "    EnvelopeDescriptor {",
                f"        envelope_topic: {rust_string(item['envelope_topic'])},",
                f"        module: {rust_string(item['module'])},",
                f"        name: {rust_string(item['name'])},",
                f"        schema_id: {rust_string(item['schema_id'])},",
                f"        schema_hash: {rust_string(item['schema_hash'])},",
                "        required_permissions_broad: "
                f"{rust_slice(item['required_permissions_broad'])},",
                "        required_permissions_scoped: "
                f"{rust_slice(item['required_permissions_scoped'])},",
                f"        scoped_topics: {rust_slice(item['scoped_topics'])},",
                f"        scoped_categories: {rust_slice(item['scoped_categories'])},",
                f"        requires_correlation_id: {str(item['requires_correlation_id']).lower()},",
                f"        bounded: {str(item['bounded']).lower()},",
                f"        authorized: {str(item['authorized']).lower()},",
                f"        route_path: {rust_string(item['route_path'])},",
                f"        route_kind: {rust_string(item['route_kind'])},",
                f"        descriptor_kind: {rust_string(item['descriptor_kind'])},",
                "    },",
            ]
        )
    lines.append("];")
    return "\n".join(lines)


def _rust_const_name(value: str) -> str:
    parts = [part for part in re.split(r"[^A-Za-z0-9]+", value) if part]
    candidate = "_".join(snake_case(part).upper() for part in parts)
    if not candidate or candidate[0].isdigit():
        raise GenerationError(f"cannot render Rust constant name for {value!r}")
    return candidate


def _render_identity_constants(contract_schema: Mapping[str, Any]) -> str:
    lines = ["pub mod ids {"]
    seen: dict[str, str] = {}
    for collection, key in (
        (contract_schema.get("method_descriptors", []), "method_id"),
        (contract_schema.get("event_descriptors", []), "event_topic"),
        (contract_schema.get("envelope_descriptors", []), "envelope_topic"),
    ):
        for item in collection:
            value = item[key]
            name = _rust_const_name(value)
            if existing := seen.get(name):
                raise GenerationError(
                    "duplicate generated Rust identity constant "
                    f"{name} for {existing!r} and {value!r}"
                )
            seen[name] = value
            lines.append(f"    pub const {name}: &str = {rust_string(value)};")
    lines.append("}")
    return "\n".join(lines)


def _render_validator(contract_schema: Mapping[str, Any], model_modules: Mapping[str, str]) -> str:
    arms: list[str] = []
    for item in contract_schema["schemas"]:
        model_name = item["model_name"]
        module_name = model_modules[model_name]
        rust_name = rust_type_name(model_name)
        arms.append(
            f"        {rust_string(item['schema_id'])} => "
            f"serde_json::from_value::<models::{module_name}::{rust_name}>(normalized)"
            ".and_then(serde_json::to_value).map_err(|_| ContractParseError::Decode { "
            "schema_id: schema_id.to_owned() }),"
        )
    arms.append("        _ => Err(ContractParseError::UnknownSchema(schema_id.to_owned())),")
    return "\n".join(
        [
            "pub fn normalize_generated_contract(",
            "    schema_id: &str,",
            "    value: serde_json::Value,",
            ") -> Result<serde_json::Value, ContractParseError> {",
            "    let (normalized, compiled) = normalize_contract_value(schema_id, value)?;",
            "    validate_normalized_contract_schema(schema_id, compiled, &normalized)?;",
            "    match schema_id {",
            *arms,
            "    }",
            "}",
            "",
            "pub fn validate_generated_contract(",
            "    schema_id: &str,",
            "    value: serde_json::Value,",
            ") -> Result<(), ContractParseError> {",
            "    normalize_generated_contract(schema_id, value).map(|_| ())",
            "}",
        ]
    )


def render_rust_module(contract_schema: Mapping[str, Any]) -> str:
    """Render generated typed modules and descriptor tables."""

    models, model_modules = _render_models(contract_schema)
    sections = [
        GENERATED_HEADER,
        "use crate::{normalize_contract_value, validate_normalized_contract_schema, ContractParseError, EnvelopeDescriptor, EventDescriptor, MethodDescriptor, SchemaDescriptor, StreamingDescriptor};",
        _render_identity_constants(contract_schema),
        models,
        _render_schema_descriptors(contract_schema, model_modules),
        _render_method_descriptors(contract_schema),
        _render_event_descriptors(contract_schema),
        _render_envelope_descriptors(contract_schema),
        "pub fn schema_by_id(schema_id: &str) -> Option<&'static SchemaDescriptor> {\n"
        "    SCHEMA_DESCRIPTORS.iter().find(|item| item.schema_id == schema_id)\n}",
        "pub fn method_by_id(method_id: &str) -> Option<&'static MethodDescriptor> {\n"
        "    METHOD_DESCRIPTORS.iter().find(|item| item.method_id == method_id)\n}",
        "pub fn event_by_topic(topic: &str) -> Option<&'static EventDescriptor> {\n"
        "    EVENT_DESCRIPTORS.iter().find(|item| item.event_topic == topic)\n}",
        "pub fn envelope_by_topic(topic: &str) -> Option<&'static EnvelopeDescriptor> {\n"
        "    ENVELOPE_DESCRIPTORS.iter().find(|item| item.envelope_topic == topic)\n}",
        _render_validator(contract_schema, model_modules),
    ]
    return "\n\n".join(sections) + "\n"


def render_vector_fixture(contract_schema: Mapping[str, Any]) -> str:
    """Render the shared Python/Zod/Rust parser-vector artifact."""

    vectors: list[dict[str, Any]] = []
    for item in contract_schema["schemas"]:
        raw_vectors = _marker_vectors(item, item.get("vectors") or {})
        positive = raw_vectors.get("positive")
        if positive:
            vectors.append(
                {
                    "accepted": True,
                    "direction": item["direction"],
                    "input": positive["input"],
                    "method_id": item["method_id"],
                    "model_name": item["model_name"],
                    "normalized": positive["normalized"],
                    "normalized_hash": positive["normalized_hash"],
                    "schema_id": item["schema_id"],
                    **(
                        {"marker_paths": positive["marker_paths"]}
                        if positive.get("marker_paths")
                        else {}
                    ),
                }
            )
        for case_index, extra_positive in enumerate(raw_vectors.get("positive_cases") or [], 1):
            vectors.append(
                {
                    "accepted": True,
                    "case_index": case_index,
                    "direction": item["direction"],
                    "input": extra_positive["input"],
                    "method_id": item["method_id"],
                    "model_name": item["model_name"],
                    "normalized": extra_positive["normalized"],
                    "normalized_hash": extra_positive["normalized_hash"],
                    "schema_id": item["schema_id"],
                }
            )
        for index, negative in enumerate(raw_vectors.get("negative_cases") or []):
            vectors.append(
                {
                    "accepted": False,
                    "case_index": index,
                    "direction": item["direction"],
                    "input": negative["input"],
                    "issue_category": negative["issue_category"],
                    "issue_path": negative["issue_path"],
                    "method_id": item["method_id"],
                    "model_name": item["model_name"],
                    "schema_id": item["schema_id"],
                    **(
                        {"marker_paths": negative["marker_paths"]}
                        if negative.get("marker_paths")
                        else {}
                    ),
                }
            )
    fixture = {
        "artifact": "aurora-rust-contract-parse-vectors",
        "generator_format_version": GENERATOR_FORMAT_VERSION,
        "schema_artifact": contract_schema["artifact"],
        "schema_content_hash": sha256_text(canonical_json(contract_schema)),
        "vectors": vectors,
    }
    return json.dumps(fixture, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def render_outputs(contract_schema: Mapping[str, Any]) -> dict[str, str]:
    """Render every checked crate output keyed by a crate-relative path."""

    outputs = {"src/generated.rs": _format_rust(render_rust_module(contract_schema))}
    for item in _deduplicated_schemas(contract_schema):
        module_name = snake_case(item["model_name"])
        outputs[f"schema/{module_name}.json"] = (
            json.dumps(item["schema"], ensure_ascii=False, indent=2, sort_keys=True) + "\n"
        )
    return outputs


def _write_atomic(path: Path, source: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False
    ) as handle:
        handle.write(source)
        tmp_path = Path(handle.name)
    try:
        os.replace(tmp_path, path)
    finally:
        tmp_path.unlink(missing_ok=True)


def _format_rust(source: str) -> str:
    """Format generated Rust with the workspace-pinned toolchain."""

    result = subprocess.run(
        ["rustfmt", "--edition", "2021", "--emit", "stdout"],
        cwd=REPO_ROOT / "rust",
        input=source,
        capture_output=True,
        check=False,
        encoding="utf-8",
    )
    if result.returncode != 0:
        raise GenerationError(f"rustfmt rejected generated contracts: {result.stderr.strip()}")
    return result.stdout


def _display_path(path: Path) -> str:
    """Render paths relative to the repository when possible."""

    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def generate(
    *, schema_input: Path, crate_dir: Path, fixture_output: Path, check: bool = False
) -> None:
    """Generate or verify all Rust contract outputs."""

    contract_schema = json.loads(schema_input.read_text(encoding="utf-8"))
    outputs = render_outputs(contract_schema)
    expected_schema_paths = {
        crate_dir / relative for relative in outputs if relative.startswith("schema/")
    }
    existing_schema_paths = set((crate_dir / "schema").glob("*.json"))
    stale_paths = existing_schema_paths - expected_schema_paths
    fixture_source = render_vector_fixture(contract_schema)

    mismatches: list[Path] = []
    for relative, source in outputs.items():
        path = crate_dir / relative
        if not path.exists() or path.read_text(encoding="utf-8") != source:
            mismatches.append(path)
    if not fixture_output.exists() or fixture_output.read_text(encoding="utf-8") != fixture_source:
        mismatches.append(fixture_output)
    mismatches.extend(sorted(stale_paths))

    if check:
        if mismatches:
            rendered = ", ".join(_display_path(path) for path in mismatches)
            raise GenerationError(f"Rust contract outputs are stale: {rendered}")
        return

    for stale_path in sorted(stale_paths):
        stale_path.unlink()
    for relative, source in outputs.items():
        _write_atomic(crate_dir / relative, source)
    _write_atomic(fixture_output, fixture_source)


def main() -> int:
    """Run deterministic Rust contract generation or a no-diff check."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema-input", type=Path, default=DEFAULT_SCHEMA_INPUT)
    parser.add_argument("--crate-dir", type=Path, default=DEFAULT_CRATE_DIR)
    parser.add_argument("--fixture-output", type=Path, default=DEFAULT_FIXTURE_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generate(
        schema_input=args.schema_input,
        crate_dir=args.crate_dir,
        fixture_output=args.fixture_output,
        check=args.check,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
