#!/usr/bin/env python3
"""Generate deterministic local-data SQLite migration manifests."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

SQL_NAME_RE = re.compile(r"^(?P<version>\d{4})_(?P<name>[a-z0-9_]+)\.sql$")
ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MIGRATIONS_DIR = ROOT / "packages/aurora-sdk/src/local-data/migrations/sqlite"
DEFAULT_TS_OUTPUT = ROOT / "packages/aurora-sdk/src/local-data/migration-manifest.ts"
DEFAULT_SCHEMA_OUTPUT = ROOT / "packages/aurora-sdk/src/local-data/generated/local-data.schema.json"


@dataclass(frozen=True)
class Migration:
    version: int
    name: str
    file: str
    checksum: str
    min_app_version: str
    requires_pre_migration_export: bool
    ledger_sql: str


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--migrations-dir", type=Path, default=DEFAULT_MIGRATIONS_DIR)
    parser.add_argument("--manifest-output", type=Path, default=DEFAULT_MIGRATIONS_DIR / "manifest.json")
    parser.add_argument("--ts-output", type=Path, default=DEFAULT_TS_OUTPUT)
    parser.add_argument("--rust-output", type=Path, default=None)
    parser.add_argument("--schema-output", type=Path, default=DEFAULT_SCHEMA_OUTPUT)
    args = parser.parse_args()

    migrations = read_migrations(args.migrations_dir)
    manifest = {
        "formatVersion": 1,
        "databaseName": "aurora-lightweight.db",
        "latestVersion": migrations[-1].version if migrations else 0,
        "migrations": [migration.__dict__ for migration in migrations],
    }
    schema_artifact = build_zod_schema_artifact()
    outputs = [
        (args.manifest_output, render_json(manifest)),
        (args.ts_output, render_ts(manifest)),
        (args.schema_output, render_json(schema_artifact)),
    ]
    if args.rust_output is not None:
        outputs.append((args.rust_output, render_rust_source(args.rust_output, args.migrations_dir, migrations)))
    write_outputs(outputs)


def read_migrations(directory: Path) -> list[Migration]:
    files = sorted(directory.glob("*.sql"))
    migrations: list[Migration] = []
    for expected, path in enumerate(files, start=1):
        match = SQL_NAME_RE.match(path.name)
        if match is None:
            raise SystemExit(f"invalid migration filename: {path.name}")
        version = int(match.group("version"))
        if version != expected:
            raise SystemExit(f"non-contiguous migration version: expected {expected:04d}, got {version:04d}")
        sql = path.read_text(encoding="utf-8")
        checksum = hashlib.sha256(sql.encode("utf-8")).hexdigest()
        name = match.group("name")
        migrations.append(
            Migration(
                version=version,
                name=name,
                file=path.name,
                checksum=checksum,
                min_app_version="0.1.0",
                requires_pre_migration_export=False,
                ledger_sql=ledger_sql(version, name, checksum),
            )
        )
    return migrations


def ledger_sql(version: int, name: str, checksum: str) -> str:
    return (
        "INSERT INTO aurora_schema_migrations (version, name, checksum, applied_at_ms) "
        f"VALUES ({version}, '{name}', '{checksum}', CAST(strftime('%s','now') AS INTEGER) * 1000);\n"
        f"PRAGMA user_version = {version};"
    )


def render_rust_source(output_path: Path, migrations_dir: Path, migrations: list[Migration]) -> str:
    entries = []
    for migration in migrations:
        sql_path = migrations_dir / migration.file
        include_path = os.path.relpath(sql_path, output_path.parent).replace(os.sep, "/")
        entries.append(
            "    LocalDataMigration {\n"
            f"        version: {migration.version},\n"
            f"        name: {rust_string(migration.name)},\n"
            f"        file: {rust_string(migration.file)},\n"
            f"        checksum: {rust_string(migration.checksum)},\n"
            f"        sql: include_str!({rust_string(include_path)}),\n"
            f"        ledger_sql: {rust_string(migration.ledger_sql)},\n"
            "    },"
        )
    latest = migrations[-1].version if migrations else 0
    return (
        "// @generated by scripts/generate_local_data_migration_manifest.py\n"
        "// Do not edit by hand.\n\n"
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n"
        "pub struct LocalDataMigration {\n"
        "    pub version: u32,\n"
        "    pub name: &'static str,\n"
        "    pub file: &'static str,\n"
        "    pub checksum: &'static str,\n"
        "    pub sql: &'static str,\n"
        "    pub ledger_sql: &'static str,\n"
        "}\n\n"
        "pub const LOCAL_DATA_DATABASE_NAME: &str = \"aurora-lightweight.db\";\n"
        f"pub const LOCAL_DATA_LATEST_VERSION: u32 = {latest};\n"
        "pub const LOCAL_DATA_MIGRATIONS: &[LocalDataMigration] = &[\n"
        + "\n".join(entries)
        + "\n];\n"
    )


def render_ts(manifest: dict[str, object]) -> str:
    encoded = json.dumps(manifest, indent=2, sort_keys=True)
    return (
        "import { validateLocalDataMigrationManifest } from './migration-manifest-runtime.js'\n\n"
        "export * from './migration-manifest-runtime.js'\n\n"
        f"export const LOCAL_DATA_MIGRATION_MANIFEST = {encoded} as const\n\n"
        "export const localDataMigrationManifest = validateLocalDataMigrationManifest(LOCAL_DATA_MIGRATION_MANIFEST)\n"
    )


def render_json(value: object) -> str:
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def rust_string(value: str) -> str:
    return json.dumps(value)


def write_outputs(outputs: list[tuple[Path, str]]) -> None:
    temporary_paths: list[Path] = []
    try:
        for path, content in outputs:
            path.parent.mkdir(parents=True, exist_ok=True)
            temporary = path.with_name(f".{path.name}.tmp")
            temporary.write_text(content, encoding="utf-8")
            temporary_paths.append(temporary)
        for temporary, (path, _) in zip(temporary_paths, outputs, strict=True):
            temporary.replace(path)
    finally:
        for temporary in temporary_paths:
            if temporary.exists():
                temporary.unlink()


def build_zod_schema_artifact() -> dict[str, object]:
    schema_source = ROOT / "packages/aurora-sdk/src/local-data/schema-artifact.ts"
    with tempfile.TemporaryDirectory(prefix="aurora-local-data-schema-") as tmp:
        tmp_path = Path(tmp)
        entry = tmp_path / "entry.ts"
        bundle = tmp_path / "entry.mjs"
        entry.write_text(
            "import { buildLocalDataJsonSchemaArtifact } from "
            f"{json.dumps(schema_source.as_posix())}\n"
            "console.log(JSON.stringify(buildLocalDataJsonSchemaArtifact()))\n",
            encoding="utf-8",
        )
        subprocess.run(
            [
                "pnpm",
                "exec",
                "esbuild",
                str(entry),
                "--bundle",
                "--platform=node",
                "--format=esm",
                "--log-level=silent",
                f"--outfile={bundle}",
            ],
            cwd=ROOT,
            check=True,
            stdout=subprocess.DEVNULL,
        )
        completed = subprocess.run(
            ["node", str(bundle)],
            cwd=ROOT,
            check=True,
            text=True,
            stdout=subprocess.PIPE,
        )
    return json.loads(completed.stdout)


if __name__ == "__main__":
    main()
