from collections.abc import Awaitable, Callable
from typing import Protocol

OnMessage = Callable[[bytes], Awaitable[None]]


class SignalingAdapter(Protocol):
    async def connect(self) -> None: ...
    async def join_room(
        self,
        app_id: str,
        room: str,
        peer_id: str,
        metadata: dict | None = None,
    ) -> None: ...
    async def send(self, channel: str, payload: bytes, to_peer: str | None = None) -> None: ...
    def on_message(self, channel: str, handler: OnMessage) -> None: ...
    async def leave(self) -> None: ...
    async def close(self) -> None: ...
